/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.controllers;

import com.splitit.sandbox.webapiv3.ApiHelper;
import com.splitit.sandbox.webapiv3.Server;
import com.splitit.sandbox.webapiv3.exceptions.ApiException;
import com.splitit.sandbox.webapiv3.exceptions.FailedResponseException;
import com.splitit.sandbox.webapiv3.exceptions.PlanErrorResponseException;
import com.splitit.sandbox.webapiv3.http.request.HttpMethod;
import com.splitit.sandbox.webapiv3.models.CheckInstallmentsEligibilityRequest;
import com.splitit.sandbox.webapiv3.models.EligibilityTermsAndConditionResponse;
import com.splitit.sandbox.webapiv3.models.InitiatePlanResponse;
import com.splitit.sandbox.webapiv3.models.InstallmentPlanCreateRequest;
import com.splitit.sandbox.webapiv3.models.InstallmentPlanCreateResponse;
import com.splitit.sandbox.webapiv3.models.InstallmentPlanGetResponse;
import com.splitit.sandbox.webapiv3.models.InstallmentPlanInitiateRequest;
import com.splitit.sandbox.webapiv3.models.InstallmentPlanRefundRequest;
import com.splitit.sandbox.webapiv3.models.InstallmentPlanRefundResponse;
import com.splitit.sandbox.webapiv3.models.InstallmentPlanSearchResponse;
import com.splitit.sandbox.webapiv3.models.InstallmentPlanUpdateRequest;
import com.splitit.sandbox.webapiv3.models.InstallmentPlanUpdateRequestByIdentifier;
import com.splitit.sandbox.webapiv3.models.InstallmentPlanUpdateResponse;
import com.splitit.sandbox.webapiv3.models.InstallmentsEligibilityResponse;
import com.splitit.sandbox.webapiv3.models.TestModesEnum;
import com.splitit.sandbox.webapiv3.models.VerifyAuthorizationResponse;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class InstallmentPlanController extends BaseController {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public InstallmentPlanController(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * @param  installmentPlanNumber  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentPlanGetResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public InstallmentPlanGetResponse installmentPlanGet(
            final String installmentPlanNumber,
            final String xSplititTouchPoint) throws ApiException, IOException {
        return prepareInstallmentPlanGetRequest(installmentPlanNumber,
                xSplititTouchPoint).execute();
    }

    /**
     * @param  installmentPlanNumber  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentPlanGetResponse response from the API call
     */
    public CompletableFuture<InstallmentPlanGetResponse> installmentPlanGetAsync(
            final String installmentPlanNumber,
            final String xSplititTouchPoint) {
        try {
            return prepareInstallmentPlanGetRequest(installmentPlanNumber,
            xSplititTouchPoint).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for installmentPlanGet.
     */
    private ApiCall<InstallmentPlanGetResponse, ApiException> prepareInstallmentPlanGetRequest(
            final String installmentPlanNumber,
            final String xSplititTouchPoint) {
        return new ApiCall.Builder<InstallmentPlanGetResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/api/installmentplans/{installmentPlanNumber}")
                        .templateParam(param -> param.key("installmentPlanNumber").value(installmentPlanNumber)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("X-Splitit-TouchPoint")
                                .value(xSplititTouchPoint).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("OAuth2-sandbox")
                                        .add("OAuth2-production")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, InstallmentPlanGetResponse.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  installmentPlanNumber  Optional parameter:
     * @param  refOrderNumber  Optional parameter:
     * @param  extendedParams  Optional parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentPlanSearchResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public InstallmentPlanSearchResponse installmentPlanSearch(
            final String installmentPlanNumber,
            final String refOrderNumber,
            final Object extendedParams,
            final String xSplititTouchPoint) throws ApiException, IOException {
        return prepareInstallmentPlanSearchRequest(installmentPlanNumber, refOrderNumber,
                extendedParams, xSplititTouchPoint).execute();
    }

    /**
     * @param  installmentPlanNumber  Optional parameter:
     * @param  refOrderNumber  Optional parameter:
     * @param  extendedParams  Optional parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentPlanSearchResponse response from the API call
     */
    public CompletableFuture<InstallmentPlanSearchResponse> installmentPlanSearchAsync(
            final String installmentPlanNumber,
            final String refOrderNumber,
            final Object extendedParams,
            final String xSplititTouchPoint) {
        try {
            return prepareInstallmentPlanSearchRequest(installmentPlanNumber, refOrderNumber,
            extendedParams, xSplititTouchPoint).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for installmentPlanSearch.
     */
    private ApiCall<InstallmentPlanSearchResponse, ApiException> prepareInstallmentPlanSearchRequest(
            final String installmentPlanNumber,
            final String refOrderNumber,
            final Object extendedParams,
            final String xSplititTouchPoint) {
        return new ApiCall.Builder<InstallmentPlanSearchResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/api/installmentplans/search")
                        .queryParam(param -> param.key("installmentPlanNumber")
                                .value(installmentPlanNumber).isRequired(false))
                        .queryParam(param -> param.key("refOrderNumber")
                                .value(refOrderNumber).isRequired(false))
                        .queryParam(param -> param.key("extendedParams")
                                .value(extendedParams).isRequired(false))
                        .headerParam(param -> param.key("X-Splitit-TouchPoint")
                                .value(xSplititTouchPoint).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("OAuth2-sandbox")
                                        .add("OAuth2-production")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, InstallmentPlanSearchResponse.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  xSplititIdempotencyKey  Required parameter:
     * @param  body  Required parameter:
     * @param  xSplititTestMode  Optional parameter: Example:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InitiatePlanResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public InitiatePlanResponse installmentPlanPost(
            final String xSplititIdempotencyKey,
            final InstallmentPlanInitiateRequest body,
            final TestModesEnum xSplititTestMode,
            final String xSplititTouchPoint) throws ApiException, IOException {
        return prepareInstallmentPlanPostRequest(xSplititIdempotencyKey, body, xSplititTestMode,
                xSplititTouchPoint).execute();
    }

    /**
     * @param  xSplititIdempotencyKey  Required parameter:
     * @param  body  Required parameter:
     * @param  xSplititTestMode  Optional parameter: Example:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InitiatePlanResponse response from the API call
     */
    public CompletableFuture<InitiatePlanResponse> installmentPlanPostAsync(
            final String xSplititIdempotencyKey,
            final InstallmentPlanInitiateRequest body,
            final TestModesEnum xSplititTestMode,
            final String xSplititTouchPoint) {
        try {
            return prepareInstallmentPlanPostRequest(xSplititIdempotencyKey, body, xSplititTestMode,
            xSplititTouchPoint).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for installmentPlanPost.
     */
    private ApiCall<InitiatePlanResponse, ApiException> prepareInstallmentPlanPostRequest(
            final String xSplititIdempotencyKey,
            final InstallmentPlanInitiateRequest body,
            final TestModesEnum xSplititTestMode,
            final String xSplititTouchPoint) {
        return new ApiCall.Builder<InitiatePlanResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/api/installmentplans/initiate")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("X-Splitit-IdempotencyKey")
                                .value(xSplititIdempotencyKey).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json-patch+json").isRequired(false))
                        .headerParam(param -> param.key("X-Splitit-TestMode")
                                .value((xSplititTestMode != null) ? xSplititTestMode.value() : null).isRequired(false))
                        .headerParam(param -> param.key("X-Splitit-TouchPoint")
                                .value(xSplititTouchPoint).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("OAuth2-sandbox")
                                        .add("OAuth2-production")))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, InitiatePlanResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("",
                                (reason, context) -> new PlanErrorResponseException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  xSplititIdempotencyKey  Required parameter:
     * @param  body  Required parameter:
     * @param  xSplititTestMode  Optional parameter: Example:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentPlanCreateResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public InstallmentPlanCreateResponse installmentPlanPost2(
            final String xSplititIdempotencyKey,
            final InstallmentPlanCreateRequest body,
            final TestModesEnum xSplititTestMode,
            final String xSplititTouchPoint) throws ApiException, IOException {
        return prepareInstallmentPlanPost2Request(xSplititIdempotencyKey, body, xSplititTestMode,
                xSplititTouchPoint).execute();
    }

    /**
     * @param  xSplititIdempotencyKey  Required parameter:
     * @param  body  Required parameter:
     * @param  xSplititTestMode  Optional parameter: Example:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentPlanCreateResponse response from the API call
     */
    public CompletableFuture<InstallmentPlanCreateResponse> installmentPlanPost2Async(
            final String xSplititIdempotencyKey,
            final InstallmentPlanCreateRequest body,
            final TestModesEnum xSplititTestMode,
            final String xSplititTouchPoint) {
        try {
            return prepareInstallmentPlanPost2Request(xSplititIdempotencyKey, body, xSplititTestMode,
            xSplititTouchPoint).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for installmentPlanPost2.
     */
    private ApiCall<InstallmentPlanCreateResponse, ApiException> prepareInstallmentPlanPost2Request(
            final String xSplititIdempotencyKey,
            final InstallmentPlanCreateRequest body,
            final TestModesEnum xSplititTestMode,
            final String xSplititTouchPoint) {
        return new ApiCall.Builder<InstallmentPlanCreateResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/api/installmentplans")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("X-Splitit-IdempotencyKey")
                                .value(xSplititIdempotencyKey).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json-patch+json").isRequired(false))
                        .headerParam(param -> param.key("X-Splitit-TestMode")
                                .value((xSplititTestMode != null) ? xSplititTestMode.value() : null).isRequired(false))
                        .headerParam(param -> param.key("X-Splitit-TouchPoint")
                                .value(xSplititTouchPoint).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("OAuth2-sandbox")
                                        .add("OAuth2-production")))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, InstallmentPlanCreateResponse.class))
                        .nullify404(false)
                        .localErrorCase("400",
                                 ErrorCase.setReason("",
                                (reason, context) -> new PlanErrorResponseException(reason, context)))
                        .localErrorCase("401",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  installmentPlanNumber  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the VerifyAuthorizationResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public VerifyAuthorizationResponse installmentPlanVerifyAuthorization(
            final String installmentPlanNumber,
            final String xSplititTouchPoint) throws ApiException, IOException {
        return prepareInstallmentPlanVerifyAuthorizationRequest(installmentPlanNumber,
                xSplititTouchPoint).execute();
    }

    /**
     * @param  installmentPlanNumber  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the VerifyAuthorizationResponse response from the API call
     */
    public CompletableFuture<VerifyAuthorizationResponse> installmentPlanVerifyAuthorizationAsync(
            final String installmentPlanNumber,
            final String xSplititTouchPoint) {
        try {
            return prepareInstallmentPlanVerifyAuthorizationRequest(installmentPlanNumber,
            xSplititTouchPoint).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for installmentPlanVerifyAuthorization.
     */
    private ApiCall<VerifyAuthorizationResponse, ApiException> prepareInstallmentPlanVerifyAuthorizationRequest(
            final String installmentPlanNumber,
            final String xSplititTouchPoint) {
        return new ApiCall.Builder<VerifyAuthorizationResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/api/installmentplans/{installmentPlanNumber}/verifyauthorization")
                        .templateParam(param -> param.key("installmentPlanNumber").value(installmentPlanNumber)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("X-Splitit-TouchPoint")
                                .value(xSplititTouchPoint).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("OAuth2-sandbox")
                                        .add("OAuth2-production")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, VerifyAuthorizationResponse.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  installmentPlanNumber  Required parameter:
     * @param  xSplititIdempotencyKey  Required parameter:
     * @param  body  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentPlanUpdateResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public InstallmentPlanUpdateResponse installmentPlanUpdateOrder(
            final String installmentPlanNumber,
            final String xSplititIdempotencyKey,
            final InstallmentPlanUpdateRequest body,
            final String xSplititTouchPoint) throws ApiException, IOException {
        return prepareInstallmentPlanUpdateOrderRequest(installmentPlanNumber,
                xSplititIdempotencyKey, body, xSplititTouchPoint).execute();
    }

    /**
     * @param  installmentPlanNumber  Required parameter:
     * @param  xSplititIdempotencyKey  Required parameter:
     * @param  body  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentPlanUpdateResponse response from the API call
     */
    public CompletableFuture<InstallmentPlanUpdateResponse> installmentPlanUpdateOrderAsync(
            final String installmentPlanNumber,
            final String xSplititIdempotencyKey,
            final InstallmentPlanUpdateRequest body,
            final String xSplititTouchPoint) {
        try {
            return prepareInstallmentPlanUpdateOrderRequest(installmentPlanNumber, xSplititIdempotencyKey,
            body, xSplititTouchPoint).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for installmentPlanUpdateOrder.
     */
    private ApiCall<InstallmentPlanUpdateResponse, ApiException> prepareInstallmentPlanUpdateOrderRequest(
            final String installmentPlanNumber,
            final String xSplititIdempotencyKey,
            final InstallmentPlanUpdateRequest body,
            final String xSplititTouchPoint) {
        return new ApiCall.Builder<InstallmentPlanUpdateResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/api/installmentplans/{installmentPlanNumber}/updateorder")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .templateParam(param -> param.key("installmentPlanNumber").value(installmentPlanNumber)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("X-Splitit-IdempotencyKey")
                                .value(xSplititIdempotencyKey).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json-patch+json").isRequired(false))
                        .headerParam(param -> param.key("X-Splitit-TouchPoint")
                                .value(xSplititTouchPoint).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("OAuth2-sandbox")
                                        .add("OAuth2-production")))
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, InstallmentPlanUpdateResponse.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  xSplititIdempotencyKey  Required parameter:
     * @param  body  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentPlanUpdateResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public InstallmentPlanUpdateResponse installmentPlanUpdateOrder2(
            final String xSplititIdempotencyKey,
            final InstallmentPlanUpdateRequestByIdentifier body,
            final String xSplititTouchPoint) throws ApiException, IOException {
        return prepareInstallmentPlanUpdateOrder2Request(xSplititIdempotencyKey, body,
                xSplititTouchPoint).execute();
    }

    /**
     * @param  xSplititIdempotencyKey  Required parameter:
     * @param  body  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentPlanUpdateResponse response from the API call
     */
    public CompletableFuture<InstallmentPlanUpdateResponse> installmentPlanUpdateOrder2Async(
            final String xSplititIdempotencyKey,
            final InstallmentPlanUpdateRequestByIdentifier body,
            final String xSplititTouchPoint) {
        try {
            return prepareInstallmentPlanUpdateOrder2Request(xSplititIdempotencyKey, body,
            xSplititTouchPoint).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for installmentPlanUpdateOrder2.
     */
    private ApiCall<InstallmentPlanUpdateResponse, ApiException> prepareInstallmentPlanUpdateOrder2Request(
            final String xSplititIdempotencyKey,
            final InstallmentPlanUpdateRequestByIdentifier body,
            final String xSplititTouchPoint) {
        return new ApiCall.Builder<InstallmentPlanUpdateResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/api/installmentplans/updateorder")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("X-Splitit-IdempotencyKey")
                                .value(xSplititIdempotencyKey).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json-patch+json").isRequired(false))
                        .headerParam(param -> param.key("X-Splitit-TouchPoint")
                                .value(xSplititTouchPoint).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("OAuth2-sandbox")
                                        .add("OAuth2-production")))
                        .httpMethod(HttpMethod.PUT))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, InstallmentPlanUpdateResponse.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  installmentPlanNumber  Required parameter:
     * @param  xSplititIdempotencyKey  Required parameter:
     * @param  body  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentPlanRefundResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public InstallmentPlanRefundResponse installmentPlanRefund(
            final String installmentPlanNumber,
            final String xSplititIdempotencyKey,
            final InstallmentPlanRefundRequest body,
            final String xSplititTouchPoint) throws ApiException, IOException {
        return prepareInstallmentPlanRefundRequest(installmentPlanNumber, xSplititIdempotencyKey,
                body, xSplititTouchPoint).execute();
    }

    /**
     * @param  installmentPlanNumber  Required parameter:
     * @param  xSplititIdempotencyKey  Required parameter:
     * @param  body  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentPlanRefundResponse response from the API call
     */
    public CompletableFuture<InstallmentPlanRefundResponse> installmentPlanRefundAsync(
            final String installmentPlanNumber,
            final String xSplititIdempotencyKey,
            final InstallmentPlanRefundRequest body,
            final String xSplititTouchPoint) {
        try {
            return prepareInstallmentPlanRefundRequest(installmentPlanNumber, xSplititIdempotencyKey, body,
            xSplititTouchPoint).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for installmentPlanRefund.
     */
    private ApiCall<InstallmentPlanRefundResponse, ApiException> prepareInstallmentPlanRefundRequest(
            final String installmentPlanNumber,
            final String xSplititIdempotencyKey,
            final InstallmentPlanRefundRequest body,
            final String xSplititTouchPoint) {
        return new ApiCall.Builder<InstallmentPlanRefundResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/api/installmentplans/{installmentPlanNumber}/refund")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .templateParam(param -> param.key("installmentPlanNumber").value(installmentPlanNumber)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("X-Splitit-IdempotencyKey")
                                .value(xSplititIdempotencyKey).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json-patch+json").isRequired(false))
                        .headerParam(param -> param.key("X-Splitit-TouchPoint")
                                .value(xSplititTouchPoint).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("OAuth2-sandbox")
                                        .add("OAuth2-production")))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, InstallmentPlanRefundResponse.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  xSplititIdempotencyKey  Required parameter:
     * @param  body  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentsEligibilityResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public InstallmentsEligibilityResponse installmentPlanCheckEligibility(
            final String xSplititIdempotencyKey,
            final CheckInstallmentsEligibilityRequest body,
            final String xSplititTouchPoint) throws ApiException, IOException {
        return prepareInstallmentPlanCheckEligibilityRequest(xSplititIdempotencyKey, body,
                xSplititTouchPoint).execute();
    }

    /**
     * @param  xSplititIdempotencyKey  Required parameter:
     * @param  body  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the InstallmentsEligibilityResponse response from the API call
     */
    public CompletableFuture<InstallmentsEligibilityResponse> installmentPlanCheckEligibilityAsync(
            final String xSplititIdempotencyKey,
            final CheckInstallmentsEligibilityRequest body,
            final String xSplititTouchPoint) {
        try {
            return prepareInstallmentPlanCheckEligibilityRequest(xSplititIdempotencyKey, body,
            xSplititTouchPoint).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for installmentPlanCheckEligibility.
     */
    private ApiCall<InstallmentsEligibilityResponse, ApiException> prepareInstallmentPlanCheckEligibilityRequest(
            final String xSplititIdempotencyKey,
            final CheckInstallmentsEligibilityRequest body,
            final String xSplititTouchPoint) {
        return new ApiCall.Builder<InstallmentsEligibilityResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/api/installmentplans/check-eligibility")
                        .bodyParam(param -> param.value(body))
                        .bodySerializer(() ->  ApiHelper.serialize(body))
                        .headerParam(param -> param.key("X-Splitit-IdempotencyKey")
                                .value(xSplititIdempotencyKey).isRequired(false))
                        .headerParam(param -> param.key("Content-Type")
                                .value("application/json-patch+json").isRequired(false))
                        .headerParam(param -> param.key("X-Splitit-TouchPoint")
                                .value(xSplititTouchPoint).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("OAuth2-sandbox")
                                        .add("OAuth2-production")))
                        .httpMethod(HttpMethod.POST))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, InstallmentsEligibilityResponse.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }

    /**
     * @param  ipn  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the EligibilityTermsAndConditionResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public EligibilityTermsAndConditionResponse installmentPlanGetEligibilityTermsAndCondition(
            final String ipn,
            final String xSplititTouchPoint) throws ApiException, IOException {
        return prepareInstallmentPlanGetEligibilityTermsAndConditionRequest(ipn,
                xSplititTouchPoint).execute();
    }

    /**
     * @param  ipn  Required parameter:
     * @param  xSplititTouchPoint  Optional parameter: TouchPoint
     * @return    Returns the EligibilityTermsAndConditionResponse response from the API call
     */
    public CompletableFuture<EligibilityTermsAndConditionResponse> installmentPlanGetEligibilityTermsAndConditionAsync(
            final String ipn,
            final String xSplititTouchPoint) {
        try {
            return prepareInstallmentPlanGetEligibilityTermsAndConditionRequest(ipn,
            xSplititTouchPoint).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for installmentPlanGetEligibilityTermsAndCondition.
     */
    private ApiCall<EligibilityTermsAndConditionResponse, ApiException> prepareInstallmentPlanGetEligibilityTermsAndConditionRequest(
            final String ipn,
            final String xSplititTouchPoint) {
        return new ApiCall.Builder<EligibilityTermsAndConditionResponse, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/api/installmentplans/{ipn}/legal")
                        .templateParam(param -> param.key("ipn").value(ipn)
                                .shouldEncode(true))
                        .headerParam(param -> param.key("X-Splitit-TouchPoint")
                                .value(xSplititTouchPoint).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .or(orAuth -> orAuth
                                        .add("OAuth2-sandbox")
                                        .add("OAuth2-production")))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .deserializer(
                                response -> ApiHelper.deserialize(response, EligibilityTermsAndConditionResponse.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("404",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .localErrorCase("500",
                                 ErrorCase.setReason("",
                                (reason, context) -> new FailedResponseException(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}