/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3;

import com.splitit.sandbox.webapiv3.authentication.OAuth2ProductionCredentials;
import com.splitit.sandbox.webapiv3.authentication.OAuth2ProductionModel;
import com.splitit.sandbox.webapiv3.authentication.OAuth2SandboxCredentials;
import com.splitit.sandbox.webapiv3.authentication.OAuth2SandboxModel;
import com.splitit.sandbox.webapiv3.http.client.ReadonlyHttpClientConfiguration;

/**
 * Configuration Interface for the library.
 */
public interface Configuration {

    /**
     * Current API environment.
     * @return a copy of environment
     */
    Environment getEnvironment();

    /**
     * Http Client Configuration instance.
     * @return a copy of httpClientConfig
     */
    ReadonlyHttpClientConfiguration getHttpClientConfig();

    /**
     * The timeout to use for making HTTP requests. The timeout to use for making HTTP requests.
     * @return a copy of timeout
     */
    long timeout();

    /**
     * The credentials to use with OAuth2Sandbox.
     * @return oAuth2SandboxCredentials
     */
    OAuth2SandboxCredentials getOAuth2SandboxCredentials();

    /**
     * The auth credential model for OAuth2Sandbox.
     * @return the instance of OAuth2SandboxModel
     */
    OAuth2SandboxModel getOAuth2SandboxModel();

    /**
     * The credentials to use with OAuth2Production.
     * @return oAuth2ProductionCredentials
     */
    OAuth2ProductionCredentials getOAuth2ProductionCredentials();

    /**
     * The auth credential model for OAuth2Production.
     * @return the instance of OAuth2ProductionModel
     */
    OAuth2ProductionModel getOAuth2ProductionModel();

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    String getBaseUri(Server server);

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    String getBaseUri();
}
