/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3;

import com.splitit.sandbox.webapiv3.authentication.OAuth2ProductionCredentials;
import com.splitit.sandbox.webapiv3.authentication.OAuth2ProductionManager;
import com.splitit.sandbox.webapiv3.authentication.OAuth2ProductionModel;
import com.splitit.sandbox.webapiv3.authentication.OAuth2SandboxCredentials;
import com.splitit.sandbox.webapiv3.authentication.OAuth2SandboxManager;
import com.splitit.sandbox.webapiv3.authentication.OAuth2SandboxModel;
import com.splitit.sandbox.webapiv3.controllers.InstallmentPlanController;
import com.splitit.sandbox.webapiv3.controllers.OAuthAuthorizationController;
import com.splitit.sandbox.webapiv3.http.client.HttpCallback;
import com.splitit.sandbox.webapiv3.http.client.HttpClientConfiguration;
import com.splitit.sandbox.webapiv3.http.client.ReadonlyHttpClientConfiguration;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Gateway class for the library.
 * This class acts as a factory for Controllers.
 * It holds the state of the SDK.
 */
public final class SplititWebApiV3Client implements Configuration {

    /**
     * Private store for controllers.
     */
    private InstallmentPlanController installmentPlan;
    private OAuthAuthorizationController oAuthAuthorization;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "APIMATIC 3.0";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * OAuth2SandboxManager.
     */
    private OAuth2SandboxManager oAuth2SandboxManager;

    /**
     * The instance of OAuth2SandboxModel.
     */
    private OAuth2SandboxModel oAuth2SandboxModel;

    /**
     * OAuth2ProductionManager.
     */
    private OAuth2ProductionManager oAuth2ProductionManager;

    /**
     * The instance of OAuth2ProductionModel.
     */
    private OAuth2ProductionModel oAuth2ProductionModel;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications = new HashMap<String, Authentication>();

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private SplititWebApiV3Client(Environment environment, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig, OAuth2SandboxModel oAuth2SandboxModel,
            OAuth2ProductionModel oAuth2ProductionModel, HttpCallback httpCallback) {
        this.environment = environment;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.httpCallback = httpCallback;

        this.oAuth2SandboxModel = oAuth2SandboxModel;
        this.oAuth2ProductionModel = oAuth2ProductionModel;

        this.oAuth2SandboxManager = new OAuth2SandboxManager(oAuth2SandboxModel);
        this.authentications.put("OAuth2-sandbox", oAuth2SandboxManager);

        this.oAuth2ProductionManager = new OAuth2ProductionManager(oAuth2ProductionModel);
        this.authentications.put("OAuth2-production", oAuth2ProductionManager);

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .compatibilityFactory(compatibilityFactory)
                .authentication(this.authentications)
                .callback(httpCallback)
                .userAgent(userAgent)
                .build();
        this.oAuth2SandboxManager.applyGlobalConfiguration(globalConfig);
        this.oAuth2ProductionManager.applyGlobalConfiguration(globalConfig);

        installmentPlan = new InstallmentPlanController(globalConfig);
        oAuthAuthorization = new OAuthAuthorizationController(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of InstallmentPlanController.
     * @return installmentPlan
     */
    public InstallmentPlanController getInstallmentPlanController() {
        return installmentPlan;
    }

    /**
     * Get the instance of OAuthAuthorizationController.
     * @return oAuthAuthorization
     */
    public OAuthAuthorizationController getOAuthAuthorizationController() {
        return oAuthAuthorization;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * The credentials to use with OAuth2Sandbox.
     * @return oAuth2SandboxCredentials
     */
    public OAuth2SandboxCredentials getOAuth2SandboxCredentials() {
        return oAuth2SandboxManager;
    }

    /**
     * The auth credential model for OAuth2Sandbox.
     * @return the instance of OAuth2SandboxModel
     */
    public OAuth2SandboxModel getOAuth2SandboxModel() {
        return oAuth2SandboxModel;
    }
    /**
     * The credentials to use with OAuth2Production.
     * @return oAuth2ProductionCredentials
     */
    public OAuth2ProductionCredentials getOAuth2ProductionCredentials() {
        return oAuth2ProductionManager;
    }

    /**
     * The auth credential model for OAuth2Production.
     * @return the instance of OAuth2ProductionModel
     */
    public OAuth2ProductionModel getOAuth2ProductionModel() {
        return oAuth2ProductionModel;
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://web-api-v3.sandbox.splitit.com/";
            }
            if (server.equals(Server.ACCESS_TOKEN_SERVER)) {
                return "https://id.sandbox.splitit.com/connect";
            }
            if (server.equals(Server.ACCESS_TOKEN_SERVER1)) {
                return "https://id.splitit.com/connect";
            }
        }
        if (environment.equals(Environment.ENVIRONMENT2)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://web-api-v3.splitit.com/";
            }
            if (server.equals(Server.ACCESS_TOKEN_SERVER)) {
                return "https://id.sandbox.splitit.com/connect";
            }
            if (server.equals(Server.ACCESS_TOKEN_SERVER1)) {
                return "https://id.splitit.com/connect";
            }
        }
        return "https://web-api-v3.sandbox.splitit.com/";
    }

    /**
     * Converts this SplititWebApiV3Client into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SplititWebApiV3Client [" + "environment=" + environment + ", httpClientConfig="
                + httpClientConfig + ", authentications=" + authentications + "]";
    }

    /**
     * Builds a new {@link SplititWebApiV3Client.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link SplititWebApiV3Client.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.httpClient = getHttpClient();
        builder.oAuth2SandboxCredentials(getOAuth2SandboxModel()
                .toBuilder().build());
        builder.oAuth2ProductionCredentials(getOAuth2ProductionModel()
                .toBuilder().build());
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(() -> ((HttpClientConfiguration) httpClientConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link SplititWebApiV3Client}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private HttpClient httpClient;
        private OAuth2SandboxModel oAuth2SandboxModel =
                new OAuth2SandboxModel.Builder("", "").build();
        private OAuth2ProductionModel oAuth2ProductionModel =
                new OAuth2ProductionModel.Builder("", "").build();
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();


        /**
         * Credentials setter for OAuth2SandboxCredentials.
         * @param oAuth2SandboxModel The instance of OAuth2SandboxModel.
         * @return The current instance of builder.
         */
        public Builder oAuth2SandboxCredentials(OAuth2SandboxModel oAuth2SandboxModel) {
            this.oAuth2SandboxModel = oAuth2SandboxModel;
            return this;
        }

        /**
         * Credentials setter for OAuth2ProductionCredentials.
         * @param oAuth2ProductionModel The instance of OAuth2ProductionModel.
         * @return The current instance of builder.
         */
        public Builder oAuth2ProductionCredentials(OAuth2ProductionModel oAuth2ProductionModel) {
            this.oAuth2ProductionModel = oAuth2ProductionModel;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Private Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param supplier Supplier for the builder of httpClientConfiguration.
         * @return Builder
         */
        private Builder httpClientConfig(Supplier<HttpClientConfiguration.Builder> supplier) {
            httpClientConfigBuilder = supplier.get();
            return this;
        }

        /**
         * Builds a new SplititWebApiV3Client object using the set fields.
         * @return SplititWebApiV3Client
         */
        public SplititWebApiV3Client build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new SplititWebApiV3Client(environment, httpClient, httpClientConfig,
                    oAuth2SandboxModel, oAuth2ProductionModel, httpCallback);
        }
    }
}