/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.splitit.sandbox.webapiv3.models.ErrorExtended;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for FailedResponseException type.
 */
public class FailedResponseException extends ApiException {
    private static final long serialVersionUID = 3530342015742456358L;
    private String traceId;
    private ErrorExtended error;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public FailedResponseException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for TraceId.
     * @return Returns the String
     */
    @JsonGetter("TraceId")
    public String getTraceId() {
        return this.traceId;
    }

    /**
     * Setter for TraceId.
     * @param traceId Value for String
     */
    @JsonSetter("TraceId")
    private void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    /**
     * Getter for Error.
     * @return Returns the ErrorExtended
     */
    @JsonGetter("Error")
    public ErrorExtended getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for ErrorExtended
     */
    @JsonSetter("Error")
    private void setError(ErrorExtended error) {
        this.error = error;
    }

    /**
     * Converts this FailedResponseException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FailedResponseException [" + "statusCode=" + getResponseCode() + ", message="
                + getMessage() + ", traceId=" + traceId + ", error=" + error + "]";
    }
}
