/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.splitit.sandbox.webapiv3.models.ErrorExtended;
import com.splitit.sandbox.webapiv3.models.PaymentInfo;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for PlanErrorResponseException type.
 */
public class PlanErrorResponseException extends ApiException {
    private static final long serialVersionUID = -1901941610749242498L;
    private String traceId;
    private ErrorExtended error;
    private String installmentPlanNumber;
    private PaymentInfo paymentInfo;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public PlanErrorResponseException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for TraceId.
     * @return Returns the String
     */
    @JsonGetter("TraceId")
    public String getTraceId() {
        return this.traceId;
    }

    /**
     * Setter for TraceId.
     * @param traceId Value for String
     */
    @JsonSetter("TraceId")
    private void setTraceId(String traceId) {
        this.traceId = traceId;
    }

    /**
     * Getter for Error.
     * @return Returns the ErrorExtended
     */
    @JsonGetter("Error")
    public ErrorExtended getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for ErrorExtended
     */
    @JsonSetter("Error")
    private void setError(ErrorExtended error) {
        this.error = error;
    }

    /**
     * Getter for InstallmentPlanNumber.
     * @return Returns the String
     */
    @JsonGetter("InstallmentPlanNumber")
    public String getInstallmentPlanNumber() {
        return this.installmentPlanNumber;
    }

    /**
     * Setter for InstallmentPlanNumber.
     * @param installmentPlanNumber Value for String
     */
    @JsonSetter("InstallmentPlanNumber")
    private void setInstallmentPlanNumber(String installmentPlanNumber) {
        this.installmentPlanNumber = installmentPlanNumber;
    }

    /**
     * Getter for PaymentInfo.
     * @return Returns the PaymentInfo
     */
    @JsonGetter("PaymentInfo")
    public PaymentInfo getPaymentInfo() {
        return this.paymentInfo;
    }

    /**
     * Setter for PaymentInfo.
     * @param paymentInfo Value for PaymentInfo
     */
    @JsonSetter("PaymentInfo")
    private void setPaymentInfo(PaymentInfo paymentInfo) {
        this.paymentInfo = paymentInfo;
    }

    /**
     * Converts this PlanErrorResponseException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlanErrorResponseException [" + "statusCode=" + getResponseCode() + ", message="
                + getMessage() + ", traceId=" + traceId + ", error=" + error
                + ", installmentPlanNumber=" + installmentPlanNumber + ", paymentInfo="
                + paymentInfo + "]";
    }
}
