/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.controllers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import com.splitit.sandbox.webapiv3.ApiHelper;
import com.splitit.sandbox.webapiv3.SplititWebApiV3Client;
import com.splitit.sandbox.webapiv3.exceptions.ApiException;
import io.apimatic.core.utilities.TestHelper;
import java.util.LinkedHashMap;
import java.util.Map;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

public class InstallmentPlanControllerTest extends BaseControllerTest {

    /**
     * Client instance.
     */
    private static SplititWebApiV3Client client;
    
    /**
     * Controller instance (for all tests).
     */
    private static InstallmentPlanController controller;

    /**
     * Setup test class.
     */
    @BeforeClass
    public static void setUpClass() {
        client = createConfiguration();
        controller = client.getInstallmentPlanController();
    }

    /**
     * Tear down test class.
     */
    @AfterClass
    public static void tearDownClass() {
        controller = null;
    }

    /**
     * Testcase for testing endpoint InstallmentPlan_Search.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestInstallmentPlanSearch2() throws Exception {
        // Parameters for the API call
        String installmentPlanNumber = null;
        String refOrderNumber = null;
        Object extendedParams = null;
        String xSplititTouchPoint = null;

        // Set callback and perform API call
        try {
            controller.installmentPlanSearch(installmentPlanNumber, refOrderNumber, extendedParams, xSplititTouchPoint);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "text/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

    }

    /**
     * Testcase for testing endpoint InstallmentPlan_Search.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestInstallmentPlanSearch() throws Exception {
        // Parameters for the API call
        String installmentPlanNumber = null;
        String refOrderNumber = null;
        Object extendedParams = null;
        String xSplititTouchPoint = null;

        // Set callback and perform API call
        try {
            controller.installmentPlanSearch(installmentPlanNumber, refOrderNumber, extendedParams, xSplititTouchPoint);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "text/plain");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

    }

    /**
     * Testcase for testing endpoint InstallmentPlan_Search.
     * @throws Throwable exception if occurs.
     */
    @Test
    public void testTestInstallmentPlanSearch1() throws Exception {
        // Parameters for the API call
        String installmentPlanNumber = null;
        String refOrderNumber = null;
        Object extendedParams = null;
        String xSplititTouchPoint = null;

        // Set callback and perform API call
        try {
            controller.installmentPlanSearch(installmentPlanNumber, refOrderNumber, extendedParams, xSplititTouchPoint);
        } catch (ApiException e) {
            // Empty block
        }

        // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders().asSimpleMap(), true));

    }

}
