/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AddressData type.
 */
public class AddressData {
    private String addressLine;
    private String addressLine2;
    private String city;
    private String country;
    private String state;
    private String zip;

    /**
     * Default constructor.
     */
    public AddressData() {
    }

    /**
     * Initialization constructor.
     * @param  addressLine  String value for addressLine.
     * @param  addressLine2  String value for addressLine2.
     * @param  city  String value for city.
     * @param  country  String value for country.
     * @param  state  String value for state.
     * @param  zip  String value for zip.
     */
    public AddressData(
            String addressLine,
            String addressLine2,
            String city,
            String country,
            String state,
            String zip) {
        this.addressLine = addressLine;
        this.addressLine2 = addressLine2;
        this.city = city;
        this.country = country;
        this.state = state;
        this.zip = zip;
    }

    /**
     * Getter for AddressLine.
     * @return Returns the String
     */
    @JsonGetter("AddressLine")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAddressLine() {
        return addressLine;
    }

    /**
     * Setter for AddressLine.
     * @param addressLine Value for String
     */
    @JsonSetter("AddressLine")
    public void setAddressLine(String addressLine) {
        this.addressLine = addressLine;
    }

    /**
     * Getter for AddressLine2.
     * @return Returns the String
     */
    @JsonGetter("AddressLine2")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAddressLine2() {
        return addressLine2;
    }

    /**
     * Setter for AddressLine2.
     * @param addressLine2 Value for String
     */
    @JsonSetter("AddressLine2")
    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    /**
     * Getter for City.
     * @return Returns the String
     */
    @JsonGetter("City")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCity() {
        return city;
    }

    /**
     * Setter for City.
     * @param city Value for String
     */
    @JsonSetter("City")
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for Country.
     * @return Returns the String
     */
    @JsonGetter("Country")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCountry() {
        return country;
    }

    /**
     * Setter for Country.
     * @param country Value for String
     */
    @JsonSetter("Country")
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for State.
     * @return Returns the String
     */
    @JsonGetter("State")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getState() {
        return state;
    }

    /**
     * Setter for State.
     * @param state Value for String
     */
    @JsonSetter("State")
    public void setState(String state) {
        this.state = state;
    }

    /**
     * Getter for Zip.
     * @return Returns the String
     */
    @JsonGetter("Zip")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getZip() {
        return zip;
    }

    /**
     * Setter for Zip.
     * @param zip Value for String
     */
    @JsonSetter("Zip")
    public void setZip(String zip) {
        this.zip = zip;
    }

    /**
     * Converts this AddressData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AddressData [" + "addressLine=" + addressLine + ", addressLine2=" + addressLine2
                + ", city=" + city + ", country=" + country + ", state=" + state + ", zip=" + zip
                + "]";
    }

    /**
     * Builds a new {@link AddressData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AddressData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .addressLine(getAddressLine())
                .addressLine2(getAddressLine2())
                .city(getCity())
                .country(getCountry())
                .state(getState())
                .zip(getZip());
        return builder;
    }

    /**
     * Class to build instances of {@link AddressData}.
     */
    public static class Builder {
        private String addressLine;
        private String addressLine2;
        private String city;
        private String country;
        private String state;
        private String zip;



        /**
         * Setter for addressLine.
         * @param  addressLine  String value for addressLine.
         * @return Builder
         */
        public Builder addressLine(String addressLine) {
            this.addressLine = addressLine;
            return this;
        }

        /**
         * Setter for addressLine2.
         * @param  addressLine2  String value for addressLine2.
         * @return Builder
         */
        public Builder addressLine2(String addressLine2) {
            this.addressLine2 = addressLine2;
            return this;
        }

        /**
         * Setter for city.
         * @param  city  String value for city.
         * @return Builder
         */
        public Builder city(String city) {
            this.city = city;
            return this;
        }

        /**
         * Setter for country.
         * @param  country  String value for country.
         * @return Builder
         */
        public Builder country(String country) {
            this.country = country;
            return this;
        }

        /**
         * Setter for state.
         * @param  state  String value for state.
         * @return Builder
         */
        public Builder state(String state) {
            this.state = state;
            return this;
        }

        /**
         * Setter for zip.
         * @param  zip  String value for zip.
         * @return Builder
         */
        public Builder zip(String zip) {
            this.zip = zip;
            return this;
        }

        /**
         * Builds a new {@link AddressData} object using the set fields.
         * @return {@link AddressData}
         */
        public AddressData build() {
            return new AddressData(addressLine, addressLine2, city, country, state, zip);
        }
    }
}
