/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.splitit.sandbox.webapiv3.DateTimeHelper;
import java.time.LocalDateTime;

/**
 * This is a model class for AuthorizationModel type.
 */
public class AuthorizationModel {
    private GwAuthorizationStatusEnum status;
    private LocalDateTime date;
    private String splititErrorResultCode;
    private String gatewayTransactionID;
    private String gatewayResultCode;
    private String gatewayResultMessage;
    private ThreeDsRedirectDataV3 threeDSRedirect;
    private String cAVV;
    private String eCI;
    private String gatewaySourceResponse;

    /**
     * Default constructor.
     */
    public AuthorizationModel() {
    }

    /**
     * Initialization constructor.
     * @param  status  GwAuthorizationStatusEnum value for status.
     * @param  date  LocalDateTime value for date.
     * @param  splititErrorResultCode  String value for splititErrorResultCode.
     * @param  gatewayTransactionID  String value for gatewayTransactionID.
     * @param  gatewayResultCode  String value for gatewayResultCode.
     * @param  gatewayResultMessage  String value for gatewayResultMessage.
     * @param  threeDSRedirect  ThreeDsRedirectDataV3 value for threeDSRedirect.
     * @param  cAVV  String value for cAVV.
     * @param  eCI  String value for eCI.
     * @param  gatewaySourceResponse  String value for gatewaySourceResponse.
     */
    public AuthorizationModel(
            GwAuthorizationStatusEnum status,
            LocalDateTime date,
            String splititErrorResultCode,
            String gatewayTransactionID,
            String gatewayResultCode,
            String gatewayResultMessage,
            ThreeDsRedirectDataV3 threeDSRedirect,
            String cAVV,
            String eCI,
            String gatewaySourceResponse) {
        this.status = status;
        this.date = date;
        this.splititErrorResultCode = splititErrorResultCode;
        this.gatewayTransactionID = gatewayTransactionID;
        this.gatewayResultCode = gatewayResultCode;
        this.gatewayResultMessage = gatewayResultMessage;
        this.threeDSRedirect = threeDSRedirect;
        this.cAVV = cAVV;
        this.eCI = eCI;
        this.gatewaySourceResponse = gatewaySourceResponse;
    }

    /**
     * Getter for Status.
     * @return Returns the GwAuthorizationStatusEnum
     */
    @JsonGetter("Status")
    public GwAuthorizationStatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for GwAuthorizationStatusEnum
     */
    @JsonSetter("Status")
    public void setStatus(GwAuthorizationStatusEnum status) {
        this.status = status;
    }

    /**
     * Getter for Date.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("Date")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getDate() {
        return date;
    }

    /**
     * Setter for Date.
     * @param date Value for LocalDateTime
     */
    @JsonSetter("Date")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    /**
     * Getter for SplititErrorResultCode.
     * @return Returns the String
     */
    @JsonGetter("SplititErrorResultCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSplititErrorResultCode() {
        return splititErrorResultCode;
    }

    /**
     * Setter for SplititErrorResultCode.
     * @param splititErrorResultCode Value for String
     */
    @JsonSetter("SplititErrorResultCode")
    public void setSplititErrorResultCode(String splititErrorResultCode) {
        this.splititErrorResultCode = splititErrorResultCode;
    }

    /**
     * Getter for GatewayTransactionID.
     * @return Returns the String
     */
    @JsonGetter("GatewayTransactionID")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getGatewayTransactionID() {
        return gatewayTransactionID;
    }

    /**
     * Setter for GatewayTransactionID.
     * @param gatewayTransactionID Value for String
     */
    @JsonSetter("GatewayTransactionID")
    public void setGatewayTransactionID(String gatewayTransactionID) {
        this.gatewayTransactionID = gatewayTransactionID;
    }

    /**
     * Getter for GatewayResultCode.
     * @return Returns the String
     */
    @JsonGetter("GatewayResultCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getGatewayResultCode() {
        return gatewayResultCode;
    }

    /**
     * Setter for GatewayResultCode.
     * @param gatewayResultCode Value for String
     */
    @JsonSetter("GatewayResultCode")
    public void setGatewayResultCode(String gatewayResultCode) {
        this.gatewayResultCode = gatewayResultCode;
    }

    /**
     * Getter for GatewayResultMessage.
     * @return Returns the String
     */
    @JsonGetter("GatewayResultMessage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getGatewayResultMessage() {
        return gatewayResultMessage;
    }

    /**
     * Setter for GatewayResultMessage.
     * @param gatewayResultMessage Value for String
     */
    @JsonSetter("GatewayResultMessage")
    public void setGatewayResultMessage(String gatewayResultMessage) {
        this.gatewayResultMessage = gatewayResultMessage;
    }

    /**
     * Getter for ThreeDSRedirect.
     * @return Returns the ThreeDsRedirectDataV3
     */
    @JsonGetter("ThreeDSRedirect")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ThreeDsRedirectDataV3 getThreeDSRedirect() {
        return threeDSRedirect;
    }

    /**
     * Setter for ThreeDSRedirect.
     * @param threeDSRedirect Value for ThreeDsRedirectDataV3
     */
    @JsonSetter("ThreeDSRedirect")
    public void setThreeDSRedirect(ThreeDsRedirectDataV3 threeDSRedirect) {
        this.threeDSRedirect = threeDSRedirect;
    }

    /**
     * Getter for CAVV.
     * @return Returns the String
     */
    @JsonGetter("CAVV")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCAVV() {
        return cAVV;
    }

    /**
     * Setter for CAVV.
     * @param cAVV Value for String
     */
    @JsonSetter("CAVV")
    public void setCAVV(String cAVV) {
        this.cAVV = cAVV;
    }

    /**
     * Getter for ECI.
     * @return Returns the String
     */
    @JsonGetter("ECI")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getECI() {
        return eCI;
    }

    /**
     * Setter for ECI.
     * @param eCI Value for String
     */
    @JsonSetter("ECI")
    public void setECI(String eCI) {
        this.eCI = eCI;
    }

    /**
     * Getter for GatewaySourceResponse.
     * @return Returns the String
     */
    @JsonGetter("GatewaySourceResponse")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getGatewaySourceResponse() {
        return gatewaySourceResponse;
    }

    /**
     * Setter for GatewaySourceResponse.
     * @param gatewaySourceResponse Value for String
     */
    @JsonSetter("GatewaySourceResponse")
    public void setGatewaySourceResponse(String gatewaySourceResponse) {
        this.gatewaySourceResponse = gatewaySourceResponse;
    }

    /**
     * Converts this AuthorizationModel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AuthorizationModel [" + "status=" + status + ", date=" + date
                + ", splititErrorResultCode=" + splititErrorResultCode + ", gatewayTransactionID="
                + gatewayTransactionID + ", gatewayResultCode=" + gatewayResultCode
                + ", gatewayResultMessage=" + gatewayResultMessage + ", threeDSRedirect="
                + threeDSRedirect + ", cAVV=" + cAVV + ", eCI=" + eCI + ", gatewaySourceResponse="
                + gatewaySourceResponse + "]";
    }

    /**
     * Builds a new {@link AuthorizationModel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AuthorizationModel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(status)
                .date(getDate())
                .splititErrorResultCode(getSplititErrorResultCode())
                .gatewayTransactionID(getGatewayTransactionID())
                .gatewayResultCode(getGatewayResultCode())
                .gatewayResultMessage(getGatewayResultMessage())
                .threeDSRedirect(getThreeDSRedirect())
                .cAVV(getCAVV())
                .eCI(getECI())
                .gatewaySourceResponse(getGatewaySourceResponse());
        return builder;
    }

    /**
     * Class to build instances of {@link AuthorizationModel}.
     */
    public static class Builder {
        private GwAuthorizationStatusEnum status;
        private LocalDateTime date;
        private String splititErrorResultCode;
        private String gatewayTransactionID;
        private String gatewayResultCode;
        private String gatewayResultMessage;
        private ThreeDsRedirectDataV3 threeDSRedirect;
        private String cAVV;
        private String eCI;
        private String gatewaySourceResponse;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  status  GwAuthorizationStatusEnum value for status.
         */
        public Builder(GwAuthorizationStatusEnum status) {
            this.status = status;
        }

        /**
         * Setter for status.
         * @param  status  GwAuthorizationStatusEnum value for status.
         * @return Builder
         */
        public Builder status(GwAuthorizationStatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for date.
         * @param  date  LocalDateTime value for date.
         * @return Builder
         */
        public Builder date(LocalDateTime date) {
            this.date = date;
            return this;
        }

        /**
         * Setter for splititErrorResultCode.
         * @param  splititErrorResultCode  String value for splititErrorResultCode.
         * @return Builder
         */
        public Builder splititErrorResultCode(String splititErrorResultCode) {
            this.splititErrorResultCode = splititErrorResultCode;
            return this;
        }

        /**
         * Setter for gatewayTransactionID.
         * @param  gatewayTransactionID  String value for gatewayTransactionID.
         * @return Builder
         */
        public Builder gatewayTransactionID(String gatewayTransactionID) {
            this.gatewayTransactionID = gatewayTransactionID;
            return this;
        }

        /**
         * Setter for gatewayResultCode.
         * @param  gatewayResultCode  String value for gatewayResultCode.
         * @return Builder
         */
        public Builder gatewayResultCode(String gatewayResultCode) {
            this.gatewayResultCode = gatewayResultCode;
            return this;
        }

        /**
         * Setter for gatewayResultMessage.
         * @param  gatewayResultMessage  String value for gatewayResultMessage.
         * @return Builder
         */
        public Builder gatewayResultMessage(String gatewayResultMessage) {
            this.gatewayResultMessage = gatewayResultMessage;
            return this;
        }

        /**
         * Setter for threeDSRedirect.
         * @param  threeDSRedirect  ThreeDsRedirectDataV3 value for threeDSRedirect.
         * @return Builder
         */
        public Builder threeDSRedirect(ThreeDsRedirectDataV3 threeDSRedirect) {
            this.threeDSRedirect = threeDSRedirect;
            return this;
        }

        /**
         * Setter for cAVV.
         * @param  cAVV  String value for cAVV.
         * @return Builder
         */
        public Builder cAVV(String cAVV) {
            this.cAVV = cAVV;
            return this;
        }

        /**
         * Setter for eCI.
         * @param  eCI  String value for eCI.
         * @return Builder
         */
        public Builder eCI(String eCI) {
            this.eCI = eCI;
            return this;
        }

        /**
         * Setter for gatewaySourceResponse.
         * @param  gatewaySourceResponse  String value for gatewaySourceResponse.
         * @return Builder
         */
        public Builder gatewaySourceResponse(String gatewaySourceResponse) {
            this.gatewaySourceResponse = gatewaySourceResponse;
            return this;
        }

        /**
         * Builds a new {@link AuthorizationModel} object using the set fields.
         * @return {@link AuthorizationModel}
         */
        public AuthorizationModel build() {
            return new AuthorizationModel(status, date, splititErrorResultCode,
                    gatewayTransactionID, gatewayResultCode, gatewayResultMessage, threeDSRedirect,
                    cAVV, eCI, gatewaySourceResponse);
        }
    }
}
