/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for BluesnapVaultedShopperToken type.
 */
public class BluesnapVaultedShopperToken {
    private String token;
    private String last4Digit;

    /**
     * Default constructor.
     */
    public BluesnapVaultedShopperToken() {
    }

    /**
     * Initialization constructor.
     * @param  token  String value for token.
     * @param  last4Digit  String value for last4Digit.
     */
    public BluesnapVaultedShopperToken(
            String token,
            String last4Digit) {
        this.token = token;
        this.last4Digit = last4Digit;
    }

    /**
     * Getter for Token.
     * @return Returns the String
     */
    @JsonGetter("Token")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getToken() {
        return token;
    }

    /**
     * Setter for Token.
     * @param token Value for String
     */
    @JsonSetter("Token")
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * Getter for Last4Digit.
     * @return Returns the String
     */
    @JsonGetter("Last4Digit")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLast4Digit() {
        return last4Digit;
    }

    /**
     * Setter for Last4Digit.
     * @param last4Digit Value for String
     */
    @JsonSetter("Last4Digit")
    public void setLast4Digit(String last4Digit) {
        this.last4Digit = last4Digit;
    }

    /**
     * Converts this BluesnapVaultedShopperToken into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "BluesnapVaultedShopperToken [" + "token=" + token + ", last4Digit=" + last4Digit
                + "]";
    }

    /**
     * Builds a new {@link BluesnapVaultedShopperToken.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link BluesnapVaultedShopperToken.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .token(getToken())
                .last4Digit(getLast4Digit());
        return builder;
    }

    /**
     * Class to build instances of {@link BluesnapVaultedShopperToken}.
     */
    public static class Builder {
        private String token;
        private String last4Digit;



        /**
         * Setter for token.
         * @param  token  String value for token.
         * @return Builder
         */
        public Builder token(String token) {
            this.token = token;
            return this;
        }

        /**
         * Setter for last4Digit.
         * @param  last4Digit  String value for last4Digit.
         * @return Builder
         */
        public Builder last4Digit(String last4Digit) {
            this.last4Digit = last4Digit;
            return this;
        }

        /**
         * Builds a new {@link BluesnapVaultedShopperToken} object using the set fields.
         * @return {@link BluesnapVaultedShopperToken}
         */
        public BluesnapVaultedShopperToken build() {
            return new BluesnapVaultedShopperToken(token, last4Digit);
        }
    }
}
