/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CardData type.
 */
public class CardData {
    private String cardHolderFullName;
    private String cardNumber;
    private String cardExpYear;
    private String cardExpMonth;
    private String cardCvv;
    private CardBrandEnum cardBrand;
    private CardTypeEnum cardType;

    /**
     * Default constructor.
     */
    public CardData() {
    }

    /**
     * Initialization constructor.
     * @param  cardHolderFullName  String value for cardHolderFullName.
     * @param  cardNumber  String value for cardNumber.
     * @param  cardExpYear  String value for cardExpYear.
     * @param  cardExpMonth  String value for cardExpMonth.
     * @param  cardCvv  String value for cardCvv.
     * @param  cardBrand  CardBrandEnum value for cardBrand.
     * @param  cardType  CardTypeEnum value for cardType.
     */
    public CardData(
            String cardHolderFullName,
            String cardNumber,
            String cardExpYear,
            String cardExpMonth,
            String cardCvv,
            CardBrandEnum cardBrand,
            CardTypeEnum cardType) {
        this.cardHolderFullName = cardHolderFullName;
        this.cardNumber = cardNumber;
        this.cardExpYear = cardExpYear;
        this.cardExpMonth = cardExpMonth;
        this.cardCvv = cardCvv;
        this.cardBrand = cardBrand;
        this.cardType = cardType;
    }

    /**
     * Getter for CardHolderFullName.
     * @return Returns the String
     */
    @JsonGetter("CardHolderFullName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardHolderFullName() {
        return cardHolderFullName;
    }

    /**
     * Setter for CardHolderFullName.
     * @param cardHolderFullName Value for String
     */
    @JsonSetter("CardHolderFullName")
    public void setCardHolderFullName(String cardHolderFullName) {
        this.cardHolderFullName = cardHolderFullName;
    }

    /**
     * Getter for CardNumber.
     * @return Returns the String
     */
    @JsonGetter("CardNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * Setter for CardNumber.
     * @param cardNumber Value for String
     */
    @JsonSetter("CardNumber")
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    /**
     * Getter for CardExpYear.
     * @return Returns the String
     */
    @JsonGetter("CardExpYear")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardExpYear() {
        return cardExpYear;
    }

    /**
     * Setter for CardExpYear.
     * @param cardExpYear Value for String
     */
    @JsonSetter("CardExpYear")
    public void setCardExpYear(String cardExpYear) {
        this.cardExpYear = cardExpYear;
    }

    /**
     * Getter for CardExpMonth.
     * @return Returns the String
     */
    @JsonGetter("CardExpMonth")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardExpMonth() {
        return cardExpMonth;
    }

    /**
     * Setter for CardExpMonth.
     * @param cardExpMonth Value for String
     */
    @JsonSetter("CardExpMonth")
    public void setCardExpMonth(String cardExpMonth) {
        this.cardExpMonth = cardExpMonth;
    }

    /**
     * Getter for CardCvv.
     * @return Returns the String
     */
    @JsonGetter("CardCvv")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardCvv() {
        return cardCvv;
    }

    /**
     * Setter for CardCvv.
     * @param cardCvv Value for String
     */
    @JsonSetter("CardCvv")
    public void setCardCvv(String cardCvv) {
        this.cardCvv = cardCvv;
    }

    /**
     * Getter for CardBrand.
     * @return Returns the CardBrandEnum
     */
    @JsonGetter("CardBrand")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardBrandEnum getCardBrand() {
        return cardBrand;
    }

    /**
     * Setter for CardBrand.
     * @param cardBrand Value for CardBrandEnum
     */
    @JsonSetter("CardBrand")
    public void setCardBrand(CardBrandEnum cardBrand) {
        this.cardBrand = cardBrand;
    }

    /**
     * Getter for CardType.
     * @return Returns the CardTypeEnum
     */
    @JsonGetter("CardType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardTypeEnum getCardType() {
        return cardType;
    }

    /**
     * Setter for CardType.
     * @param cardType Value for CardTypeEnum
     */
    @JsonSetter("CardType")
    public void setCardType(CardTypeEnum cardType) {
        this.cardType = cardType;
    }

    /**
     * Converts this CardData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CardData [" + "cardHolderFullName=" + cardHolderFullName + ", cardNumber="
                + cardNumber + ", cardExpYear=" + cardExpYear + ", cardExpMonth=" + cardExpMonth
                + ", cardCvv=" + cardCvv + ", cardBrand=" + cardBrand + ", cardType=" + cardType
                + "]";
    }

    /**
     * Builds a new {@link CardData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CardData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .cardHolderFullName(getCardHolderFullName())
                .cardNumber(getCardNumber())
                .cardExpYear(getCardExpYear())
                .cardExpMonth(getCardExpMonth())
                .cardCvv(getCardCvv())
                .cardBrand(getCardBrand())
                .cardType(getCardType());
        return builder;
    }

    /**
     * Class to build instances of {@link CardData}.
     */
    public static class Builder {
        private String cardHolderFullName;
        private String cardNumber;
        private String cardExpYear;
        private String cardExpMonth;
        private String cardCvv;
        private CardBrandEnum cardBrand;
        private CardTypeEnum cardType;



        /**
         * Setter for cardHolderFullName.
         * @param  cardHolderFullName  String value for cardHolderFullName.
         * @return Builder
         */
        public Builder cardHolderFullName(String cardHolderFullName) {
            this.cardHolderFullName = cardHolderFullName;
            return this;
        }

        /**
         * Setter for cardNumber.
         * @param  cardNumber  String value for cardNumber.
         * @return Builder
         */
        public Builder cardNumber(String cardNumber) {
            this.cardNumber = cardNumber;
            return this;
        }

        /**
         * Setter for cardExpYear.
         * @param  cardExpYear  String value for cardExpYear.
         * @return Builder
         */
        public Builder cardExpYear(String cardExpYear) {
            this.cardExpYear = cardExpYear;
            return this;
        }

        /**
         * Setter for cardExpMonth.
         * @param  cardExpMonth  String value for cardExpMonth.
         * @return Builder
         */
        public Builder cardExpMonth(String cardExpMonth) {
            this.cardExpMonth = cardExpMonth;
            return this;
        }

        /**
         * Setter for cardCvv.
         * @param  cardCvv  String value for cardCvv.
         * @return Builder
         */
        public Builder cardCvv(String cardCvv) {
            this.cardCvv = cardCvv;
            return this;
        }

        /**
         * Setter for cardBrand.
         * @param  cardBrand  CardBrandEnum value for cardBrand.
         * @return Builder
         */
        public Builder cardBrand(CardBrandEnum cardBrand) {
            this.cardBrand = cardBrand;
            return this;
        }

        /**
         * Setter for cardType.
         * @param  cardType  CardTypeEnum value for cardType.
         * @return Builder
         */
        public Builder cardType(CardTypeEnum cardType) {
            this.cardType = cardType;
            return this;
        }

        /**
         * Builds a new {@link CardData} object using the set fields.
         * @return {@link CardData}
         */
        public CardData build() {
            return new CardData(cardHolderFullName, cardNumber, cardExpYear, cardExpMonth, cardCvv,
                    cardBrand, cardType);
        }
    }
}
