/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CheckInstallmentsEligibilityRequest type.
 */
public class CheckInstallmentsEligibilityRequest {
    private PlanData planData;
    private CardData cardDetails;
    private AddressData billingAddress;
    private String shopperIdentifier;

    /**
     * Default constructor.
     */
    public CheckInstallmentsEligibilityRequest() {
    }

    /**
     * Initialization constructor.
     * @param  planData  PlanData value for planData.
     * @param  cardDetails  CardData value for cardDetails.
     * @param  billingAddress  AddressData value for billingAddress.
     * @param  shopperIdentifier  String value for shopperIdentifier.
     */
    public CheckInstallmentsEligibilityRequest(
            PlanData planData,
            CardData cardDetails,
            AddressData billingAddress,
            String shopperIdentifier) {
        this.planData = planData;
        this.cardDetails = cardDetails;
        this.billingAddress = billingAddress;
        this.shopperIdentifier = shopperIdentifier;
    }

    /**
     * Getter for PlanData.
     * @return Returns the PlanData
     */
    @JsonGetter("PlanData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PlanData getPlanData() {
        return planData;
    }

    /**
     * Setter for PlanData.
     * @param planData Value for PlanData
     */
    @JsonSetter("PlanData")
    public void setPlanData(PlanData planData) {
        this.planData = planData;
    }

    /**
     * Getter for CardDetails.
     * @return Returns the CardData
     */
    @JsonGetter("CardDetails")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardData getCardDetails() {
        return cardDetails;
    }

    /**
     * Setter for CardDetails.
     * @param cardDetails Value for CardData
     */
    @JsonSetter("CardDetails")
    public void setCardDetails(CardData cardDetails) {
        this.cardDetails = cardDetails;
    }

    /**
     * Getter for BillingAddress.
     * @return Returns the AddressData
     */
    @JsonGetter("BillingAddress")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AddressData getBillingAddress() {
        return billingAddress;
    }

    /**
     * Setter for BillingAddress.
     * @param billingAddress Value for AddressData
     */
    @JsonSetter("BillingAddress")
    public void setBillingAddress(AddressData billingAddress) {
        this.billingAddress = billingAddress;
    }

    /**
     * Getter for ShopperIdentifier.
     * @return Returns the String
     */
    @JsonGetter("ShopperIdentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getShopperIdentifier() {
        return shopperIdentifier;
    }

    /**
     * Setter for ShopperIdentifier.
     * @param shopperIdentifier Value for String
     */
    @JsonSetter("ShopperIdentifier")
    public void setShopperIdentifier(String shopperIdentifier) {
        this.shopperIdentifier = shopperIdentifier;
    }

    /**
     * Converts this CheckInstallmentsEligibilityRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CheckInstallmentsEligibilityRequest [" + "planData=" + planData + ", cardDetails="
                + cardDetails + ", billingAddress=" + billingAddress + ", shopperIdentifier="
                + shopperIdentifier + "]";
    }

    /**
     * Builds a new {@link CheckInstallmentsEligibilityRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CheckInstallmentsEligibilityRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .planData(getPlanData())
                .cardDetails(getCardDetails())
                .billingAddress(getBillingAddress())
                .shopperIdentifier(getShopperIdentifier());
        return builder;
    }

    /**
     * Class to build instances of {@link CheckInstallmentsEligibilityRequest}.
     */
    public static class Builder {
        private PlanData planData;
        private CardData cardDetails;
        private AddressData billingAddress;
        private String shopperIdentifier;



        /**
         * Setter for planData.
         * @param  planData  PlanData value for planData.
         * @return Builder
         */
        public Builder planData(PlanData planData) {
            this.planData = planData;
            return this;
        }

        /**
         * Setter for cardDetails.
         * @param  cardDetails  CardData value for cardDetails.
         * @return Builder
         */
        public Builder cardDetails(CardData cardDetails) {
            this.cardDetails = cardDetails;
            return this;
        }

        /**
         * Setter for billingAddress.
         * @param  billingAddress  AddressData value for billingAddress.
         * @return Builder
         */
        public Builder billingAddress(AddressData billingAddress) {
            this.billingAddress = billingAddress;
            return this;
        }

        /**
         * Setter for shopperIdentifier.
         * @param  shopperIdentifier  String value for shopperIdentifier.
         * @return Builder
         */
        public Builder shopperIdentifier(String shopperIdentifier) {
            this.shopperIdentifier = shopperIdentifier;
            return this;
        }

        /**
         * Builds a new {@link CheckInstallmentsEligibilityRequest} object using the set fields.
         * @return {@link CheckInstallmentsEligibilityRequest}
         */
        public CheckInstallmentsEligibilityRequest build() {
            return new CheckInstallmentsEligibilityRequest(planData, cardDetails, billingAddress,
                    shopperIdentifier);
        }
    }
}
