/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for EligibilityTermsAndConditionResponse type.
 */
public class EligibilityTermsAndConditionResponse {
    private String termsAndConditions;
    private String privacyPolicy;
    private String provider;

    /**
     * Default constructor.
     */
    public EligibilityTermsAndConditionResponse() {
    }

    /**
     * Initialization constructor.
     * @param  termsAndConditions  String value for termsAndConditions.
     * @param  privacyPolicy  String value for privacyPolicy.
     * @param  provider  String value for provider.
     */
    public EligibilityTermsAndConditionResponse(
            String termsAndConditions,
            String privacyPolicy,
            String provider) {
        this.termsAndConditions = termsAndConditions;
        this.privacyPolicy = privacyPolicy;
        this.provider = provider;
    }

    /**
     * Getter for TermsAndConditions.
     * @return Returns the String
     */
    @JsonGetter("TermsAndConditions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTermsAndConditions() {
        return termsAndConditions;
    }

    /**
     * Setter for TermsAndConditions.
     * @param termsAndConditions Value for String
     */
    @JsonSetter("TermsAndConditions")
    public void setTermsAndConditions(String termsAndConditions) {
        this.termsAndConditions = termsAndConditions;
    }

    /**
     * Getter for PrivacyPolicy.
     * @return Returns the String
     */
    @JsonGetter("PrivacyPolicy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPrivacyPolicy() {
        return privacyPolicy;
    }

    /**
     * Setter for PrivacyPolicy.
     * @param privacyPolicy Value for String
     */
    @JsonSetter("PrivacyPolicy")
    public void setPrivacyPolicy(String privacyPolicy) {
        this.privacyPolicy = privacyPolicy;
    }

    /**
     * Getter for Provider.
     * @return Returns the String
     */
    @JsonGetter("Provider")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getProvider() {
        return provider;
    }

    /**
     * Setter for Provider.
     * @param provider Value for String
     */
    @JsonSetter("Provider")
    public void setProvider(String provider) {
        this.provider = provider;
    }

    /**
     * Converts this EligibilityTermsAndConditionResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EligibilityTermsAndConditionResponse [" + "termsAndConditions=" + termsAndConditions
                + ", privacyPolicy=" + privacyPolicy + ", provider=" + provider + "]";
    }

    /**
     * Builds a new {@link EligibilityTermsAndConditionResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EligibilityTermsAndConditionResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .termsAndConditions(getTermsAndConditions())
                .privacyPolicy(getPrivacyPolicy())
                .provider(getProvider());
        return builder;
    }

    /**
     * Class to build instances of {@link EligibilityTermsAndConditionResponse}.
     */
    public static class Builder {
        private String termsAndConditions;
        private String privacyPolicy;
        private String provider;



        /**
         * Setter for termsAndConditions.
         * @param  termsAndConditions  String value for termsAndConditions.
         * @return Builder
         */
        public Builder termsAndConditions(String termsAndConditions) {
            this.termsAndConditions = termsAndConditions;
            return this;
        }

        /**
         * Setter for privacyPolicy.
         * @param  privacyPolicy  String value for privacyPolicy.
         * @return Builder
         */
        public Builder privacyPolicy(String privacyPolicy) {
            this.privacyPolicy = privacyPolicy;
            return this;
        }

        /**
         * Setter for provider.
         * @param  provider  String value for provider.
         * @return Builder
         */
        public Builder provider(String provider) {
            this.provider = provider;
            return this;
        }

        /**
         * Builds a new {@link EligibilityTermsAndConditionResponse} object using the set fields.
         * @return {@link EligibilityTermsAndConditionResponse}
         */
        public EligibilityTermsAndConditionResponse build() {
            return new EligibilityTermsAndConditionResponse(termsAndConditions, privacyPolicy,
                    provider);
        }
    }
}
