/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.Map;

/**
 * This is a model class for ErrorExtended type.
 */
public class ErrorExtended {
    private String code;
    private String message;
    private String additionalInfo;
    private Map<String, String> extraData;

    /**
     * Default constructor.
     */
    public ErrorExtended() {
    }

    /**
     * Initialization constructor.
     * @param  code  String value for code.
     * @param  message  String value for message.
     * @param  additionalInfo  String value for additionalInfo.
     * @param  extraData  Map of String, value for extraData.
     */
    public ErrorExtended(
            String code,
            String message,
            String additionalInfo,
            Map<String, String> extraData) {
        this.code = code;
        this.message = message;
        this.additionalInfo = additionalInfo;
        this.extraData = extraData;
    }

    /**
     * Getter for Code.
     * @return Returns the String
     */
    @JsonGetter("Code")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCode() {
        return code;
    }

    /**
     * Setter for Code.
     * @param code Value for String
     */
    @JsonSetter("Code")
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * Getter for Message.
     * @return Returns the String
     */
    @JsonGetter("Message")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * @param message Value for String
     */
    @JsonSetter("Message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Getter for AdditionalInfo.
     * @return Returns the String
     */
    @JsonGetter("AdditionalInfo")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAdditionalInfo() {
        return additionalInfo;
    }

    /**
     * Setter for AdditionalInfo.
     * @param additionalInfo Value for String
     */
    @JsonSetter("AdditionalInfo")
    public void setAdditionalInfo(String additionalInfo) {
        this.additionalInfo = additionalInfo;
    }

    /**
     * Getter for ExtraData.
     * @return Returns the Map of String, String
     */
    @JsonGetter("ExtraData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, String> getExtraData() {
        return extraData;
    }

    /**
     * Setter for ExtraData.
     * @param extraData Value for Map of String, String
     */
    @JsonSetter("ExtraData")
    public void setExtraData(Map<String, String> extraData) {
        this.extraData = extraData;
    }

    /**
     * Converts this ErrorExtended into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ErrorExtended [" + "code=" + code + ", message=" + message + ", additionalInfo="
                + additionalInfo + ", extraData=" + extraData + "]";
    }

    /**
     * Builds a new {@link ErrorExtended.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ErrorExtended.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .code(getCode())
                .message(getMessage())
                .additionalInfo(getAdditionalInfo())
                .extraData(getExtraData());
        return builder;
    }

    /**
     * Class to build instances of {@link ErrorExtended}.
     */
    public static class Builder {
        private String code;
        private String message;
        private String additionalInfo;
        private Map<String, String> extraData;



        /**
         * Setter for code.
         * @param  code  String value for code.
         * @return Builder
         */
        public Builder code(String code) {
            this.code = code;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for additionalInfo.
         * @param  additionalInfo  String value for additionalInfo.
         * @return Builder
         */
        public Builder additionalInfo(String additionalInfo) {
            this.additionalInfo = additionalInfo;
            return this;
        }

        /**
         * Setter for extraData.
         * @param  extraData  Map of String, value for extraData.
         * @return Builder
         */
        public Builder extraData(Map<String, String> extraData) {
            this.extraData = extraData;
            return this;
        }

        /**
         * Builds a new {@link ErrorExtended} object using the set fields.
         * @return {@link ErrorExtended}
         */
        public ErrorExtended build() {
            return new ErrorExtended(code, message, additionalInfo, extraData);
        }
    }
}
