/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for EventsEndpointsModel type.
 */
public class EventsEndpointsModel {
    private String createSucceeded;

    /**
     * Default constructor.
     */
    public EventsEndpointsModel() {
    }

    /**
     * Initialization constructor.
     * @param  createSucceeded  String value for createSucceeded.
     */
    public EventsEndpointsModel(
            String createSucceeded) {
        this.createSucceeded = createSucceeded;
    }

    /**
     * Getter for CreateSucceeded.
     * @return Returns the String
     */
    @JsonGetter("CreateSucceeded")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCreateSucceeded() {
        return createSucceeded;
    }

    /**
     * Setter for CreateSucceeded.
     * @param createSucceeded Value for String
     */
    @JsonSetter("CreateSucceeded")
    public void setCreateSucceeded(String createSucceeded) {
        this.createSucceeded = createSucceeded;
    }

    /**
     * Converts this EventsEndpointsModel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EventsEndpointsModel [" + "createSucceeded=" + createSucceeded + "]";
    }

    /**
     * Builds a new {@link EventsEndpointsModel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EventsEndpointsModel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .createSucceeded(getCreateSucceeded());
        return builder;
    }

    /**
     * Class to build instances of {@link EventsEndpointsModel}.
     */
    public static class Builder {
        private String createSucceeded;



        /**
         * Setter for createSucceeded.
         * @param  createSucceeded  String value for createSucceeded.
         * @return Builder
         */
        public Builder createSucceeded(String createSucceeded) {
            this.createSucceeded = createSucceeded;
            return this;
        }

        /**
         * Builds a new {@link EventsEndpointsModel} object using the set fields.
         * @return {@link EventsEndpointsModel}
         */
        public EventsEndpointsModel build() {
            return new EventsEndpointsModel(createSucceeded);
        }
    }
}
