/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * GwAuthorizationStatusEnum to be used.
 */
public enum GwAuthorizationStatusEnum {
    NA,

    SUCCEEDED,

    PENDING3DS,

    FAILED,

    CANCELED,

    VOIDED;


    private static TreeMap<String, GwAuthorizationStatusEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        NA.value = "NA";
        SUCCEEDED.value = "Succeeded";
        PENDING3DS.value = "Pending3DS";
        FAILED.value = "Failed";
        CANCELED.value = "Canceled";
        VOIDED.value = "Voided";

        valueMap.put("NA", NA);
        valueMap.put("Succeeded", SUCCEEDED);
        valueMap.put("Pending3DS", PENDING3DS);
        valueMap.put("Failed", FAILED);
        valueMap.put("Canceled", CANCELED);
        valueMap.put("Voided", VOIDED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static GwAuthorizationStatusEnum constructFromString(String toConvert) throws IOException {
        GwAuthorizationStatusEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static GwAuthorizationStatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of GwAuthorizationStatusEnum values to list of string values.
     * @param toConvert The list of GwAuthorizationStatusEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<GwAuthorizationStatusEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (GwAuthorizationStatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 