/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.Map;

/**
 * This is a model class for IdentifierContract type.
 */
public class IdentifierContract {
    private String refOrderNumber;
    private String installmentPlanNumber;
    private Map<String, String> extendedParams;

    /**
     * Default constructor.
     */
    public IdentifierContract() {
    }

    /**
     * Initialization constructor.
     * @param  refOrderNumber  String value for refOrderNumber.
     * @param  installmentPlanNumber  String value for installmentPlanNumber.
     * @param  extendedParams  Map of String, value for extendedParams.
     */
    public IdentifierContract(
            String refOrderNumber,
            String installmentPlanNumber,
            Map<String, String> extendedParams) {
        this.refOrderNumber = refOrderNumber;
        this.installmentPlanNumber = installmentPlanNumber;
        this.extendedParams = extendedParams;
    }

    /**
     * Getter for RefOrderNumber.
     * @return Returns the String
     */
    @JsonGetter("RefOrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRefOrderNumber() {
        return refOrderNumber;
    }

    /**
     * Setter for RefOrderNumber.
     * @param refOrderNumber Value for String
     */
    @JsonSetter("RefOrderNumber")
    public void setRefOrderNumber(String refOrderNumber) {
        this.refOrderNumber = refOrderNumber;
    }

    /**
     * Getter for InstallmentPlanNumber.
     * @return Returns the String
     */
    @JsonGetter("InstallmentPlanNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getInstallmentPlanNumber() {
        return installmentPlanNumber;
    }

    /**
     * Setter for InstallmentPlanNumber.
     * @param installmentPlanNumber Value for String
     */
    @JsonSetter("InstallmentPlanNumber")
    public void setInstallmentPlanNumber(String installmentPlanNumber) {
        this.installmentPlanNumber = installmentPlanNumber;
    }

    /**
     * Getter for ExtendedParams.
     * @return Returns the Map of String, String
     */
    @JsonGetter("ExtendedParams")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, String> getExtendedParams() {
        return extendedParams;
    }

    /**
     * Setter for ExtendedParams.
     * @param extendedParams Value for Map of String, String
     */
    @JsonSetter("ExtendedParams")
    public void setExtendedParams(Map<String, String> extendedParams) {
        this.extendedParams = extendedParams;
    }

    /**
     * Converts this IdentifierContract into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "IdentifierContract [" + "refOrderNumber=" + refOrderNumber
                + ", installmentPlanNumber=" + installmentPlanNumber + ", extendedParams="
                + extendedParams + "]";
    }

    /**
     * Builds a new {@link IdentifierContract.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link IdentifierContract.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .refOrderNumber(getRefOrderNumber())
                .installmentPlanNumber(getInstallmentPlanNumber())
                .extendedParams(getExtendedParams());
        return builder;
    }

    /**
     * Class to build instances of {@link IdentifierContract}.
     */
    public static class Builder {
        private String refOrderNumber;
        private String installmentPlanNumber;
        private Map<String, String> extendedParams;



        /**
         * Setter for refOrderNumber.
         * @param  refOrderNumber  String value for refOrderNumber.
         * @return Builder
         */
        public Builder refOrderNumber(String refOrderNumber) {
            this.refOrderNumber = refOrderNumber;
            return this;
        }

        /**
         * Setter for installmentPlanNumber.
         * @param  installmentPlanNumber  String value for installmentPlanNumber.
         * @return Builder
         */
        public Builder installmentPlanNumber(String installmentPlanNumber) {
            this.installmentPlanNumber = installmentPlanNumber;
            return this;
        }

        /**
         * Setter for extendedParams.
         * @param  extendedParams  Map of String, value for extendedParams.
         * @return Builder
         */
        public Builder extendedParams(Map<String, String> extendedParams) {
            this.extendedParams = extendedParams;
            return this;
        }

        /**
         * Builds a new {@link IdentifierContract} object using the set fields.
         * @return {@link IdentifierContract}
         */
        public IdentifierContract build() {
            return new IdentifierContract(refOrderNumber, installmentPlanNumber, extendedParams);
        }
    }
}
