/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.Map;

/**
 * This is a model class for InitiatePlanResponse type.
 */
public class InitiatePlanResponse {
    private String installmentPlanNumber;
    private String refOrderNumber;
    private PurchaseMethodEnum purchaseMethod;
    private PlanStatusEnum status;
    private String currency;
    private Double amount;
    private Map<String, String> extendedParams;
    private ShopperData shopper;
    private AddressData billingAddress;
    private String checkoutUrl;
    private Double principalAmount;

    /**
     * Default constructor.
     */
    public InitiatePlanResponse() {
    }

    /**
     * Initialization constructor.
     * @param  status  PlanStatusEnum value for status.
     * @param  installmentPlanNumber  String value for installmentPlanNumber.
     * @param  refOrderNumber  String value for refOrderNumber.
     * @param  purchaseMethod  PurchaseMethodEnum value for purchaseMethod.
     * @param  currency  String value for currency.
     * @param  amount  Double value for amount.
     * @param  extendedParams  Map of String, value for extendedParams.
     * @param  shopper  ShopperData value for shopper.
     * @param  billingAddress  AddressData value for billingAddress.
     * @param  checkoutUrl  String value for checkoutUrl.
     * @param  principalAmount  Double value for principalAmount.
     */
    public InitiatePlanResponse(
            PlanStatusEnum status,
            String installmentPlanNumber,
            String refOrderNumber,
            PurchaseMethodEnum purchaseMethod,
            String currency,
            Double amount,
            Map<String, String> extendedParams,
            ShopperData shopper,
            AddressData billingAddress,
            String checkoutUrl,
            Double principalAmount) {
        this.installmentPlanNumber = installmentPlanNumber;
        this.refOrderNumber = refOrderNumber;
        this.purchaseMethod = purchaseMethod;
        this.status = status;
        this.currency = currency;
        this.amount = amount;
        this.extendedParams = extendedParams;
        this.shopper = shopper;
        this.billingAddress = billingAddress;
        this.checkoutUrl = checkoutUrl;
        this.principalAmount = principalAmount;
    }

    /**
     * Getter for InstallmentPlanNumber.
     * @return Returns the String
     */
    @JsonGetter("InstallmentPlanNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getInstallmentPlanNumber() {
        return installmentPlanNumber;
    }

    /**
     * Setter for InstallmentPlanNumber.
     * @param installmentPlanNumber Value for String
     */
    @JsonSetter("InstallmentPlanNumber")
    public void setInstallmentPlanNumber(String installmentPlanNumber) {
        this.installmentPlanNumber = installmentPlanNumber;
    }

    /**
     * Getter for RefOrderNumber.
     * @return Returns the String
     */
    @JsonGetter("RefOrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRefOrderNumber() {
        return refOrderNumber;
    }

    /**
     * Setter for RefOrderNumber.
     * @param refOrderNumber Value for String
     */
    @JsonSetter("RefOrderNumber")
    public void setRefOrderNumber(String refOrderNumber) {
        this.refOrderNumber = refOrderNumber;
    }

    /**
     * Getter for PurchaseMethod.
     * @return Returns the PurchaseMethodEnum
     */
    @JsonGetter("PurchaseMethod")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PurchaseMethodEnum getPurchaseMethod() {
        return purchaseMethod;
    }

    /**
     * Setter for PurchaseMethod.
     * @param purchaseMethod Value for PurchaseMethodEnum
     */
    @JsonSetter("PurchaseMethod")
    public void setPurchaseMethod(PurchaseMethodEnum purchaseMethod) {
        this.purchaseMethod = purchaseMethod;
    }

    /**
     * Getter for Status.
     * @return Returns the PlanStatusEnum
     */
    @JsonGetter("Status")
    public PlanStatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for PlanStatusEnum
     */
    @JsonSetter("Status")
    public void setStatus(PlanStatusEnum status) {
        this.status = status;
    }

    /**
     * Getter for Currency.
     * @return Returns the String
     */
    @JsonGetter("Currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCurrency() {
        return currency;
    }

    /**
     * Setter for Currency.
     * @param currency Value for String
     */
    @JsonSetter("Currency")
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Getter for Amount.
     * @return Returns the Double
     */
    @JsonGetter("Amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getAmount() {
        return amount;
    }

    /**
     * Setter for Amount.
     * @param amount Value for Double
     */
    @JsonSetter("Amount")
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * Getter for ExtendedParams.
     * @return Returns the Map of String, String
     */
    @JsonGetter("ExtendedParams")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, String> getExtendedParams() {
        return extendedParams;
    }

    /**
     * Setter for ExtendedParams.
     * @param extendedParams Value for Map of String, String
     */
    @JsonSetter("ExtendedParams")
    public void setExtendedParams(Map<String, String> extendedParams) {
        this.extendedParams = extendedParams;
    }

    /**
     * Getter for Shopper.
     * @return Returns the ShopperData
     */
    @JsonGetter("Shopper")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShopperData getShopper() {
        return shopper;
    }

    /**
     * Setter for Shopper.
     * @param shopper Value for ShopperData
     */
    @JsonSetter("Shopper")
    public void setShopper(ShopperData shopper) {
        this.shopper = shopper;
    }

    /**
     * Getter for BillingAddress.
     * @return Returns the AddressData
     */
    @JsonGetter("BillingAddress")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AddressData getBillingAddress() {
        return billingAddress;
    }

    /**
     * Setter for BillingAddress.
     * @param billingAddress Value for AddressData
     */
    @JsonSetter("BillingAddress")
    public void setBillingAddress(AddressData billingAddress) {
        this.billingAddress = billingAddress;
    }

    /**
     * Getter for CheckoutUrl.
     * @return Returns the String
     */
    @JsonGetter("CheckoutUrl")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCheckoutUrl() {
        return checkoutUrl;
    }

    /**
     * Setter for CheckoutUrl.
     * @param checkoutUrl Value for String
     */
    @JsonSetter("CheckoutUrl")
    public void setCheckoutUrl(String checkoutUrl) {
        this.checkoutUrl = checkoutUrl;
    }

    /**
     * Getter for PrincipalAmount.
     * @return Returns the Double
     */
    @JsonGetter("PrincipalAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPrincipalAmount() {
        return principalAmount;
    }

    /**
     * Setter for PrincipalAmount.
     * @param principalAmount Value for Double
     */
    @JsonSetter("PrincipalAmount")
    public void setPrincipalAmount(Double principalAmount) {
        this.principalAmount = principalAmount;
    }

    /**
     * Converts this InitiatePlanResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InitiatePlanResponse [" + "status=" + status + ", installmentPlanNumber="
                + installmentPlanNumber + ", refOrderNumber=" + refOrderNumber + ", purchaseMethod="
                + purchaseMethod + ", currency=" + currency + ", amount=" + amount
                + ", extendedParams=" + extendedParams + ", shopper=" + shopper
                + ", billingAddress=" + billingAddress + ", checkoutUrl=" + checkoutUrl
                + ", principalAmount=" + principalAmount + "]";
    }

    /**
     * Builds a new {@link InitiatePlanResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InitiatePlanResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(status)
                .installmentPlanNumber(getInstallmentPlanNumber())
                .refOrderNumber(getRefOrderNumber())
                .purchaseMethod(getPurchaseMethod())
                .currency(getCurrency())
                .amount(getAmount())
                .extendedParams(getExtendedParams())
                .shopper(getShopper())
                .billingAddress(getBillingAddress())
                .checkoutUrl(getCheckoutUrl())
                .principalAmount(getPrincipalAmount());
        return builder;
    }

    /**
     * Class to build instances of {@link InitiatePlanResponse}.
     */
    public static class Builder {
        private PlanStatusEnum status;
        private String installmentPlanNumber;
        private String refOrderNumber;
        private PurchaseMethodEnum purchaseMethod;
        private String currency;
        private Double amount;
        private Map<String, String> extendedParams;
        private ShopperData shopper;
        private AddressData billingAddress;
        private String checkoutUrl;
        private Double principalAmount;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  status  PlanStatusEnum value for status.
         */
        public Builder(PlanStatusEnum status) {
            this.status = status;
        }

        /**
         * Setter for status.
         * @param  status  PlanStatusEnum value for status.
         * @return Builder
         */
        public Builder status(PlanStatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for installmentPlanNumber.
         * @param  installmentPlanNumber  String value for installmentPlanNumber.
         * @return Builder
         */
        public Builder installmentPlanNumber(String installmentPlanNumber) {
            this.installmentPlanNumber = installmentPlanNumber;
            return this;
        }

        /**
         * Setter for refOrderNumber.
         * @param  refOrderNumber  String value for refOrderNumber.
         * @return Builder
         */
        public Builder refOrderNumber(String refOrderNumber) {
            this.refOrderNumber = refOrderNumber;
            return this;
        }

        /**
         * Setter for purchaseMethod.
         * @param  purchaseMethod  PurchaseMethodEnum value for purchaseMethod.
         * @return Builder
         */
        public Builder purchaseMethod(PurchaseMethodEnum purchaseMethod) {
            this.purchaseMethod = purchaseMethod;
            return this;
        }

        /**
         * Setter for currency.
         * @param  currency  String value for currency.
         * @return Builder
         */
        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * Setter for amount.
         * @param  amount  Double value for amount.
         * @return Builder
         */
        public Builder amount(Double amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Setter for extendedParams.
         * @param  extendedParams  Map of String, value for extendedParams.
         * @return Builder
         */
        public Builder extendedParams(Map<String, String> extendedParams) {
            this.extendedParams = extendedParams;
            return this;
        }

        /**
         * Setter for shopper.
         * @param  shopper  ShopperData value for shopper.
         * @return Builder
         */
        public Builder shopper(ShopperData shopper) {
            this.shopper = shopper;
            return this;
        }

        /**
         * Setter for billingAddress.
         * @param  billingAddress  AddressData value for billingAddress.
         * @return Builder
         */
        public Builder billingAddress(AddressData billingAddress) {
            this.billingAddress = billingAddress;
            return this;
        }

        /**
         * Setter for checkoutUrl.
         * @param  checkoutUrl  String value for checkoutUrl.
         * @return Builder
         */
        public Builder checkoutUrl(String checkoutUrl) {
            this.checkoutUrl = checkoutUrl;
            return this;
        }

        /**
         * Setter for principalAmount.
         * @param  principalAmount  Double value for principalAmount.
         * @return Builder
         */
        public Builder principalAmount(Double principalAmount) {
            this.principalAmount = principalAmount;
            return this;
        }

        /**
         * Builds a new {@link InitiatePlanResponse} object using the set fields.
         * @return {@link InitiatePlanResponse}
         */
        public InitiatePlanResponse build() {
            return new InitiatePlanResponse(status, installmentPlanNumber, refOrderNumber,
                    purchaseMethod, currency, amount, extendedParams, shopper, billingAddress,
                    checkoutUrl, principalAmount);
        }
    }
}
