/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InitiateRedirectionEndpointsModel type.
 */
public class InitiateRedirectionEndpointsModel {
    private String succeeded;
    private String failed;
    private String cancel;

    /**
     * Default constructor.
     */
    public InitiateRedirectionEndpointsModel() {
    }

    /**
     * Initialization constructor.
     * @param  succeeded  String value for succeeded.
     * @param  failed  String value for failed.
     * @param  cancel  String value for cancel.
     */
    public InitiateRedirectionEndpointsModel(
            String succeeded,
            String failed,
            String cancel) {
        this.succeeded = succeeded;
        this.failed = failed;
        this.cancel = cancel;
    }

    /**
     * Getter for Succeeded.
     * @return Returns the String
     */
    @JsonGetter("Succeeded")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSucceeded() {
        return succeeded;
    }

    /**
     * Setter for Succeeded.
     * @param succeeded Value for String
     */
    @JsonSetter("Succeeded")
    public void setSucceeded(String succeeded) {
        this.succeeded = succeeded;
    }

    /**
     * Getter for Failed.
     * @return Returns the String
     */
    @JsonGetter("Failed")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFailed() {
        return failed;
    }

    /**
     * Setter for Failed.
     * @param failed Value for String
     */
    @JsonSetter("Failed")
    public void setFailed(String failed) {
        this.failed = failed;
    }

    /**
     * Getter for Cancel.
     * @return Returns the String
     */
    @JsonGetter("Cancel")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCancel() {
        return cancel;
    }

    /**
     * Setter for Cancel.
     * @param cancel Value for String
     */
    @JsonSetter("Cancel")
    public void setCancel(String cancel) {
        this.cancel = cancel;
    }

    /**
     * Converts this InitiateRedirectionEndpointsModel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InitiateRedirectionEndpointsModel [" + "succeeded=" + succeeded + ", failed="
                + failed + ", cancel=" + cancel + "]";
    }

    /**
     * Builds a new {@link InitiateRedirectionEndpointsModel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InitiateRedirectionEndpointsModel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .succeeded(getSucceeded())
                .failed(getFailed())
                .cancel(getCancel());
        return builder;
    }

    /**
     * Class to build instances of {@link InitiateRedirectionEndpointsModel}.
     */
    public static class Builder {
        private String succeeded;
        private String failed;
        private String cancel;



        /**
         * Setter for succeeded.
         * @param  succeeded  String value for succeeded.
         * @return Builder
         */
        public Builder succeeded(String succeeded) {
            this.succeeded = succeeded;
            return this;
        }

        /**
         * Setter for failed.
         * @param  failed  String value for failed.
         * @return Builder
         */
        public Builder failed(String failed) {
            this.failed = failed;
            return this;
        }

        /**
         * Setter for cancel.
         * @param  cancel  String value for cancel.
         * @return Builder
         */
        public Builder cancel(String cancel) {
            this.cancel = cancel;
            return this;
        }

        /**
         * Builds a new {@link InitiateRedirectionEndpointsModel} object using the set fields.
         * @return {@link InitiateRedirectionEndpointsModel}
         */
        public InitiateRedirectionEndpointsModel build() {
            return new InitiateRedirectionEndpointsModel(succeeded, failed, cancel);
        }
    }
}
