/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * InstallmentStatusEnum to be used.
 */
public enum InstallmentStatusEnum {
    PENDING,

    PROCESSED,

    CANCELED;


    private static TreeMap<String, InstallmentStatusEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        PENDING.value = "Pending";
        PROCESSED.value = "Processed";
        CANCELED.value = "Canceled";

        valueMap.put("Pending", PENDING);
        valueMap.put("Processed", PROCESSED);
        valueMap.put("Canceled", CANCELED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static InstallmentStatusEnum constructFromString(String toConvert) throws IOException {
        InstallmentStatusEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static InstallmentStatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of InstallmentStatusEnum values to list of string values.
     * @param toConvert The list of InstallmentStatusEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<InstallmentStatusEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (InstallmentStatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 