/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.splitit.sandbox.webapiv3.DateTimeHelper;
import java.time.LocalDateTime;

/**
 * This is a model class for Installment type.
 */
public class Installment {
    private int installmentNumber;
    private double amount;
    private LocalDateTime processDateTime;
    private InstallmentStatusEnum status;

    /**
     * Default constructor.
     */
    public Installment() {
    }

    /**
     * Initialization constructor.
     * @param  installmentNumber  int value for installmentNumber.
     * @param  amount  double value for amount.
     * @param  status  InstallmentStatusEnum value for status.
     * @param  processDateTime  LocalDateTime value for processDateTime.
     */
    public Installment(
            int installmentNumber,
            double amount,
            InstallmentStatusEnum status,
            LocalDateTime processDateTime) {
        this.installmentNumber = installmentNumber;
        this.amount = amount;
        this.processDateTime = processDateTime;
        this.status = status;
    }

    /**
     * Getter for InstallmentNumber.
     * @return Returns the int
     */
    @JsonGetter("InstallmentNumber")
    public int getInstallmentNumber() {
        return installmentNumber;
    }

    /**
     * Setter for InstallmentNumber.
     * @param installmentNumber Value for int
     */
    @JsonSetter("InstallmentNumber")
    public void setInstallmentNumber(int installmentNumber) {
        this.installmentNumber = installmentNumber;
    }

    /**
     * Getter for Amount.
     * @return Returns the double
     */
    @JsonGetter("Amount")
    public double getAmount() {
        return amount;
    }

    /**
     * Setter for Amount.
     * @param amount Value for double
     */
    @JsonSetter("Amount")
    public void setAmount(double amount) {
        this.amount = amount;
    }

    /**
     * Getter for ProcessDateTime.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("ProcessDateTime")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getProcessDateTime() {
        return processDateTime;
    }

    /**
     * Setter for ProcessDateTime.
     * @param processDateTime Value for LocalDateTime
     */
    @JsonSetter("ProcessDateTime")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setProcessDateTime(LocalDateTime processDateTime) {
        this.processDateTime = processDateTime;
    }

    /**
     * Getter for Status.
     * @return Returns the InstallmentStatusEnum
     */
    @JsonGetter("Status")
    public InstallmentStatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for InstallmentStatusEnum
     */
    @JsonSetter("Status")
    public void setStatus(InstallmentStatusEnum status) {
        this.status = status;
    }

    /**
     * Converts this Installment into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Installment [" + "installmentNumber=" + installmentNumber + ", amount=" + amount
                + ", status=" + status + ", processDateTime=" + processDateTime + "]";
    }

    /**
     * Builds a new {@link Installment.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Installment.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(installmentNumber, amount, status)
                .processDateTime(getProcessDateTime());
        return builder;
    }

    /**
     * Class to build instances of {@link Installment}.
     */
    public static class Builder {
        private int installmentNumber;
        private double amount;
        private InstallmentStatusEnum status;
        private LocalDateTime processDateTime;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  installmentNumber  int value for installmentNumber.
         * @param  amount  double value for amount.
         * @param  status  InstallmentStatusEnum value for status.
         */
        public Builder(int installmentNumber, double amount, InstallmentStatusEnum status) {
            this.installmentNumber = installmentNumber;
            this.amount = amount;
            this.status = status;
        }

        /**
         * Setter for installmentNumber.
         * @param  installmentNumber  int value for installmentNumber.
         * @return Builder
         */
        public Builder installmentNumber(int installmentNumber) {
            this.installmentNumber = installmentNumber;
            return this;
        }

        /**
         * Setter for amount.
         * @param  amount  double value for amount.
         * @return Builder
         */
        public Builder amount(double amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  InstallmentStatusEnum value for status.
         * @return Builder
         */
        public Builder status(InstallmentStatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for processDateTime.
         * @param  processDateTime  LocalDateTime value for processDateTime.
         * @return Builder
         */
        public Builder processDateTime(LocalDateTime processDateTime) {
            this.processDateTime = processDateTime;
            return this;
        }

        /**
         * Builds a new {@link Installment} object using the set fields.
         * @return {@link Installment}
         */
        public Installment build() {
            return new Installment(installmentNumber, amount, status, processDateTime);
        }
    }
}
