/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InstallmentPlanRefundRequest type.
 */
public class InstallmentPlanRefundRequest {
    private String amount;
    private RefundStrategyEnum refundStrategy;
    private String referenceId;

    /**
     * Default constructor.
     */
    public InstallmentPlanRefundRequest() {
    }

    /**
     * Initialization constructor.
     * @param  amount  String value for amount.
     * @param  refundStrategy  RefundStrategyEnum value for refundStrategy.
     * @param  referenceId  String value for referenceId.
     */
    public InstallmentPlanRefundRequest(
            String amount,
            RefundStrategyEnum refundStrategy,
            String referenceId) {
        this.amount = amount;
        this.refundStrategy = refundStrategy;
        this.referenceId = referenceId;
    }

    /**
     * Getter for Amount.
     * @return Returns the String
     */
    @JsonGetter("Amount")
    public String getAmount() {
        return amount;
    }

    /**
     * Setter for Amount.
     * @param amount Value for String
     */
    @JsonSetter("Amount")
    public void setAmount(String amount) {
        this.amount = amount;
    }

    /**
     * Getter for RefundStrategy.
     * @return Returns the RefundStrategyEnum
     */
    @JsonGetter("RefundStrategy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public RefundStrategyEnum getRefundStrategy() {
        return refundStrategy;
    }

    /**
     * Setter for RefundStrategy.
     * @param refundStrategy Value for RefundStrategyEnum
     */
    @JsonSetter("RefundStrategy")
    public void setRefundStrategy(RefundStrategyEnum refundStrategy) {
        this.refundStrategy = refundStrategy;
    }

    /**
     * Getter for ReferenceId.
     * @return Returns the String
     */
    @JsonGetter("ReferenceId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * Setter for ReferenceId.
     * @param referenceId Value for String
     */
    @JsonSetter("ReferenceId")
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    /**
     * Converts this InstallmentPlanRefundRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InstallmentPlanRefundRequest [" + "amount=" + amount + ", refundStrategy="
                + refundStrategy + ", referenceId=" + referenceId + "]";
    }

    /**
     * Builds a new {@link InstallmentPlanRefundRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InstallmentPlanRefundRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(amount)
                .refundStrategy(getRefundStrategy())
                .referenceId(getReferenceId());
        return builder;
    }

    /**
     * Class to build instances of {@link InstallmentPlanRefundRequest}.
     */
    public static class Builder {
        private String amount;
        private RefundStrategyEnum refundStrategy;
        private String referenceId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  amount  String value for amount.
         */
        public Builder(String amount) {
            this.amount = amount;
        }

        /**
         * Setter for amount.
         * @param  amount  String value for amount.
         * @return Builder
         */
        public Builder amount(String amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Setter for refundStrategy.
         * @param  refundStrategy  RefundStrategyEnum value for refundStrategy.
         * @return Builder
         */
        public Builder refundStrategy(RefundStrategyEnum refundStrategy) {
            this.refundStrategy = refundStrategy;
            return this;
        }

        /**
         * Setter for referenceId.
         * @param  referenceId  String value for referenceId.
         * @return Builder
         */
        public Builder referenceId(String referenceId) {
            this.referenceId = referenceId;
            return this;
        }

        /**
         * Builds a new {@link InstallmentPlanRefundRequest} object using the set fields.
         * @return {@link InstallmentPlanRefundRequest}
         */
        public InstallmentPlanRefundRequest build() {
            return new InstallmentPlanRefundRequest(amount, refundStrategy, referenceId);
        }
    }
}
