/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InstallmentPlanUpdateResponse type.
 */
public class InstallmentPlanUpdateResponse {
    private String refOrderNumber;
    private String installmentPlanNumber;
    private PlanStatusEnum status;
    private ShippingStatusEnum shippingStatus;
    private Double newAmount;

    /**
     * Default constructor.
     */
    public InstallmentPlanUpdateResponse() {
    }

    /**
     * Initialization constructor.
     * @param  status  PlanStatusEnum value for status.
     * @param  shippingStatus  ShippingStatusEnum value for shippingStatus.
     * @param  refOrderNumber  String value for refOrderNumber.
     * @param  installmentPlanNumber  String value for installmentPlanNumber.
     * @param  newAmount  Double value for newAmount.
     */
    public InstallmentPlanUpdateResponse(
            PlanStatusEnum status,
            ShippingStatusEnum shippingStatus,
            String refOrderNumber,
            String installmentPlanNumber,
            Double newAmount) {
        this.refOrderNumber = refOrderNumber;
        this.installmentPlanNumber = installmentPlanNumber;
        this.status = status;
        this.shippingStatus = shippingStatus;
        this.newAmount = newAmount;
    }

    /**
     * Getter for RefOrderNumber.
     * @return Returns the String
     */
    @JsonGetter("RefOrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRefOrderNumber() {
        return refOrderNumber;
    }

    /**
     * Setter for RefOrderNumber.
     * @param refOrderNumber Value for String
     */
    @JsonSetter("RefOrderNumber")
    public void setRefOrderNumber(String refOrderNumber) {
        this.refOrderNumber = refOrderNumber;
    }

    /**
     * Getter for InstallmentPlanNumber.
     * @return Returns the String
     */
    @JsonGetter("InstallmentPlanNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getInstallmentPlanNumber() {
        return installmentPlanNumber;
    }

    /**
     * Setter for InstallmentPlanNumber.
     * @param installmentPlanNumber Value for String
     */
    @JsonSetter("InstallmentPlanNumber")
    public void setInstallmentPlanNumber(String installmentPlanNumber) {
        this.installmentPlanNumber = installmentPlanNumber;
    }

    /**
     * Getter for Status.
     * @return Returns the PlanStatusEnum
     */
    @JsonGetter("Status")
    public PlanStatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for PlanStatusEnum
     */
    @JsonSetter("Status")
    public void setStatus(PlanStatusEnum status) {
        this.status = status;
    }

    /**
     * Getter for ShippingStatus.
     * @return Returns the ShippingStatusEnum
     */
    @JsonGetter("ShippingStatus")
    public ShippingStatusEnum getShippingStatus() {
        return shippingStatus;
    }

    /**
     * Setter for ShippingStatus.
     * @param shippingStatus Value for ShippingStatusEnum
     */
    @JsonSetter("ShippingStatus")
    public void setShippingStatus(ShippingStatusEnum shippingStatus) {
        this.shippingStatus = shippingStatus;
    }

    /**
     * Getter for NewAmount.
     * @return Returns the Double
     */
    @JsonGetter("NewAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getNewAmount() {
        return newAmount;
    }

    /**
     * Setter for NewAmount.
     * @param newAmount Value for Double
     */
    @JsonSetter("NewAmount")
    public void setNewAmount(Double newAmount) {
        this.newAmount = newAmount;
    }

    /**
     * Converts this InstallmentPlanUpdateResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InstallmentPlanUpdateResponse [" + "status=" + status + ", shippingStatus="
                + shippingStatus + ", refOrderNumber=" + refOrderNumber + ", installmentPlanNumber="
                + installmentPlanNumber + ", newAmount=" + newAmount + "]";
    }

    /**
     * Builds a new {@link InstallmentPlanUpdateResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InstallmentPlanUpdateResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(status, shippingStatus)
                .refOrderNumber(getRefOrderNumber())
                .installmentPlanNumber(getInstallmentPlanNumber())
                .newAmount(getNewAmount());
        return builder;
    }

    /**
     * Class to build instances of {@link InstallmentPlanUpdateResponse}.
     */
    public static class Builder {
        private PlanStatusEnum status;
        private ShippingStatusEnum shippingStatus;
        private String refOrderNumber;
        private String installmentPlanNumber;
        private Double newAmount;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  status  PlanStatusEnum value for status.
         * @param  shippingStatus  ShippingStatusEnum value for shippingStatus.
         */
        public Builder(PlanStatusEnum status, ShippingStatusEnum shippingStatus) {
            this.status = status;
            this.shippingStatus = shippingStatus;
        }

        /**
         * Setter for status.
         * @param  status  PlanStatusEnum value for status.
         * @return Builder
         */
        public Builder status(PlanStatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for shippingStatus.
         * @param  shippingStatus  ShippingStatusEnum value for shippingStatus.
         * @return Builder
         */
        public Builder shippingStatus(ShippingStatusEnum shippingStatus) {
            this.shippingStatus = shippingStatus;
            return this;
        }

        /**
         * Setter for refOrderNumber.
         * @param  refOrderNumber  String value for refOrderNumber.
         * @return Builder
         */
        public Builder refOrderNumber(String refOrderNumber) {
            this.refOrderNumber = refOrderNumber;
            return this;
        }

        /**
         * Setter for installmentPlanNumber.
         * @param  installmentPlanNumber  String value for installmentPlanNumber.
         * @return Builder
         */
        public Builder installmentPlanNumber(String installmentPlanNumber) {
            this.installmentPlanNumber = installmentPlanNumber;
            return this;
        }

        /**
         * Setter for newAmount.
         * @param  newAmount  Double value for newAmount.
         * @return Builder
         */
        public Builder newAmount(Double newAmount) {
            this.newAmount = newAmount;
            return this;
        }

        /**
         * Builds a new {@link InstallmentPlanUpdateResponse} object using the set fields.
         * @return {@link InstallmentPlanUpdateResponse}
         */
        public InstallmentPlanUpdateResponse build() {
            return new InstallmentPlanUpdateResponse(status, shippingStatus, refOrderNumber,
                    installmentPlanNumber, newAmount);
        }
    }
}
