/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InstallmentPlanRefundResponse type.
 */
public class InstallmentPlanRefundResponse {
    private String refundId;
    private String installmentPlanNumber;
    private String currency;
    private Double nonCreditRefundAmount;
    private Double creditRefundAmount;
    private RefundSummary summary;
    private String referenceId;

    /**
     * Default constructor.
     */
    public InstallmentPlanRefundResponse() {
    }

    /**
     * Initialization constructor.
     * @param  refundId  String value for refundId.
     * @param  installmentPlanNumber  String value for installmentPlanNumber.
     * @param  currency  String value for currency.
     * @param  nonCreditRefundAmount  Double value for nonCreditRefundAmount.
     * @param  creditRefundAmount  Double value for creditRefundAmount.
     * @param  summary  RefundSummary value for summary.
     * @param  referenceId  String value for referenceId.
     */
    public InstallmentPlanRefundResponse(
            String refundId,
            String installmentPlanNumber,
            String currency,
            Double nonCreditRefundAmount,
            Double creditRefundAmount,
            RefundSummary summary,
            String referenceId) {
        this.refundId = refundId;
        this.installmentPlanNumber = installmentPlanNumber;
        this.currency = currency;
        this.nonCreditRefundAmount = nonCreditRefundAmount;
        this.creditRefundAmount = creditRefundAmount;
        this.summary = summary;
        this.referenceId = referenceId;
    }

    /**
     * Getter for RefundId.
     * @return Returns the String
     */
    @JsonGetter("RefundId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRefundId() {
        return refundId;
    }

    /**
     * Setter for RefundId.
     * @param refundId Value for String
     */
    @JsonSetter("RefundId")
    public void setRefundId(String refundId) {
        this.refundId = refundId;
    }

    /**
     * Getter for InstallmentPlanNumber.
     * @return Returns the String
     */
    @JsonGetter("InstallmentPlanNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getInstallmentPlanNumber() {
        return installmentPlanNumber;
    }

    /**
     * Setter for InstallmentPlanNumber.
     * @param installmentPlanNumber Value for String
     */
    @JsonSetter("InstallmentPlanNumber")
    public void setInstallmentPlanNumber(String installmentPlanNumber) {
        this.installmentPlanNumber = installmentPlanNumber;
    }

    /**
     * Getter for Currency.
     * @return Returns the String
     */
    @JsonGetter("Currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCurrency() {
        return currency;
    }

    /**
     * Setter for Currency.
     * @param currency Value for String
     */
    @JsonSetter("Currency")
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Getter for NonCreditRefundAmount.
     * @return Returns the Double
     */
    @JsonGetter("NonCreditRefundAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getNonCreditRefundAmount() {
        return nonCreditRefundAmount;
    }

    /**
     * Setter for NonCreditRefundAmount.
     * @param nonCreditRefundAmount Value for Double
     */
    @JsonSetter("NonCreditRefundAmount")
    public void setNonCreditRefundAmount(Double nonCreditRefundAmount) {
        this.nonCreditRefundAmount = nonCreditRefundAmount;
    }

    /**
     * Getter for CreditRefundAmount.
     * @return Returns the Double
     */
    @JsonGetter("CreditRefundAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getCreditRefundAmount() {
        return creditRefundAmount;
    }

    /**
     * Setter for CreditRefundAmount.
     * @param creditRefundAmount Value for Double
     */
    @JsonSetter("CreditRefundAmount")
    public void setCreditRefundAmount(Double creditRefundAmount) {
        this.creditRefundAmount = creditRefundAmount;
    }

    /**
     * Getter for Summary.
     * @return Returns the RefundSummary
     */
    @JsonGetter("Summary")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public RefundSummary getSummary() {
        return summary;
    }

    /**
     * Setter for Summary.
     * @param summary Value for RefundSummary
     */
    @JsonSetter("Summary")
    public void setSummary(RefundSummary summary) {
        this.summary = summary;
    }

    /**
     * Getter for ReferenceId.
     * @return Returns the String
     */
    @JsonGetter("ReferenceId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * Setter for ReferenceId.
     * @param referenceId Value for String
     */
    @JsonSetter("ReferenceId")
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    /**
     * Converts this InstallmentPlanRefundResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InstallmentPlanRefundResponse [" + "refundId=" + refundId
                + ", installmentPlanNumber=" + installmentPlanNumber + ", currency=" + currency
                + ", nonCreditRefundAmount=" + nonCreditRefundAmount + ", creditRefundAmount="
                + creditRefundAmount + ", summary=" + summary + ", referenceId=" + referenceId
                + "]";
    }

    /**
     * Builds a new {@link InstallmentPlanRefundResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InstallmentPlanRefundResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .refundId(getRefundId())
                .installmentPlanNumber(getInstallmentPlanNumber())
                .currency(getCurrency())
                .nonCreditRefundAmount(getNonCreditRefundAmount())
                .creditRefundAmount(getCreditRefundAmount())
                .summary(getSummary())
                .referenceId(getReferenceId());
        return builder;
    }

    /**
     * Class to build instances of {@link InstallmentPlanRefundResponse}.
     */
    public static class Builder {
        private String refundId;
        private String installmentPlanNumber;
        private String currency;
        private Double nonCreditRefundAmount;
        private Double creditRefundAmount;
        private RefundSummary summary;
        private String referenceId;



        /**
         * Setter for refundId.
         * @param  refundId  String value for refundId.
         * @return Builder
         */
        public Builder refundId(String refundId) {
            this.refundId = refundId;
            return this;
        }

        /**
         * Setter for installmentPlanNumber.
         * @param  installmentPlanNumber  String value for installmentPlanNumber.
         * @return Builder
         */
        public Builder installmentPlanNumber(String installmentPlanNumber) {
            this.installmentPlanNumber = installmentPlanNumber;
            return this;
        }

        /**
         * Setter for currency.
         * @param  currency  String value for currency.
         * @return Builder
         */
        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * Setter for nonCreditRefundAmount.
         * @param  nonCreditRefundAmount  Double value for nonCreditRefundAmount.
         * @return Builder
         */
        public Builder nonCreditRefundAmount(Double nonCreditRefundAmount) {
            this.nonCreditRefundAmount = nonCreditRefundAmount;
            return this;
        }

        /**
         * Setter for creditRefundAmount.
         * @param  creditRefundAmount  Double value for creditRefundAmount.
         * @return Builder
         */
        public Builder creditRefundAmount(Double creditRefundAmount) {
            this.creditRefundAmount = creditRefundAmount;
            return this;
        }

        /**
         * Setter for summary.
         * @param  summary  RefundSummary value for summary.
         * @return Builder
         */
        public Builder summary(RefundSummary summary) {
            this.summary = summary;
            return this;
        }

        /**
         * Setter for referenceId.
         * @param  referenceId  String value for referenceId.
         * @return Builder
         */
        public Builder referenceId(String referenceId) {
            this.referenceId = referenceId;
            return this;
        }

        /**
         * Builds a new {@link InstallmentPlanRefundResponse} object using the set fields.
         * @return {@link InstallmentPlanRefundResponse}
         */
        public InstallmentPlanRefundResponse build() {
            return new InstallmentPlanRefundResponse(refundId, installmentPlanNumber, currency,
                    nonCreditRefundAmount, creditRefundAmount, summary, referenceId);
        }
    }
}
