/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InstallmentPlanCreateRequest type.
 */
public class InstallmentPlanCreateRequest {
    private boolean autoCapture;
    private Boolean attempt3dSecure;
    private boolean termsAndConditionsAccepted;
    private ShopperData shopper;
    private PlanDataModel planData;
    private AddressDataModel billingAddress;
    private PaymentMethodModel paymentMethod;
    private RedirectionEndpointsModel redirectUrls;
    private ProcessingData processingData;
    private EventsEndpointsModel eventsEndpoints;

    /**
     * Default constructor.
     */
    public InstallmentPlanCreateRequest() {
    }

    /**
     * Initialization constructor.
     * @param  autoCapture  boolean value for autoCapture.
     * @param  termsAndConditionsAccepted  boolean value for termsAndConditionsAccepted.
     * @param  attempt3dSecure  Boolean value for attempt3dSecure.
     * @param  shopper  ShopperData value for shopper.
     * @param  planData  PlanDataModel value for planData.
     * @param  billingAddress  AddressDataModel value for billingAddress.
     * @param  paymentMethod  PaymentMethodModel value for paymentMethod.
     * @param  redirectUrls  RedirectionEndpointsModel value for redirectUrls.
     * @param  processingData  ProcessingData value for processingData.
     * @param  eventsEndpoints  EventsEndpointsModel value for eventsEndpoints.
     */
    public InstallmentPlanCreateRequest(
            boolean autoCapture,
            boolean termsAndConditionsAccepted,
            Boolean attempt3dSecure,
            ShopperData shopper,
            PlanDataModel planData,
            AddressDataModel billingAddress,
            PaymentMethodModel paymentMethod,
            RedirectionEndpointsModel redirectUrls,
            ProcessingData processingData,
            EventsEndpointsModel eventsEndpoints) {
        this.autoCapture = autoCapture;
        this.attempt3dSecure = attempt3dSecure;
        this.termsAndConditionsAccepted = termsAndConditionsAccepted;
        this.shopper = shopper;
        this.planData = planData;
        this.billingAddress = billingAddress;
        this.paymentMethod = paymentMethod;
        this.redirectUrls = redirectUrls;
        this.processingData = processingData;
        this.eventsEndpoints = eventsEndpoints;
    }

    /**
     * Getter for AutoCapture.
     * @return Returns the boolean
     */
    @JsonGetter("AutoCapture")
    public boolean getAutoCapture() {
        return autoCapture;
    }

    /**
     * Setter for AutoCapture.
     * @param autoCapture Value for boolean
     */
    @JsonSetter("AutoCapture")
    public void setAutoCapture(boolean autoCapture) {
        this.autoCapture = autoCapture;
    }

    /**
     * Getter for Attempt3dSecure.
     * @return Returns the Boolean
     */
    @JsonGetter("Attempt3dSecure")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getAttempt3dSecure() {
        return attempt3dSecure;
    }

    /**
     * Setter for Attempt3dSecure.
     * @param attempt3dSecure Value for Boolean
     */
    @JsonSetter("Attempt3dSecure")
    public void setAttempt3dSecure(Boolean attempt3dSecure) {
        this.attempt3dSecure = attempt3dSecure;
    }

    /**
     * Getter for TermsAndConditionsAccepted.
     * @return Returns the boolean
     */
    @JsonGetter("TermsAndConditionsAccepted")
    public boolean getTermsAndConditionsAccepted() {
        return termsAndConditionsAccepted;
    }

    /**
     * Setter for TermsAndConditionsAccepted.
     * @param termsAndConditionsAccepted Value for boolean
     */
    @JsonSetter("TermsAndConditionsAccepted")
    public void setTermsAndConditionsAccepted(boolean termsAndConditionsAccepted) {
        this.termsAndConditionsAccepted = termsAndConditionsAccepted;
    }

    /**
     * Getter for Shopper.
     * @return Returns the ShopperData
     */
    @JsonGetter("Shopper")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShopperData getShopper() {
        return shopper;
    }

    /**
     * Setter for Shopper.
     * @param shopper Value for ShopperData
     */
    @JsonSetter("Shopper")
    public void setShopper(ShopperData shopper) {
        this.shopper = shopper;
    }

    /**
     * Getter for PlanData.
     * @return Returns the PlanDataModel
     */
    @JsonGetter("PlanData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PlanDataModel getPlanData() {
        return planData;
    }

    /**
     * Setter for PlanData.
     * @param planData Value for PlanDataModel
     */
    @JsonSetter("PlanData")
    public void setPlanData(PlanDataModel planData) {
        this.planData = planData;
    }

    /**
     * Getter for BillingAddress.
     * @return Returns the AddressDataModel
     */
    @JsonGetter("BillingAddress")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AddressDataModel getBillingAddress() {
        return billingAddress;
    }

    /**
     * Setter for BillingAddress.
     * @param billingAddress Value for AddressDataModel
     */
    @JsonSetter("BillingAddress")
    public void setBillingAddress(AddressDataModel billingAddress) {
        this.billingAddress = billingAddress;
    }

    /**
     * Getter for PaymentMethod.
     * @return Returns the PaymentMethodModel
     */
    @JsonGetter("PaymentMethod")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PaymentMethodModel getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Setter for PaymentMethod.
     * @param paymentMethod Value for PaymentMethodModel
     */
    @JsonSetter("PaymentMethod")
    public void setPaymentMethod(PaymentMethodModel paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * Getter for RedirectUrls.
     * @return Returns the RedirectionEndpointsModel
     */
    @JsonGetter("RedirectUrls")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public RedirectionEndpointsModel getRedirectUrls() {
        return redirectUrls;
    }

    /**
     * Setter for RedirectUrls.
     * @param redirectUrls Value for RedirectionEndpointsModel
     */
    @JsonSetter("RedirectUrls")
    public void setRedirectUrls(RedirectionEndpointsModel redirectUrls) {
        this.redirectUrls = redirectUrls;
    }

    /**
     * Getter for ProcessingData.
     * @return Returns the ProcessingData
     */
    @JsonGetter("ProcessingData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProcessingData getProcessingData() {
        return processingData;
    }

    /**
     * Setter for ProcessingData.
     * @param processingData Value for ProcessingData
     */
    @JsonSetter("ProcessingData")
    public void setProcessingData(ProcessingData processingData) {
        this.processingData = processingData;
    }

    /**
     * Getter for EventsEndpoints.
     * @return Returns the EventsEndpointsModel
     */
    @JsonGetter("EventsEndpoints")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EventsEndpointsModel getEventsEndpoints() {
        return eventsEndpoints;
    }

    /**
     * Setter for EventsEndpoints.
     * @param eventsEndpoints Value for EventsEndpointsModel
     */
    @JsonSetter("EventsEndpoints")
    public void setEventsEndpoints(EventsEndpointsModel eventsEndpoints) {
        this.eventsEndpoints = eventsEndpoints;
    }

    /**
     * Converts this InstallmentPlanCreateRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InstallmentPlanCreateRequest [" + "autoCapture=" + autoCapture
                + ", termsAndConditionsAccepted=" + termsAndConditionsAccepted
                + ", attempt3dSecure=" + attempt3dSecure + ", shopper=" + shopper + ", planData="
                + planData + ", billingAddress=" + billingAddress + ", paymentMethod="
                + paymentMethod + ", redirectUrls=" + redirectUrls + ", processingData="
                + processingData + ", eventsEndpoints=" + eventsEndpoints + "]";
    }

    /**
     * Builds a new {@link InstallmentPlanCreateRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InstallmentPlanCreateRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(autoCapture, termsAndConditionsAccepted)
                .attempt3dSecure(getAttempt3dSecure())
                .shopper(getShopper())
                .planData(getPlanData())
                .billingAddress(getBillingAddress())
                .paymentMethod(getPaymentMethod())
                .redirectUrls(getRedirectUrls())
                .processingData(getProcessingData())
                .eventsEndpoints(getEventsEndpoints());
        return builder;
    }

    /**
     * Class to build instances of {@link InstallmentPlanCreateRequest}.
     */
    public static class Builder {
        private boolean autoCapture;
        private boolean termsAndConditionsAccepted;
        private Boolean attempt3dSecure;
        private ShopperData shopper;
        private PlanDataModel planData;
        private AddressDataModel billingAddress;
        private PaymentMethodModel paymentMethod;
        private RedirectionEndpointsModel redirectUrls;
        private ProcessingData processingData;
        private EventsEndpointsModel eventsEndpoints;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  autoCapture  boolean value for autoCapture.
         * @param  termsAndConditionsAccepted  boolean value for termsAndConditionsAccepted.
         */
        public Builder(boolean autoCapture, boolean termsAndConditionsAccepted) {
            this.autoCapture = autoCapture;
            this.termsAndConditionsAccepted = termsAndConditionsAccepted;
        }

        /**
         * Setter for autoCapture.
         * @param  autoCapture  boolean value for autoCapture.
         * @return Builder
         */
        public Builder autoCapture(boolean autoCapture) {
            this.autoCapture = autoCapture;
            return this;
        }

        /**
         * Setter for termsAndConditionsAccepted.
         * @param  termsAndConditionsAccepted  boolean value for termsAndConditionsAccepted.
         * @return Builder
         */
        public Builder termsAndConditionsAccepted(boolean termsAndConditionsAccepted) {
            this.termsAndConditionsAccepted = termsAndConditionsAccepted;
            return this;
        }

        /**
         * Setter for attempt3dSecure.
         * @param  attempt3dSecure  Boolean value for attempt3dSecure.
         * @return Builder
         */
        public Builder attempt3dSecure(Boolean attempt3dSecure) {
            this.attempt3dSecure = attempt3dSecure;
            return this;
        }

        /**
         * Setter for shopper.
         * @param  shopper  ShopperData value for shopper.
         * @return Builder
         */
        public Builder shopper(ShopperData shopper) {
            this.shopper = shopper;
            return this;
        }

        /**
         * Setter for planData.
         * @param  planData  PlanDataModel value for planData.
         * @return Builder
         */
        public Builder planData(PlanDataModel planData) {
            this.planData = planData;
            return this;
        }

        /**
         * Setter for billingAddress.
         * @param  billingAddress  AddressDataModel value for billingAddress.
         * @return Builder
         */
        public Builder billingAddress(AddressDataModel billingAddress) {
            this.billingAddress = billingAddress;
            return this;
        }

        /**
         * Setter for paymentMethod.
         * @param  paymentMethod  PaymentMethodModel value for paymentMethod.
         * @return Builder
         */
        public Builder paymentMethod(PaymentMethodModel paymentMethod) {
            this.paymentMethod = paymentMethod;
            return this;
        }

        /**
         * Setter for redirectUrls.
         * @param  redirectUrls  RedirectionEndpointsModel value for redirectUrls.
         * @return Builder
         */
        public Builder redirectUrls(RedirectionEndpointsModel redirectUrls) {
            this.redirectUrls = redirectUrls;
            return this;
        }

        /**
         * Setter for processingData.
         * @param  processingData  ProcessingData value for processingData.
         * @return Builder
         */
        public Builder processingData(ProcessingData processingData) {
            this.processingData = processingData;
            return this;
        }

        /**
         * Setter for eventsEndpoints.
         * @param  eventsEndpoints  EventsEndpointsModel value for eventsEndpoints.
         * @return Builder
         */
        public Builder eventsEndpoints(EventsEndpointsModel eventsEndpoints) {
            this.eventsEndpoints = eventsEndpoints;
            return this;
        }

        /**
         * Builds a new {@link InstallmentPlanCreateRequest} object using the set fields.
         * @return {@link InstallmentPlanCreateRequest}
         */
        public InstallmentPlanCreateRequest build() {
            return new InstallmentPlanCreateRequest(autoCapture, termsAndConditionsAccepted,
                    attempt3dSecure, shopper, planData, billingAddress, paymentMethod, redirectUrls,
                    processingData, eventsEndpoints);
        }
    }
}
