/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for InstallmentPlanSearchResponse type.
 */
public class InstallmentPlanSearchResponse {
    private List<SearchInstallmentPlanResponseItem> planList;

    /**
     * Default constructor.
     */
    public InstallmentPlanSearchResponse() {
    }

    /**
     * Initialization constructor.
     * @param  planList  List of SearchInstallmentPlanResponseItem value for planList.
     */
    public InstallmentPlanSearchResponse(
            List<SearchInstallmentPlanResponseItem> planList) {
        this.planList = planList;
    }

    /**
     * Getter for PlanList.
     * @return Returns the List of SearchInstallmentPlanResponseItem
     */
    @JsonGetter("PlanList")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<SearchInstallmentPlanResponseItem> getPlanList() {
        return planList;
    }

    /**
     * Setter for PlanList.
     * @param planList Value for List of SearchInstallmentPlanResponseItem
     */
    @JsonSetter("PlanList")
    public void setPlanList(List<SearchInstallmentPlanResponseItem> planList) {
        this.planList = planList;
    }

    /**
     * Converts this InstallmentPlanSearchResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InstallmentPlanSearchResponse [" + "planList=" + planList + "]";
    }

    /**
     * Builds a new {@link InstallmentPlanSearchResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InstallmentPlanSearchResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .planList(getPlanList());
        return builder;
    }

    /**
     * Class to build instances of {@link InstallmentPlanSearchResponse}.
     */
    public static class Builder {
        private List<SearchInstallmentPlanResponseItem> planList;



        /**
         * Setter for planList.
         * @param  planList  List of SearchInstallmentPlanResponseItem value for planList.
         * @return Builder
         */
        public Builder planList(List<SearchInstallmentPlanResponseItem> planList) {
            this.planList = planList;
            return this;
        }

        /**
         * Builds a new {@link InstallmentPlanSearchResponse} object using the set fields.
         * @return {@link InstallmentPlanSearchResponse}
         */
        public InstallmentPlanSearchResponse build() {
            return new InstallmentPlanSearchResponse(planList);
        }
    }
}
