/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InstallmentPlanInitiateRequest type.
 */
public class InstallmentPlanInitiateRequest {
    private Boolean autoCapture;
    private Boolean attempt3dSecure;
    private ShopperData shopper;
    private PlanDataModel planData;
    private AddressDataModel billingAddress;
    private InitiateRedirectionEndpointsModel redirectUrls;
    private UxSettingsModel uxSettings;
    private EventsEndpointsModel eventsEndpoints;
    private ProcessingData processingData;

    /**
     * Default constructor.
     */
    public InstallmentPlanInitiateRequest() {
    }

    /**
     * Initialization constructor.
     * @param  autoCapture  Boolean value for autoCapture.
     * @param  attempt3dSecure  Boolean value for attempt3dSecure.
     * @param  shopper  ShopperData value for shopper.
     * @param  planData  PlanDataModel value for planData.
     * @param  billingAddress  AddressDataModel value for billingAddress.
     * @param  redirectUrls  InitiateRedirectionEndpointsModel value for redirectUrls.
     * @param  uxSettings  UxSettingsModel value for uxSettings.
     * @param  eventsEndpoints  EventsEndpointsModel value for eventsEndpoints.
     * @param  processingData  ProcessingData value for processingData.
     */
    public InstallmentPlanInitiateRequest(
            Boolean autoCapture,
            Boolean attempt3dSecure,
            ShopperData shopper,
            PlanDataModel planData,
            AddressDataModel billingAddress,
            InitiateRedirectionEndpointsModel redirectUrls,
            UxSettingsModel uxSettings,
            EventsEndpointsModel eventsEndpoints,
            ProcessingData processingData) {
        this.autoCapture = autoCapture;
        this.attempt3dSecure = attempt3dSecure;
        this.shopper = shopper;
        this.planData = planData;
        this.billingAddress = billingAddress;
        this.redirectUrls = redirectUrls;
        this.uxSettings = uxSettings;
        this.eventsEndpoints = eventsEndpoints;
        this.processingData = processingData;
    }

    /**
     * Getter for AutoCapture.
     * @return Returns the Boolean
     */
    @JsonGetter("AutoCapture")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getAutoCapture() {
        return autoCapture;
    }

    /**
     * Setter for AutoCapture.
     * @param autoCapture Value for Boolean
     */
    @JsonSetter("AutoCapture")
    public void setAutoCapture(Boolean autoCapture) {
        this.autoCapture = autoCapture;
    }

    /**
     * Getter for Attempt3dSecure.
     * @return Returns the Boolean
     */
    @JsonGetter("Attempt3dSecure")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getAttempt3dSecure() {
        return attempt3dSecure;
    }

    /**
     * Setter for Attempt3dSecure.
     * @param attempt3dSecure Value for Boolean
     */
    @JsonSetter("Attempt3dSecure")
    public void setAttempt3dSecure(Boolean attempt3dSecure) {
        this.attempt3dSecure = attempt3dSecure;
    }

    /**
     * Getter for Shopper.
     * @return Returns the ShopperData
     */
    @JsonGetter("Shopper")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShopperData getShopper() {
        return shopper;
    }

    /**
     * Setter for Shopper.
     * @param shopper Value for ShopperData
     */
    @JsonSetter("Shopper")
    public void setShopper(ShopperData shopper) {
        this.shopper = shopper;
    }

    /**
     * Getter for PlanData.
     * @return Returns the PlanDataModel
     */
    @JsonGetter("PlanData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PlanDataModel getPlanData() {
        return planData;
    }

    /**
     * Setter for PlanData.
     * @param planData Value for PlanDataModel
     */
    @JsonSetter("PlanData")
    public void setPlanData(PlanDataModel planData) {
        this.planData = planData;
    }

    /**
     * Getter for BillingAddress.
     * @return Returns the AddressDataModel
     */
    @JsonGetter("BillingAddress")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AddressDataModel getBillingAddress() {
        return billingAddress;
    }

    /**
     * Setter for BillingAddress.
     * @param billingAddress Value for AddressDataModel
     */
    @JsonSetter("BillingAddress")
    public void setBillingAddress(AddressDataModel billingAddress) {
        this.billingAddress = billingAddress;
    }

    /**
     * Getter for RedirectUrls.
     * @return Returns the InitiateRedirectionEndpointsModel
     */
    @JsonGetter("RedirectUrls")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public InitiateRedirectionEndpointsModel getRedirectUrls() {
        return redirectUrls;
    }

    /**
     * Setter for RedirectUrls.
     * @param redirectUrls Value for InitiateRedirectionEndpointsModel
     */
    @JsonSetter("RedirectUrls")
    public void setRedirectUrls(InitiateRedirectionEndpointsModel redirectUrls) {
        this.redirectUrls = redirectUrls;
    }

    /**
     * Getter for UxSettings.
     * @return Returns the UxSettingsModel
     */
    @JsonGetter("UxSettings")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UxSettingsModel getUxSettings() {
        return uxSettings;
    }

    /**
     * Setter for UxSettings.
     * @param uxSettings Value for UxSettingsModel
     */
    @JsonSetter("UxSettings")
    public void setUxSettings(UxSettingsModel uxSettings) {
        this.uxSettings = uxSettings;
    }

    /**
     * Getter for EventsEndpoints.
     * @return Returns the EventsEndpointsModel
     */
    @JsonGetter("EventsEndpoints")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EventsEndpointsModel getEventsEndpoints() {
        return eventsEndpoints;
    }

    /**
     * Setter for EventsEndpoints.
     * @param eventsEndpoints Value for EventsEndpointsModel
     */
    @JsonSetter("EventsEndpoints")
    public void setEventsEndpoints(EventsEndpointsModel eventsEndpoints) {
        this.eventsEndpoints = eventsEndpoints;
    }

    /**
     * Getter for ProcessingData.
     * @return Returns the ProcessingData
     */
    @JsonGetter("ProcessingData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProcessingData getProcessingData() {
        return processingData;
    }

    /**
     * Setter for ProcessingData.
     * @param processingData Value for ProcessingData
     */
    @JsonSetter("ProcessingData")
    public void setProcessingData(ProcessingData processingData) {
        this.processingData = processingData;
    }

    /**
     * Converts this InstallmentPlanInitiateRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InstallmentPlanInitiateRequest [" + "autoCapture=" + autoCapture
                + ", attempt3dSecure=" + attempt3dSecure + ", shopper=" + shopper + ", planData="
                + planData + ", billingAddress=" + billingAddress + ", redirectUrls=" + redirectUrls
                + ", uxSettings=" + uxSettings + ", eventsEndpoints=" + eventsEndpoints
                + ", processingData=" + processingData + "]";
    }

    /**
     * Builds a new {@link InstallmentPlanInitiateRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InstallmentPlanInitiateRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .autoCapture(getAutoCapture())
                .attempt3dSecure(getAttempt3dSecure())
                .shopper(getShopper())
                .planData(getPlanData())
                .billingAddress(getBillingAddress())
                .redirectUrls(getRedirectUrls())
                .uxSettings(getUxSettings())
                .eventsEndpoints(getEventsEndpoints())
                .processingData(getProcessingData());
        return builder;
    }

    /**
     * Class to build instances of {@link InstallmentPlanInitiateRequest}.
     */
    public static class Builder {
        private Boolean autoCapture;
        private Boolean attempt3dSecure;
        private ShopperData shopper;
        private PlanDataModel planData;
        private AddressDataModel billingAddress;
        private InitiateRedirectionEndpointsModel redirectUrls;
        private UxSettingsModel uxSettings;
        private EventsEndpointsModel eventsEndpoints;
        private ProcessingData processingData;



        /**
         * Setter for autoCapture.
         * @param  autoCapture  Boolean value for autoCapture.
         * @return Builder
         */
        public Builder autoCapture(Boolean autoCapture) {
            this.autoCapture = autoCapture;
            return this;
        }

        /**
         * Setter for attempt3dSecure.
         * @param  attempt3dSecure  Boolean value for attempt3dSecure.
         * @return Builder
         */
        public Builder attempt3dSecure(Boolean attempt3dSecure) {
            this.attempt3dSecure = attempt3dSecure;
            return this;
        }

        /**
         * Setter for shopper.
         * @param  shopper  ShopperData value for shopper.
         * @return Builder
         */
        public Builder shopper(ShopperData shopper) {
            this.shopper = shopper;
            return this;
        }

        /**
         * Setter for planData.
         * @param  planData  PlanDataModel value for planData.
         * @return Builder
         */
        public Builder planData(PlanDataModel planData) {
            this.planData = planData;
            return this;
        }

        /**
         * Setter for billingAddress.
         * @param  billingAddress  AddressDataModel value for billingAddress.
         * @return Builder
         */
        public Builder billingAddress(AddressDataModel billingAddress) {
            this.billingAddress = billingAddress;
            return this;
        }

        /**
         * Setter for redirectUrls.
         * @param  redirectUrls  InitiateRedirectionEndpointsModel value for redirectUrls.
         * @return Builder
         */
        public Builder redirectUrls(InitiateRedirectionEndpointsModel redirectUrls) {
            this.redirectUrls = redirectUrls;
            return this;
        }

        /**
         * Setter for uxSettings.
         * @param  uxSettings  UxSettingsModel value for uxSettings.
         * @return Builder
         */
        public Builder uxSettings(UxSettingsModel uxSettings) {
            this.uxSettings = uxSettings;
            return this;
        }

        /**
         * Setter for eventsEndpoints.
         * @param  eventsEndpoints  EventsEndpointsModel value for eventsEndpoints.
         * @return Builder
         */
        public Builder eventsEndpoints(EventsEndpointsModel eventsEndpoints) {
            this.eventsEndpoints = eventsEndpoints;
            return this;
        }

        /**
         * Setter for processingData.
         * @param  processingData  ProcessingData value for processingData.
         * @return Builder
         */
        public Builder processingData(ProcessingData processingData) {
            this.processingData = processingData;
            return this;
        }

        /**
         * Builds a new {@link InstallmentPlanInitiateRequest} object using the set fields.
         * @return {@link InstallmentPlanInitiateRequest}
         */
        public InstallmentPlanInitiateRequest build() {
            return new InstallmentPlanInitiateRequest(autoCapture, attempt3dSecure, shopper,
                    planData, billingAddress, redirectUrls, uxSettings, eventsEndpoints,
                    processingData);
        }
    }
}
