/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.splitit.sandbox.webapiv3.DateTimeHelper;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for InstallmentPlanCreateResponse type.
 */
public class InstallmentPlanCreateResponse {
    private String installmentPlanNumber;
    private LocalDateTime dateCreated;
    private String refOrderNumber;
    private PurchaseMethodEnum purchaseMethod;
    private PlanStatusEnum status;
    private String currency;
    private Double originalAmount;
    private Double amount;
    private Map<String, String> extendedParams;
    private AuthorizationModel authorization;
    private ShopperData shopper;
    private AddressData billingAddress;
    private PaymentMethodModel paymentMethod;
    private List<Installment> installments;
    private LinksData links;

    /**
     * Default constructor.
     */
    public InstallmentPlanCreateResponse() {
    }

    /**
     * Initialization constructor.
     * @param  dateCreated  LocalDateTime value for dateCreated.
     * @param  status  PlanStatusEnum value for status.
     * @param  installmentPlanNumber  String value for installmentPlanNumber.
     * @param  refOrderNumber  String value for refOrderNumber.
     * @param  purchaseMethod  PurchaseMethodEnum value for purchaseMethod.
     * @param  currency  String value for currency.
     * @param  originalAmount  Double value for originalAmount.
     * @param  amount  Double value for amount.
     * @param  extendedParams  Map of String, value for extendedParams.
     * @param  authorization  AuthorizationModel value for authorization.
     * @param  shopper  ShopperData value for shopper.
     * @param  billingAddress  AddressData value for billingAddress.
     * @param  paymentMethod  PaymentMethodModel value for paymentMethod.
     * @param  installments  List of Installment value for installments.
     * @param  links  LinksData value for links.
     */
    public InstallmentPlanCreateResponse(
            LocalDateTime dateCreated,
            PlanStatusEnum status,
            String installmentPlanNumber,
            String refOrderNumber,
            PurchaseMethodEnum purchaseMethod,
            String currency,
            Double originalAmount,
            Double amount,
            Map<String, String> extendedParams,
            AuthorizationModel authorization,
            ShopperData shopper,
            AddressData billingAddress,
            PaymentMethodModel paymentMethod,
            List<Installment> installments,
            LinksData links) {
        this.installmentPlanNumber = installmentPlanNumber;
        this.dateCreated = dateCreated;
        this.refOrderNumber = refOrderNumber;
        this.purchaseMethod = purchaseMethod;
        this.status = status;
        this.currency = currency;
        this.originalAmount = originalAmount;
        this.amount = amount;
        this.extendedParams = extendedParams;
        this.authorization = authorization;
        this.shopper = shopper;
        this.billingAddress = billingAddress;
        this.paymentMethod = paymentMethod;
        this.installments = installments;
        this.links = links;
    }

    /**
     * Getter for InstallmentPlanNumber.
     * @return Returns the String
     */
    @JsonGetter("InstallmentPlanNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getInstallmentPlanNumber() {
        return installmentPlanNumber;
    }

    /**
     * Setter for InstallmentPlanNumber.
     * @param installmentPlanNumber Value for String
     */
    @JsonSetter("InstallmentPlanNumber")
    public void setInstallmentPlanNumber(String installmentPlanNumber) {
        this.installmentPlanNumber = installmentPlanNumber;
    }

    /**
     * Getter for DateCreated.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("DateCreated")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getDateCreated() {
        return dateCreated;
    }

    /**
     * Setter for DateCreated.
     * @param dateCreated Value for LocalDateTime
     */
    @JsonSetter("DateCreated")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setDateCreated(LocalDateTime dateCreated) {
        this.dateCreated = dateCreated;
    }

    /**
     * Getter for RefOrderNumber.
     * @return Returns the String
     */
    @JsonGetter("RefOrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRefOrderNumber() {
        return refOrderNumber;
    }

    /**
     * Setter for RefOrderNumber.
     * @param refOrderNumber Value for String
     */
    @JsonSetter("RefOrderNumber")
    public void setRefOrderNumber(String refOrderNumber) {
        this.refOrderNumber = refOrderNumber;
    }

    /**
     * Getter for PurchaseMethod.
     * @return Returns the PurchaseMethodEnum
     */
    @JsonGetter("PurchaseMethod")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PurchaseMethodEnum getPurchaseMethod() {
        return purchaseMethod;
    }

    /**
     * Setter for PurchaseMethod.
     * @param purchaseMethod Value for PurchaseMethodEnum
     */
    @JsonSetter("PurchaseMethod")
    public void setPurchaseMethod(PurchaseMethodEnum purchaseMethod) {
        this.purchaseMethod = purchaseMethod;
    }

    /**
     * Getter for Status.
     * @return Returns the PlanStatusEnum
     */
    @JsonGetter("Status")
    public PlanStatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for PlanStatusEnum
     */
    @JsonSetter("Status")
    public void setStatus(PlanStatusEnum status) {
        this.status = status;
    }

    /**
     * Getter for Currency.
     * @return Returns the String
     */
    @JsonGetter("Currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCurrency() {
        return currency;
    }

    /**
     * Setter for Currency.
     * @param currency Value for String
     */
    @JsonSetter("Currency")
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Getter for OriginalAmount.
     * @return Returns the Double
     */
    @JsonGetter("OriginalAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getOriginalAmount() {
        return originalAmount;
    }

    /**
     * Setter for OriginalAmount.
     * @param originalAmount Value for Double
     */
    @JsonSetter("OriginalAmount")
    public void setOriginalAmount(Double originalAmount) {
        this.originalAmount = originalAmount;
    }

    /**
     * Getter for Amount.
     * @return Returns the Double
     */
    @JsonGetter("Amount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getAmount() {
        return amount;
    }

    /**
     * Setter for Amount.
     * @param amount Value for Double
     */
    @JsonSetter("Amount")
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * Getter for ExtendedParams.
     * @return Returns the Map of String, String
     */
    @JsonGetter("ExtendedParams")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, String> getExtendedParams() {
        return extendedParams;
    }

    /**
     * Setter for ExtendedParams.
     * @param extendedParams Value for Map of String, String
     */
    @JsonSetter("ExtendedParams")
    public void setExtendedParams(Map<String, String> extendedParams) {
        this.extendedParams = extendedParams;
    }

    /**
     * Getter for Authorization.
     * @return Returns the AuthorizationModel
     */
    @JsonGetter("Authorization")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AuthorizationModel getAuthorization() {
        return authorization;
    }

    /**
     * Setter for Authorization.
     * @param authorization Value for AuthorizationModel
     */
    @JsonSetter("Authorization")
    public void setAuthorization(AuthorizationModel authorization) {
        this.authorization = authorization;
    }

    /**
     * Getter for Shopper.
     * @return Returns the ShopperData
     */
    @JsonGetter("Shopper")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShopperData getShopper() {
        return shopper;
    }

    /**
     * Setter for Shopper.
     * @param shopper Value for ShopperData
     */
    @JsonSetter("Shopper")
    public void setShopper(ShopperData shopper) {
        this.shopper = shopper;
    }

    /**
     * Getter for BillingAddress.
     * @return Returns the AddressData
     */
    @JsonGetter("BillingAddress")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AddressData getBillingAddress() {
        return billingAddress;
    }

    /**
     * Setter for BillingAddress.
     * @param billingAddress Value for AddressData
     */
    @JsonSetter("BillingAddress")
    public void setBillingAddress(AddressData billingAddress) {
        this.billingAddress = billingAddress;
    }

    /**
     * Getter for PaymentMethod.
     * @return Returns the PaymentMethodModel
     */
    @JsonGetter("PaymentMethod")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PaymentMethodModel getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Setter for PaymentMethod.
     * @param paymentMethod Value for PaymentMethodModel
     */
    @JsonSetter("PaymentMethod")
    public void setPaymentMethod(PaymentMethodModel paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    /**
     * Getter for Installments.
     * @return Returns the List of Installment
     */
    @JsonGetter("Installments")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Installment> getInstallments() {
        return installments;
    }

    /**
     * Setter for Installments.
     * @param installments Value for List of Installment
     */
    @JsonSetter("Installments")
    public void setInstallments(List<Installment> installments) {
        this.installments = installments;
    }

    /**
     * Getter for Links.
     * @return Returns the LinksData
     */
    @JsonGetter("Links")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public LinksData getLinks() {
        return links;
    }

    /**
     * Setter for Links.
     * @param links Value for LinksData
     */
    @JsonSetter("Links")
    public void setLinks(LinksData links) {
        this.links = links;
    }

    /**
     * Converts this InstallmentPlanCreateResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InstallmentPlanCreateResponse [" + "dateCreated=" + dateCreated + ", status="
                + status + ", installmentPlanNumber=" + installmentPlanNumber + ", refOrderNumber="
                + refOrderNumber + ", purchaseMethod=" + purchaseMethod + ", currency=" + currency
                + ", originalAmount=" + originalAmount + ", amount=" + amount + ", extendedParams="
                + extendedParams + ", authorization=" + authorization + ", shopper=" + shopper
                + ", billingAddress=" + billingAddress + ", paymentMethod=" + paymentMethod
                + ", installments=" + installments + ", links=" + links + "]";
    }

    /**
     * Builds a new {@link InstallmentPlanCreateResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InstallmentPlanCreateResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(dateCreated, status)
                .installmentPlanNumber(getInstallmentPlanNumber())
                .refOrderNumber(getRefOrderNumber())
                .purchaseMethod(getPurchaseMethod())
                .currency(getCurrency())
                .originalAmount(getOriginalAmount())
                .amount(getAmount())
                .extendedParams(getExtendedParams())
                .authorization(getAuthorization())
                .shopper(getShopper())
                .billingAddress(getBillingAddress())
                .paymentMethod(getPaymentMethod())
                .installments(getInstallments())
                .links(getLinks());
        return builder;
    }

    /**
     * Class to build instances of {@link InstallmentPlanCreateResponse}.
     */
    public static class Builder {
        private LocalDateTime dateCreated;
        private PlanStatusEnum status;
        private String installmentPlanNumber;
        private String refOrderNumber;
        private PurchaseMethodEnum purchaseMethod;
        private String currency;
        private Double originalAmount;
        private Double amount;
        private Map<String, String> extendedParams;
        private AuthorizationModel authorization;
        private ShopperData shopper;
        private AddressData billingAddress;
        private PaymentMethodModel paymentMethod;
        private List<Installment> installments;
        private LinksData links;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  dateCreated  LocalDateTime value for dateCreated.
         * @param  status  PlanStatusEnum value for status.
         */
        public Builder(LocalDateTime dateCreated, PlanStatusEnum status) {
            this.dateCreated = dateCreated;
            this.status = status;
        }

        /**
         * Setter for dateCreated.
         * @param  dateCreated  LocalDateTime value for dateCreated.
         * @return Builder
         */
        public Builder dateCreated(LocalDateTime dateCreated) {
            this.dateCreated = dateCreated;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  PlanStatusEnum value for status.
         * @return Builder
         */
        public Builder status(PlanStatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for installmentPlanNumber.
         * @param  installmentPlanNumber  String value for installmentPlanNumber.
         * @return Builder
         */
        public Builder installmentPlanNumber(String installmentPlanNumber) {
            this.installmentPlanNumber = installmentPlanNumber;
            return this;
        }

        /**
         * Setter for refOrderNumber.
         * @param  refOrderNumber  String value for refOrderNumber.
         * @return Builder
         */
        public Builder refOrderNumber(String refOrderNumber) {
            this.refOrderNumber = refOrderNumber;
            return this;
        }

        /**
         * Setter for purchaseMethod.
         * @param  purchaseMethod  PurchaseMethodEnum value for purchaseMethod.
         * @return Builder
         */
        public Builder purchaseMethod(PurchaseMethodEnum purchaseMethod) {
            this.purchaseMethod = purchaseMethod;
            return this;
        }

        /**
         * Setter for currency.
         * @param  currency  String value for currency.
         * @return Builder
         */
        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * Setter for originalAmount.
         * @param  originalAmount  Double value for originalAmount.
         * @return Builder
         */
        public Builder originalAmount(Double originalAmount) {
            this.originalAmount = originalAmount;
            return this;
        }

        /**
         * Setter for amount.
         * @param  amount  Double value for amount.
         * @return Builder
         */
        public Builder amount(Double amount) {
            this.amount = amount;
            return this;
        }

        /**
         * Setter for extendedParams.
         * @param  extendedParams  Map of String, value for extendedParams.
         * @return Builder
         */
        public Builder extendedParams(Map<String, String> extendedParams) {
            this.extendedParams = extendedParams;
            return this;
        }

        /**
         * Setter for authorization.
         * @param  authorization  AuthorizationModel value for authorization.
         * @return Builder
         */
        public Builder authorization(AuthorizationModel authorization) {
            this.authorization = authorization;
            return this;
        }

        /**
         * Setter for shopper.
         * @param  shopper  ShopperData value for shopper.
         * @return Builder
         */
        public Builder shopper(ShopperData shopper) {
            this.shopper = shopper;
            return this;
        }

        /**
         * Setter for billingAddress.
         * @param  billingAddress  AddressData value for billingAddress.
         * @return Builder
         */
        public Builder billingAddress(AddressData billingAddress) {
            this.billingAddress = billingAddress;
            return this;
        }

        /**
         * Setter for paymentMethod.
         * @param  paymentMethod  PaymentMethodModel value for paymentMethod.
         * @return Builder
         */
        public Builder paymentMethod(PaymentMethodModel paymentMethod) {
            this.paymentMethod = paymentMethod;
            return this;
        }

        /**
         * Setter for installments.
         * @param  installments  List of Installment value for installments.
         * @return Builder
         */
        public Builder installments(List<Installment> installments) {
            this.installments = installments;
            return this;
        }

        /**
         * Setter for links.
         * @param  links  LinksData value for links.
         * @return Builder
         */
        public Builder links(LinksData links) {
            this.links = links;
            return this;
        }

        /**
         * Builds a new {@link InstallmentPlanCreateResponse} object using the set fields.
         * @return {@link InstallmentPlanCreateResponse}
         */
        public InstallmentPlanCreateResponse build() {
            return new InstallmentPlanCreateResponse(dateCreated, status, installmentPlanNumber,
                    refOrderNumber, purchaseMethod, currency, originalAmount, amount,
                    extendedParams, authorization, shopper, billingAddress, paymentMethod,
                    installments, links);
        }
    }
}
