/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for InstallmentsEligibilityResponse type.
 */
public class InstallmentsEligibilityResponse {
    private String installmentProvider;
    private List<PaymentPlanOptionModel> paymentPlanOptions;

    /**
     * Default constructor.
     */
    public InstallmentsEligibilityResponse() {
    }

    /**
     * Initialization constructor.
     * @param  installmentProvider  String value for installmentProvider.
     * @param  paymentPlanOptions  List of PaymentPlanOptionModel value for paymentPlanOptions.
     */
    public InstallmentsEligibilityResponse(
            String installmentProvider,
            List<PaymentPlanOptionModel> paymentPlanOptions) {
        this.installmentProvider = installmentProvider;
        this.paymentPlanOptions = paymentPlanOptions;
    }

    /**
     * Getter for InstallmentProvider.
     * @return Returns the String
     */
    @JsonGetter("InstallmentProvider")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getInstallmentProvider() {
        return installmentProvider;
    }

    /**
     * Setter for InstallmentProvider.
     * @param installmentProvider Value for String
     */
    @JsonSetter("InstallmentProvider")
    public void setInstallmentProvider(String installmentProvider) {
        this.installmentProvider = installmentProvider;
    }

    /**
     * Getter for PaymentPlanOptions.
     * @return Returns the List of PaymentPlanOptionModel
     */
    @JsonGetter("PaymentPlanOptions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<PaymentPlanOptionModel> getPaymentPlanOptions() {
        return paymentPlanOptions;
    }

    /**
     * Setter for PaymentPlanOptions.
     * @param paymentPlanOptions Value for List of PaymentPlanOptionModel
     */
    @JsonSetter("PaymentPlanOptions")
    public void setPaymentPlanOptions(List<PaymentPlanOptionModel> paymentPlanOptions) {
        this.paymentPlanOptions = paymentPlanOptions;
    }

    /**
     * Converts this InstallmentsEligibilityResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InstallmentsEligibilityResponse [" + "installmentProvider=" + installmentProvider
                + ", paymentPlanOptions=" + paymentPlanOptions + "]";
    }

    /**
     * Builds a new {@link InstallmentsEligibilityResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InstallmentsEligibilityResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .installmentProvider(getInstallmentProvider())
                .paymentPlanOptions(getPaymentPlanOptions());
        return builder;
    }

    /**
     * Class to build instances of {@link InstallmentsEligibilityResponse}.
     */
    public static class Builder {
        private String installmentProvider;
        private List<PaymentPlanOptionModel> paymentPlanOptions;



        /**
         * Setter for installmentProvider.
         * @param  installmentProvider  String value for installmentProvider.
         * @return Builder
         */
        public Builder installmentProvider(String installmentProvider) {
            this.installmentProvider = installmentProvider;
            return this;
        }

        /**
         * Setter for paymentPlanOptions.
         * @param  paymentPlanOptions  List of PaymentPlanOptionModel value for paymentPlanOptions.
         * @return Builder
         */
        public Builder paymentPlanOptions(List<PaymentPlanOptionModel> paymentPlanOptions) {
            this.paymentPlanOptions = paymentPlanOptions;
            return this;
        }

        /**
         * Builds a new {@link InstallmentsEligibilityResponse} object using the set fields.
         * @return {@link InstallmentsEligibilityResponse}
         */
        public InstallmentsEligibilityResponse build() {
            return new InstallmentsEligibilityResponse(installmentProvider, paymentPlanOptions);
        }
    }
}
