/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for InstallmentPlanUpdateRequest type.
 */
public class InstallmentPlanUpdateRequest {
    private String refOrderNumber;
    private String trackingNumber;
    private Boolean capture;
    private ShippingStatusEnum shippingStatus;
    private String newAmount;

    /**
     * Default constructor.
     */
    public InstallmentPlanUpdateRequest() {
    }

    /**
     * Initialization constructor.
     * @param  refOrderNumber  String value for refOrderNumber.
     * @param  trackingNumber  String value for trackingNumber.
     * @param  capture  Boolean value for capture.
     * @param  shippingStatus  ShippingStatusEnum value for shippingStatus.
     * @param  newAmount  String value for newAmount.
     */
    public InstallmentPlanUpdateRequest(
            String refOrderNumber,
            String trackingNumber,
            Boolean capture,
            ShippingStatusEnum shippingStatus,
            String newAmount) {
        this.refOrderNumber = refOrderNumber;
        this.trackingNumber = trackingNumber;
        this.capture = capture;
        this.shippingStatus = shippingStatus;
        this.newAmount = newAmount;
    }

    /**
     * Getter for RefOrderNumber.
     * @return Returns the String
     */
    @JsonGetter("RefOrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRefOrderNumber() {
        return refOrderNumber;
    }

    /**
     * Setter for RefOrderNumber.
     * @param refOrderNumber Value for String
     */
    @JsonSetter("RefOrderNumber")
    public void setRefOrderNumber(String refOrderNumber) {
        this.refOrderNumber = refOrderNumber;
    }

    /**
     * Getter for TrackingNumber.
     * @return Returns the String
     */
    @JsonGetter("TrackingNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTrackingNumber() {
        return trackingNumber;
    }

    /**
     * Setter for TrackingNumber.
     * @param trackingNumber Value for String
     */
    @JsonSetter("TrackingNumber")
    public void setTrackingNumber(String trackingNumber) {
        this.trackingNumber = trackingNumber;
    }

    /**
     * Getter for Capture.
     * @return Returns the Boolean
     */
    @JsonGetter("Capture")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getCapture() {
        return capture;
    }

    /**
     * Setter for Capture.
     * @param capture Value for Boolean
     */
    @JsonSetter("Capture")
    public void setCapture(Boolean capture) {
        this.capture = capture;
    }

    /**
     * Getter for ShippingStatus.
     * @return Returns the ShippingStatusEnum
     */
    @JsonGetter("ShippingStatus")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ShippingStatusEnum getShippingStatus() {
        return shippingStatus;
    }

    /**
     * Setter for ShippingStatus.
     * @param shippingStatus Value for ShippingStatusEnum
     */
    @JsonSetter("ShippingStatus")
    public void setShippingStatus(ShippingStatusEnum shippingStatus) {
        this.shippingStatus = shippingStatus;
    }

    /**
     * Getter for NewAmount.
     * @return Returns the String
     */
    @JsonGetter("NewAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNewAmount() {
        return newAmount;
    }

    /**
     * Setter for NewAmount.
     * @param newAmount Value for String
     */
    @JsonSetter("NewAmount")
    public void setNewAmount(String newAmount) {
        this.newAmount = newAmount;
    }

    /**
     * Converts this InstallmentPlanUpdateRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "InstallmentPlanUpdateRequest [" + "refOrderNumber=" + refOrderNumber
                + ", trackingNumber=" + trackingNumber + ", capture=" + capture
                + ", shippingStatus=" + shippingStatus + ", newAmount=" + newAmount + "]";
    }

    /**
     * Builds a new {@link InstallmentPlanUpdateRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link InstallmentPlanUpdateRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .refOrderNumber(getRefOrderNumber())
                .trackingNumber(getTrackingNumber())
                .capture(getCapture())
                .shippingStatus(getShippingStatus())
                .newAmount(getNewAmount());
        return builder;
    }

    /**
     * Class to build instances of {@link InstallmentPlanUpdateRequest}.
     */
    public static class Builder {
        private String refOrderNumber;
        private String trackingNumber;
        private Boolean capture;
        private ShippingStatusEnum shippingStatus;
        private String newAmount;



        /**
         * Setter for refOrderNumber.
         * @param  refOrderNumber  String value for refOrderNumber.
         * @return Builder
         */
        public Builder refOrderNumber(String refOrderNumber) {
            this.refOrderNumber = refOrderNumber;
            return this;
        }

        /**
         * Setter for trackingNumber.
         * @param  trackingNumber  String value for trackingNumber.
         * @return Builder
         */
        public Builder trackingNumber(String trackingNumber) {
            this.trackingNumber = trackingNumber;
            return this;
        }

        /**
         * Setter for capture.
         * @param  capture  Boolean value for capture.
         * @return Builder
         */
        public Builder capture(Boolean capture) {
            this.capture = capture;
            return this;
        }

        /**
         * Setter for shippingStatus.
         * @param  shippingStatus  ShippingStatusEnum value for shippingStatus.
         * @return Builder
         */
        public Builder shippingStatus(ShippingStatusEnum shippingStatus) {
            this.shippingStatus = shippingStatus;
            return this;
        }

        /**
         * Setter for newAmount.
         * @param  newAmount  String value for newAmount.
         * @return Builder
         */
        public Builder newAmount(String newAmount) {
            this.newAmount = newAmount;
            return this;
        }

        /**
         * Builds a new {@link InstallmentPlanUpdateRequest} object using the set fields.
         * @return {@link InstallmentPlanUpdateRequest}
         */
        public InstallmentPlanUpdateRequest build() {
            return new InstallmentPlanUpdateRequest(refOrderNumber, trackingNumber, capture,
                    shippingStatus, newAmount);
        }
    }
}
