/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for LinksModel type.
 */
public class LinksModel {
    private String privacyPolicyUrl;
    private String termsAndConditionsUrl;
    private String learnMoreUrl;

    /**
     * Default constructor.
     */
    public LinksModel() {
    }

    /**
     * Initialization constructor.
     * @param  privacyPolicyUrl  String value for privacyPolicyUrl.
     * @param  termsAndConditionsUrl  String value for termsAndConditionsUrl.
     * @param  learnMoreUrl  String value for learnMoreUrl.
     */
    public LinksModel(
            String privacyPolicyUrl,
            String termsAndConditionsUrl,
            String learnMoreUrl) {
        this.privacyPolicyUrl = privacyPolicyUrl;
        this.termsAndConditionsUrl = termsAndConditionsUrl;
        this.learnMoreUrl = learnMoreUrl;
    }

    /**
     * Getter for PrivacyPolicyUrl.
     * @return Returns the String
     */
    @JsonGetter("PrivacyPolicyUrl")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPrivacyPolicyUrl() {
        return privacyPolicyUrl;
    }

    /**
     * Setter for PrivacyPolicyUrl.
     * @param privacyPolicyUrl Value for String
     */
    @JsonSetter("PrivacyPolicyUrl")
    public void setPrivacyPolicyUrl(String privacyPolicyUrl) {
        this.privacyPolicyUrl = privacyPolicyUrl;
    }

    /**
     * Getter for TermsAndConditionsUrl.
     * @return Returns the String
     */
    @JsonGetter("TermsAndConditionsUrl")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTermsAndConditionsUrl() {
        return termsAndConditionsUrl;
    }

    /**
     * Setter for TermsAndConditionsUrl.
     * @param termsAndConditionsUrl Value for String
     */
    @JsonSetter("TermsAndConditionsUrl")
    public void setTermsAndConditionsUrl(String termsAndConditionsUrl) {
        this.termsAndConditionsUrl = termsAndConditionsUrl;
    }

    /**
     * Getter for LearnMoreUrl.
     * @return Returns the String
     */
    @JsonGetter("LearnMoreUrl")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLearnMoreUrl() {
        return learnMoreUrl;
    }

    /**
     * Setter for LearnMoreUrl.
     * @param learnMoreUrl Value for String
     */
    @JsonSetter("LearnMoreUrl")
    public void setLearnMoreUrl(String learnMoreUrl) {
        this.learnMoreUrl = learnMoreUrl;
    }

    /**
     * Converts this LinksModel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LinksModel [" + "privacyPolicyUrl=" + privacyPolicyUrl + ", termsAndConditionsUrl="
                + termsAndConditionsUrl + ", learnMoreUrl=" + learnMoreUrl + "]";
    }

    /**
     * Builds a new {@link LinksModel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LinksModel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .privacyPolicyUrl(getPrivacyPolicyUrl())
                .termsAndConditionsUrl(getTermsAndConditionsUrl())
                .learnMoreUrl(getLearnMoreUrl());
        return builder;
    }

    /**
     * Class to build instances of {@link LinksModel}.
     */
    public static class Builder {
        private String privacyPolicyUrl;
        private String termsAndConditionsUrl;
        private String learnMoreUrl;



        /**
         * Setter for privacyPolicyUrl.
         * @param  privacyPolicyUrl  String value for privacyPolicyUrl.
         * @return Builder
         */
        public Builder privacyPolicyUrl(String privacyPolicyUrl) {
            this.privacyPolicyUrl = privacyPolicyUrl;
            return this;
        }

        /**
         * Setter for termsAndConditionsUrl.
         * @param  termsAndConditionsUrl  String value for termsAndConditionsUrl.
         * @return Builder
         */
        public Builder termsAndConditionsUrl(String termsAndConditionsUrl) {
            this.termsAndConditionsUrl = termsAndConditionsUrl;
            return this;
        }

        /**
         * Setter for learnMoreUrl.
         * @param  learnMoreUrl  String value for learnMoreUrl.
         * @return Builder
         */
        public Builder learnMoreUrl(String learnMoreUrl) {
            this.learnMoreUrl = learnMoreUrl;
            return this;
        }

        /**
         * Builds a new {@link LinksModel} object using the set fields.
         * @return {@link LinksModel}
         */
        public LinksModel build() {
            return new LinksModel(privacyPolicyUrl, termsAndConditionsUrl, learnMoreUrl);
        }
    }
}
