/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for LinksData type.
 */
public class LinksData {
    private String checkout;
    private String learnMore;
    private String termsConditions;
    private String privacyPolicy;

    /**
     * Default constructor.
     */
    public LinksData() {
    }

    /**
     * Initialization constructor.
     * @param  checkout  String value for checkout.
     * @param  learnMore  String value for learnMore.
     * @param  termsConditions  String value for termsConditions.
     * @param  privacyPolicy  String value for privacyPolicy.
     */
    public LinksData(
            String checkout,
            String learnMore,
            String termsConditions,
            String privacyPolicy) {
        this.checkout = checkout;
        this.learnMore = learnMore;
        this.termsConditions = termsConditions;
        this.privacyPolicy = privacyPolicy;
    }

    /**
     * Getter for Checkout.
     * @return Returns the String
     */
    @JsonGetter("Checkout")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCheckout() {
        return checkout;
    }

    /**
     * Setter for Checkout.
     * @param checkout Value for String
     */
    @JsonSetter("Checkout")
    public void setCheckout(String checkout) {
        this.checkout = checkout;
    }

    /**
     * Getter for LearnMore.
     * @return Returns the String
     */
    @JsonGetter("LearnMore")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLearnMore() {
        return learnMore;
    }

    /**
     * Setter for LearnMore.
     * @param learnMore Value for String
     */
    @JsonSetter("LearnMore")
    public void setLearnMore(String learnMore) {
        this.learnMore = learnMore;
    }

    /**
     * Getter for TermsConditions.
     * @return Returns the String
     */
    @JsonGetter("TermsConditions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTermsConditions() {
        return termsConditions;
    }

    /**
     * Setter for TermsConditions.
     * @param termsConditions Value for String
     */
    @JsonSetter("TermsConditions")
    public void setTermsConditions(String termsConditions) {
        this.termsConditions = termsConditions;
    }

    /**
     * Getter for PrivacyPolicy.
     * @return Returns the String
     */
    @JsonGetter("PrivacyPolicy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPrivacyPolicy() {
        return privacyPolicy;
    }

    /**
     * Setter for PrivacyPolicy.
     * @param privacyPolicy Value for String
     */
    @JsonSetter("PrivacyPolicy")
    public void setPrivacyPolicy(String privacyPolicy) {
        this.privacyPolicy = privacyPolicy;
    }

    /**
     * Converts this LinksData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "LinksData [" + "checkout=" + checkout + ", learnMore=" + learnMore
                + ", termsConditions=" + termsConditions + ", privacyPolicy=" + privacyPolicy + "]";
    }

    /**
     * Builds a new {@link LinksData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link LinksData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .checkout(getCheckout())
                .learnMore(getLearnMore())
                .termsConditions(getTermsConditions())
                .privacyPolicy(getPrivacyPolicy());
        return builder;
    }

    /**
     * Class to build instances of {@link LinksData}.
     */
    public static class Builder {
        private String checkout;
        private String learnMore;
        private String termsConditions;
        private String privacyPolicy;



        /**
         * Setter for checkout.
         * @param  checkout  String value for checkout.
         * @return Builder
         */
        public Builder checkout(String checkout) {
            this.checkout = checkout;
            return this;
        }

        /**
         * Setter for learnMore.
         * @param  learnMore  String value for learnMore.
         * @return Builder
         */
        public Builder learnMore(String learnMore) {
            this.learnMore = learnMore;
            return this;
        }

        /**
         * Setter for termsConditions.
         * @param  termsConditions  String value for termsConditions.
         * @return Builder
         */
        public Builder termsConditions(String termsConditions) {
            this.termsConditions = termsConditions;
            return this;
        }

        /**
         * Setter for privacyPolicy.
         * @param  privacyPolicy  String value for privacyPolicy.
         * @return Builder
         */
        public Builder privacyPolicy(String privacyPolicy) {
            this.privacyPolicy = privacyPolicy;
            return this;
        }

        /**
         * Builds a new {@link LinksData} object using the set fields.
         * @return {@link LinksData}
         */
        public LinksData build() {
            return new LinksData(checkout, learnMore, termsConditions, privacyPolicy);
        }
    }
}
