/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PaymentInfo type.
 */
public class PaymentInfo {
    private String cardBin;
    private CardTypeEnum cardType;

    /**
     * Default constructor.
     */
    public PaymentInfo() {
    }

    /**
     * Initialization constructor.
     * @param  cardBin  String value for cardBin.
     * @param  cardType  CardTypeEnum value for cardType.
     */
    public PaymentInfo(
            String cardBin,
            CardTypeEnum cardType) {
        this.cardBin = cardBin;
        this.cardType = cardType;
    }

    /**
     * Getter for CardBin.
     * @return Returns the String
     */
    @JsonGetter("CardBin")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardBin() {
        return cardBin;
    }

    /**
     * Setter for CardBin.
     * @param cardBin Value for String
     */
    @JsonSetter("CardBin")
    public void setCardBin(String cardBin) {
        this.cardBin = cardBin;
    }

    /**
     * Getter for CardType.
     * @return Returns the CardTypeEnum
     */
    @JsonGetter("CardType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardTypeEnum getCardType() {
        return cardType;
    }

    /**
     * Setter for CardType.
     * @param cardType Value for CardTypeEnum
     */
    @JsonSetter("CardType")
    public void setCardType(CardTypeEnum cardType) {
        this.cardType = cardType;
    }

    /**
     * Converts this PaymentInfo into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PaymentInfo [" + "cardBin=" + cardBin + ", cardType=" + cardType + "]";
    }

    /**
     * Builds a new {@link PaymentInfo.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PaymentInfo.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .cardBin(getCardBin())
                .cardType(getCardType());
        return builder;
    }

    /**
     * Class to build instances of {@link PaymentInfo}.
     */
    public static class Builder {
        private String cardBin;
        private CardTypeEnum cardType;



        /**
         * Setter for cardBin.
         * @param  cardBin  String value for cardBin.
         * @return Builder
         */
        public Builder cardBin(String cardBin) {
            this.cardBin = cardBin;
            return this;
        }

        /**
         * Setter for cardType.
         * @param  cardType  CardTypeEnum value for cardType.
         * @return Builder
         */
        public Builder cardType(CardTypeEnum cardType) {
            this.cardType = cardType;
            return this;
        }

        /**
         * Builds a new {@link PaymentInfo} object using the set fields.
         * @return {@link PaymentInfo}
         */
        public PaymentInfo build() {
            return new PaymentInfo(cardBin, cardType);
        }
    }
}
