/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * PaymentMethodTypeEnum to be used.
 */
public enum PaymentMethodTypeEnum {
    CARD,

    SPLITITTOKEN,

    BLUESNAPVAULTEDSHOPPERTOKEN,

    SPLITITMOCKERV2TOKEN,

    SPREEDLYTOKEN;


    private static TreeMap<String, PaymentMethodTypeEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        CARD.value = "Card";
        SPLITITTOKEN.value = "SplititToken";
        BLUESNAPVAULTEDSHOPPERTOKEN.value = "BluesnapVaultedShopperToken";
        SPLITITMOCKERV2TOKEN.value = "SplititMockerV2Token";
        SPREEDLYTOKEN.value = "SpreedlyToken";

        valueMap.put("Card", CARD);
        valueMap.put("SplititToken", SPLITITTOKEN);
        valueMap.put("BluesnapVaultedShopperToken", BLUESNAPVAULTEDSHOPPERTOKEN);
        valueMap.put("SplititMockerV2Token", SPLITITMOCKERV2TOKEN);
        valueMap.put("SpreedlyToken", SPREEDLYTOKEN);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static PaymentMethodTypeEnum constructFromString(String toConvert) throws IOException {
        PaymentMethodTypeEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static PaymentMethodTypeEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PaymentMethodTypeEnum values to list of string values.
     * @param toConvert The list of PaymentMethodTypeEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PaymentMethodTypeEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PaymentMethodTypeEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 