/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PaymentPlanOptionModel type.
 */
public class PaymentPlanOptionModel {
    private int numberOfInstallments;
    private double firstInstallmentAmount;
    private double installmentAmount;
    private double lastInstallmentAmount;
    private LinksModel links;
    private String termsAndConditionsBrief;
    private String installmentFrequency;

    /**
     * Default constructor.
     */
    public PaymentPlanOptionModel() {
    }

    /**
     * Initialization constructor.
     * @param  numberOfInstallments  int value for numberOfInstallments.
     * @param  firstInstallmentAmount  double value for firstInstallmentAmount.
     * @param  installmentAmount  double value for installmentAmount.
     * @param  lastInstallmentAmount  double value for lastInstallmentAmount.
     * @param  links  LinksModel value for links.
     * @param  termsAndConditionsBrief  String value for termsAndConditionsBrief.
     * @param  installmentFrequency  String value for installmentFrequency.
     */
    public PaymentPlanOptionModel(
            int numberOfInstallments,
            double firstInstallmentAmount,
            double installmentAmount,
            double lastInstallmentAmount,
            LinksModel links,
            String termsAndConditionsBrief,
            String installmentFrequency) {
        this.numberOfInstallments = numberOfInstallments;
        this.firstInstallmentAmount = firstInstallmentAmount;
        this.installmentAmount = installmentAmount;
        this.lastInstallmentAmount = lastInstallmentAmount;
        this.links = links;
        this.termsAndConditionsBrief = termsAndConditionsBrief;
        this.installmentFrequency = installmentFrequency;
    }

    /**
     * Getter for NumberOfInstallments.
     * @return Returns the int
     */
    @JsonGetter("NumberOfInstallments")
    public int getNumberOfInstallments() {
        return numberOfInstallments;
    }

    /**
     * Setter for NumberOfInstallments.
     * @param numberOfInstallments Value for int
     */
    @JsonSetter("NumberOfInstallments")
    public void setNumberOfInstallments(int numberOfInstallments) {
        this.numberOfInstallments = numberOfInstallments;
    }

    /**
     * Getter for FirstInstallmentAmount.
     * @return Returns the double
     */
    @JsonGetter("FirstInstallmentAmount")
    public double getFirstInstallmentAmount() {
        return firstInstallmentAmount;
    }

    /**
     * Setter for FirstInstallmentAmount.
     * @param firstInstallmentAmount Value for double
     */
    @JsonSetter("FirstInstallmentAmount")
    public void setFirstInstallmentAmount(double firstInstallmentAmount) {
        this.firstInstallmentAmount = firstInstallmentAmount;
    }

    /**
     * Getter for InstallmentAmount.
     * @return Returns the double
     */
    @JsonGetter("InstallmentAmount")
    public double getInstallmentAmount() {
        return installmentAmount;
    }

    /**
     * Setter for InstallmentAmount.
     * @param installmentAmount Value for double
     */
    @JsonSetter("InstallmentAmount")
    public void setInstallmentAmount(double installmentAmount) {
        this.installmentAmount = installmentAmount;
    }

    /**
     * Getter for LastInstallmentAmount.
     * @return Returns the double
     */
    @JsonGetter("LastInstallmentAmount")
    public double getLastInstallmentAmount() {
        return lastInstallmentAmount;
    }

    /**
     * Setter for LastInstallmentAmount.
     * @param lastInstallmentAmount Value for double
     */
    @JsonSetter("LastInstallmentAmount")
    public void setLastInstallmentAmount(double lastInstallmentAmount) {
        this.lastInstallmentAmount = lastInstallmentAmount;
    }

    /**
     * Getter for Links.
     * @return Returns the LinksModel
     */
    @JsonGetter("Links")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public LinksModel getLinks() {
        return links;
    }

    /**
     * Setter for Links.
     * @param links Value for LinksModel
     */
    @JsonSetter("Links")
    public void setLinks(LinksModel links) {
        this.links = links;
    }

    /**
     * Getter for TermsAndConditionsBrief.
     * @return Returns the String
     */
    @JsonGetter("TermsAndConditionsBrief")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTermsAndConditionsBrief() {
        return termsAndConditionsBrief;
    }

    /**
     * Setter for TermsAndConditionsBrief.
     * @param termsAndConditionsBrief Value for String
     */
    @JsonSetter("TermsAndConditionsBrief")
    public void setTermsAndConditionsBrief(String termsAndConditionsBrief) {
        this.termsAndConditionsBrief = termsAndConditionsBrief;
    }

    /**
     * Getter for InstallmentFrequency.
     * @return Returns the String
     */
    @JsonGetter("InstallmentFrequency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getInstallmentFrequency() {
        return installmentFrequency;
    }

    /**
     * Setter for InstallmentFrequency.
     * @param installmentFrequency Value for String
     */
    @JsonSetter("InstallmentFrequency")
    public void setInstallmentFrequency(String installmentFrequency) {
        this.installmentFrequency = installmentFrequency;
    }

    /**
     * Converts this PaymentPlanOptionModel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PaymentPlanOptionModel [" + "numberOfInstallments=" + numberOfInstallments
                + ", firstInstallmentAmount=" + firstInstallmentAmount + ", installmentAmount="
                + installmentAmount + ", lastInstallmentAmount=" + lastInstallmentAmount
                + ", links=" + links + ", termsAndConditionsBrief=" + termsAndConditionsBrief
                + ", installmentFrequency=" + installmentFrequency + "]";
    }

    /**
     * Builds a new {@link PaymentPlanOptionModel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PaymentPlanOptionModel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(numberOfInstallments, firstInstallmentAmount,
                installmentAmount, lastInstallmentAmount)
                .links(getLinks())
                .termsAndConditionsBrief(getTermsAndConditionsBrief())
                .installmentFrequency(getInstallmentFrequency());
        return builder;
    }

    /**
     * Class to build instances of {@link PaymentPlanOptionModel}.
     */
    public static class Builder {
        private int numberOfInstallments;
        private double firstInstallmentAmount;
        private double installmentAmount;
        private double lastInstallmentAmount;
        private LinksModel links;
        private String termsAndConditionsBrief;
        private String installmentFrequency;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  numberOfInstallments  int value for numberOfInstallments.
         * @param  firstInstallmentAmount  double value for firstInstallmentAmount.
         * @param  installmentAmount  double value for installmentAmount.
         * @param  lastInstallmentAmount  double value for lastInstallmentAmount.
         */
        public Builder(int numberOfInstallments, double firstInstallmentAmount,
                double installmentAmount, double lastInstallmentAmount) {
            this.numberOfInstallments = numberOfInstallments;
            this.firstInstallmentAmount = firstInstallmentAmount;
            this.installmentAmount = installmentAmount;
            this.lastInstallmentAmount = lastInstallmentAmount;
        }

        /**
         * Setter for numberOfInstallments.
         * @param  numberOfInstallments  int value for numberOfInstallments.
         * @return Builder
         */
        public Builder numberOfInstallments(int numberOfInstallments) {
            this.numberOfInstallments = numberOfInstallments;
            return this;
        }

        /**
         * Setter for firstInstallmentAmount.
         * @param  firstInstallmentAmount  double value for firstInstallmentAmount.
         * @return Builder
         */
        public Builder firstInstallmentAmount(double firstInstallmentAmount) {
            this.firstInstallmentAmount = firstInstallmentAmount;
            return this;
        }

        /**
         * Setter for installmentAmount.
         * @param  installmentAmount  double value for installmentAmount.
         * @return Builder
         */
        public Builder installmentAmount(double installmentAmount) {
            this.installmentAmount = installmentAmount;
            return this;
        }

        /**
         * Setter for lastInstallmentAmount.
         * @param  lastInstallmentAmount  double value for lastInstallmentAmount.
         * @return Builder
         */
        public Builder lastInstallmentAmount(double lastInstallmentAmount) {
            this.lastInstallmentAmount = lastInstallmentAmount;
            return this;
        }

        /**
         * Setter for links.
         * @param  links  LinksModel value for links.
         * @return Builder
         */
        public Builder links(LinksModel links) {
            this.links = links;
            return this;
        }

        /**
         * Setter for termsAndConditionsBrief.
         * @param  termsAndConditionsBrief  String value for termsAndConditionsBrief.
         * @return Builder
         */
        public Builder termsAndConditionsBrief(String termsAndConditionsBrief) {
            this.termsAndConditionsBrief = termsAndConditionsBrief;
            return this;
        }

        /**
         * Setter for installmentFrequency.
         * @param  installmentFrequency  String value for installmentFrequency.
         * @return Builder
         */
        public Builder installmentFrequency(String installmentFrequency) {
            this.installmentFrequency = installmentFrequency;
            return this;
        }

        /**
         * Builds a new {@link PaymentPlanOptionModel} object using the set fields.
         * @return {@link PaymentPlanOptionModel}
         */
        public PaymentPlanOptionModel build() {
            return new PaymentPlanOptionModel(numberOfInstallments, firstInstallmentAmount,
                    installmentAmount, lastInstallmentAmount, links, termsAndConditionsBrief,
                    installmentFrequency);
        }
    }
}
