/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PaymentMethodModel type.
 */
public class PaymentMethodModel {
    private PaymentMethodTypeEnum type;
    private CardData card;
    private String token;
    private BluesnapVaultedShopperToken bluesnapVaultedShopperToken;
    private MockerShopperToken mockerShopperToken;
    private SpreedlyToken spreedlyToken;
    private String cardPAR;

    /**
     * Default constructor.
     */
    public PaymentMethodModel() {
    }

    /**
     * Initialization constructor.
     * @param  type  PaymentMethodTypeEnum value for type.
     * @param  card  CardData value for card.
     * @param  token  String value for token.
     * @param  bluesnapVaultedShopperToken  BluesnapVaultedShopperToken value for
     *         bluesnapVaultedShopperToken.
     * @param  mockerShopperToken  MockerShopperToken value for mockerShopperToken.
     * @param  spreedlyToken  SpreedlyToken value for spreedlyToken.
     * @param  cardPAR  String value for cardPAR.
     */
    public PaymentMethodModel(
            PaymentMethodTypeEnum type,
            CardData card,
            String token,
            BluesnapVaultedShopperToken bluesnapVaultedShopperToken,
            MockerShopperToken mockerShopperToken,
            SpreedlyToken spreedlyToken,
            String cardPAR) {
        this.type = type;
        this.card = card;
        this.token = token;
        this.bluesnapVaultedShopperToken = bluesnapVaultedShopperToken;
        this.mockerShopperToken = mockerShopperToken;
        this.spreedlyToken = spreedlyToken;
        this.cardPAR = cardPAR;
    }

    /**
     * Getter for Type.
     * @return Returns the PaymentMethodTypeEnum
     */
    @JsonGetter("Type")
    public PaymentMethodTypeEnum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for PaymentMethodTypeEnum
     */
    @JsonSetter("Type")
    public void setType(PaymentMethodTypeEnum type) {
        this.type = type;
    }

    /**
     * Getter for Card.
     * @return Returns the CardData
     */
    @JsonGetter("Card")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CardData getCard() {
        return card;
    }

    /**
     * Setter for Card.
     * @param card Value for CardData
     */
    @JsonSetter("Card")
    public void setCard(CardData card) {
        this.card = card;
    }

    /**
     * Getter for Token.
     * @return Returns the String
     */
    @JsonGetter("Token")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getToken() {
        return token;
    }

    /**
     * Setter for Token.
     * @param token Value for String
     */
    @JsonSetter("Token")
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * Getter for BluesnapVaultedShopperToken.
     * @return Returns the BluesnapVaultedShopperToken
     */
    @JsonGetter("BluesnapVaultedShopperToken")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public BluesnapVaultedShopperToken getBluesnapVaultedShopperToken() {
        return bluesnapVaultedShopperToken;
    }

    /**
     * Setter for BluesnapVaultedShopperToken.
     * @param bluesnapVaultedShopperToken Value for BluesnapVaultedShopperToken
     */
    @JsonSetter("BluesnapVaultedShopperToken")
    public void setBluesnapVaultedShopperToken(BluesnapVaultedShopperToken bluesnapVaultedShopperToken) {
        this.bluesnapVaultedShopperToken = bluesnapVaultedShopperToken;
    }

    /**
     * Getter for MockerShopperToken.
     * @return Returns the MockerShopperToken
     */
    @JsonGetter("MockerShopperToken")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public MockerShopperToken getMockerShopperToken() {
        return mockerShopperToken;
    }

    /**
     * Setter for MockerShopperToken.
     * @param mockerShopperToken Value for MockerShopperToken
     */
    @JsonSetter("MockerShopperToken")
    public void setMockerShopperToken(MockerShopperToken mockerShopperToken) {
        this.mockerShopperToken = mockerShopperToken;
    }

    /**
     * Getter for SpreedlyToken.
     * @return Returns the SpreedlyToken
     */
    @JsonGetter("SpreedlyToken")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public SpreedlyToken getSpreedlyToken() {
        return spreedlyToken;
    }

    /**
     * Setter for SpreedlyToken.
     * @param spreedlyToken Value for SpreedlyToken
     */
    @JsonSetter("SpreedlyToken")
    public void setSpreedlyToken(SpreedlyToken spreedlyToken) {
        this.spreedlyToken = spreedlyToken;
    }

    /**
     * Getter for CardPAR.
     * @return Returns the String
     */
    @JsonGetter("CardPAR")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCardPAR() {
        return cardPAR;
    }

    /**
     * Setter for CardPAR.
     * @param cardPAR Value for String
     */
    @JsonSetter("CardPAR")
    public void setCardPAR(String cardPAR) {
        this.cardPAR = cardPAR;
    }

    /**
     * Converts this PaymentMethodModel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PaymentMethodModel [" + "type=" + type + ", card=" + card + ", token=" + token
                + ", bluesnapVaultedShopperToken=" + bluesnapVaultedShopperToken
                + ", mockerShopperToken=" + mockerShopperToken + ", spreedlyToken=" + spreedlyToken
                + ", cardPAR=" + cardPAR + "]";
    }

    /**
     * Builds a new {@link PaymentMethodModel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PaymentMethodModel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type)
                .card(getCard())
                .token(getToken())
                .bluesnapVaultedShopperToken(getBluesnapVaultedShopperToken())
                .mockerShopperToken(getMockerShopperToken())
                .spreedlyToken(getSpreedlyToken())
                .cardPAR(getCardPAR());
        return builder;
    }

    /**
     * Class to build instances of {@link PaymentMethodModel}.
     */
    public static class Builder {
        private PaymentMethodTypeEnum type;
        private CardData card;
        private String token;
        private BluesnapVaultedShopperToken bluesnapVaultedShopperToken;
        private MockerShopperToken mockerShopperToken;
        private SpreedlyToken spreedlyToken;
        private String cardPAR;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  PaymentMethodTypeEnum value for type.
         */
        public Builder(PaymentMethodTypeEnum type) {
            this.type = type;
        }

        /**
         * Setter for type.
         * @param  type  PaymentMethodTypeEnum value for type.
         * @return Builder
         */
        public Builder type(PaymentMethodTypeEnum type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for card.
         * @param  card  CardData value for card.
         * @return Builder
         */
        public Builder card(CardData card) {
            this.card = card;
            return this;
        }

        /**
         * Setter for token.
         * @param  token  String value for token.
         * @return Builder
         */
        public Builder token(String token) {
            this.token = token;
            return this;
        }

        /**
         * Setter for bluesnapVaultedShopperToken.
         * @param  bluesnapVaultedShopperToken  BluesnapVaultedShopperToken value for
         *         bluesnapVaultedShopperToken.
         * @return Builder
         */
        public Builder bluesnapVaultedShopperToken(
                BluesnapVaultedShopperToken bluesnapVaultedShopperToken) {
            this.bluesnapVaultedShopperToken = bluesnapVaultedShopperToken;
            return this;
        }

        /**
         * Setter for mockerShopperToken.
         * @param  mockerShopperToken  MockerShopperToken value for mockerShopperToken.
         * @return Builder
         */
        public Builder mockerShopperToken(MockerShopperToken mockerShopperToken) {
            this.mockerShopperToken = mockerShopperToken;
            return this;
        }

        /**
         * Setter for spreedlyToken.
         * @param  spreedlyToken  SpreedlyToken value for spreedlyToken.
         * @return Builder
         */
        public Builder spreedlyToken(SpreedlyToken spreedlyToken) {
            this.spreedlyToken = spreedlyToken;
            return this;
        }

        /**
         * Setter for cardPAR.
         * @param  cardPAR  String value for cardPAR.
         * @return Builder
         */
        public Builder cardPAR(String cardPAR) {
            this.cardPAR = cardPAR;
            return this;
        }

        /**
         * Builds a new {@link PaymentMethodModel} object using the set fields.
         * @return {@link PaymentMethodModel}
         */
        public PaymentMethodModel build() {
            return new PaymentMethodModel(type, card, token, bluesnapVaultedShopperToken,
                    mockerShopperToken, spreedlyToken, cardPAR);
        }
    }
}
