/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * PlanStatusEnum to be used.
 */
public enum PlanStatusEnum {
    INITIALIZED,

    PENDINGCAPTURE,

    ACTIVE,

    CLEARED,

    CANCELED;


    private static TreeMap<String, PlanStatusEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        INITIALIZED.value = "Initialized";
        PENDINGCAPTURE.value = "PendingCapture";
        ACTIVE.value = "Active";
        CLEARED.value = "Cleared";
        CANCELED.value = "Canceled";

        valueMap.put("Initialized", INITIALIZED);
        valueMap.put("PendingCapture", PENDINGCAPTURE);
        valueMap.put("Active", ACTIVE);
        valueMap.put("Cleared", CLEARED);
        valueMap.put("Canceled", CANCELED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static PlanStatusEnum constructFromString(String toConvert) throws IOException {
        PlanStatusEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static PlanStatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of PlanStatusEnum values to list of string values.
     * @param toConvert The list of PlanStatusEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<PlanStatusEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (PlanStatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 