/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.splitit.sandbox.webapiv3.DateTimeHelper;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for PlanData type.
 */
public class PlanData {
    private String terminalId;
    private String totalAmount;
    private Double firstInstallmentAmount;
    private String currency;
    private int numberOfInstallments;
    private PurchaseMethodEnum purchaseMethod;
    private String refOrderNumber;
    private List<Integer> allowedInstallmentOptions;
    private Map<String, String> tags;
    private ProcessingData processingData;
    private LocalDateTime firstInstallmentDate;

    /**
     * Default constructor.
     */
    public PlanData() {
    }

    /**
     * Initialization constructor.
     * @param  totalAmount  String value for totalAmount.
     * @param  numberOfInstallments  int value for numberOfInstallments.
     * @param  purchaseMethod  PurchaseMethodEnum value for purchaseMethod.
     * @param  terminalId  String value for terminalId.
     * @param  firstInstallmentAmount  Double value for firstInstallmentAmount.
     * @param  currency  String value for currency.
     * @param  refOrderNumber  String value for refOrderNumber.
     * @param  allowedInstallmentOptions  List of Integer value for allowedInstallmentOptions.
     * @param  tags  Map of String, value for tags.
     * @param  processingData  ProcessingData value for processingData.
     * @param  firstInstallmentDate  LocalDateTime value for firstInstallmentDate.
     */
    public PlanData(
            String totalAmount,
            int numberOfInstallments,
            PurchaseMethodEnum purchaseMethod,
            String terminalId,
            Double firstInstallmentAmount,
            String currency,
            String refOrderNumber,
            List<Integer> allowedInstallmentOptions,
            Map<String, String> tags,
            ProcessingData processingData,
            LocalDateTime firstInstallmentDate) {
        this.terminalId = terminalId;
        this.totalAmount = totalAmount;
        this.firstInstallmentAmount = firstInstallmentAmount;
        this.currency = currency;
        this.numberOfInstallments = numberOfInstallments;
        this.purchaseMethod = purchaseMethod;
        this.refOrderNumber = refOrderNumber;
        this.allowedInstallmentOptions = allowedInstallmentOptions;
        this.tags = tags;
        this.processingData = processingData;
        this.firstInstallmentDate = firstInstallmentDate;
    }

    /**
     * Getter for TerminalId.
     * @return Returns the String
     */
    @JsonGetter("TerminalId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTerminalId() {
        return terminalId;
    }

    /**
     * Setter for TerminalId.
     * @param terminalId Value for String
     */
    @JsonSetter("TerminalId")
    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * Getter for TotalAmount.
     * @return Returns the String
     */
    @JsonGetter("TotalAmount")
    public String getTotalAmount() {
        return totalAmount;
    }

    /**
     * Setter for TotalAmount.
     * @param totalAmount Value for String
     */
    @JsonSetter("TotalAmount")
    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * Getter for FirstInstallmentAmount.
     * @return Returns the Double
     */
    @JsonGetter("FirstInstallmentAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getFirstInstallmentAmount() {
        return firstInstallmentAmount;
    }

    /**
     * Setter for FirstInstallmentAmount.
     * @param firstInstallmentAmount Value for Double
     */
    @JsonSetter("FirstInstallmentAmount")
    public void setFirstInstallmentAmount(Double firstInstallmentAmount) {
        this.firstInstallmentAmount = firstInstallmentAmount;
    }

    /**
     * Getter for Currency.
     * @return Returns the String
     */
    @JsonGetter("Currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCurrency() {
        return currency;
    }

    /**
     * Setter for Currency.
     * @param currency Value for String
     */
    @JsonSetter("Currency")
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Getter for NumberOfInstallments.
     * @return Returns the int
     */
    @JsonGetter("NumberOfInstallments")
    public int getNumberOfInstallments() {
        return numberOfInstallments;
    }

    /**
     * Setter for NumberOfInstallments.
     * @param numberOfInstallments Value for int
     */
    @JsonSetter("NumberOfInstallments")
    public void setNumberOfInstallments(int numberOfInstallments) {
        this.numberOfInstallments = numberOfInstallments;
    }

    /**
     * Getter for PurchaseMethod.
     * @return Returns the PurchaseMethodEnum
     */
    @JsonGetter("PurchaseMethod")
    public PurchaseMethodEnum getPurchaseMethod() {
        return purchaseMethod;
    }

    /**
     * Setter for PurchaseMethod.
     * @param purchaseMethod Value for PurchaseMethodEnum
     */
    @JsonSetter("PurchaseMethod")
    public void setPurchaseMethod(PurchaseMethodEnum purchaseMethod) {
        this.purchaseMethod = purchaseMethod;
    }

    /**
     * Getter for RefOrderNumber.
     * @return Returns the String
     */
    @JsonGetter("RefOrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRefOrderNumber() {
        return refOrderNumber;
    }

    /**
     * Setter for RefOrderNumber.
     * @param refOrderNumber Value for String
     */
    @JsonSetter("RefOrderNumber")
    public void setRefOrderNumber(String refOrderNumber) {
        this.refOrderNumber = refOrderNumber;
    }

    /**
     * Getter for AllowedInstallmentOptions.
     * @return Returns the List of Integer
     */
    @JsonGetter("AllowedInstallmentOptions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getAllowedInstallmentOptions() {
        return allowedInstallmentOptions;
    }

    /**
     * Setter for AllowedInstallmentOptions.
     * @param allowedInstallmentOptions Value for List of Integer
     */
    @JsonSetter("AllowedInstallmentOptions")
    public void setAllowedInstallmentOptions(List<Integer> allowedInstallmentOptions) {
        this.allowedInstallmentOptions = allowedInstallmentOptions;
    }

    /**
     * Getter for Tags.
     * @return Returns the Map of String, String
     */
    @JsonGetter("Tags")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, String> getTags() {
        return tags;
    }

    /**
     * Setter for Tags.
     * @param tags Value for Map of String, String
     */
    @JsonSetter("Tags")
    public void setTags(Map<String, String> tags) {
        this.tags = tags;
    }

    /**
     * Getter for ProcessingData.
     * @return Returns the ProcessingData
     */
    @JsonGetter("ProcessingData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ProcessingData getProcessingData() {
        return processingData;
    }

    /**
     * Setter for ProcessingData.
     * @param processingData Value for ProcessingData
     */
    @JsonSetter("ProcessingData")
    public void setProcessingData(ProcessingData processingData) {
        this.processingData = processingData;
    }

    /**
     * Getter for FirstInstallmentDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("FirstInstallmentDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getFirstInstallmentDate() {
        return firstInstallmentDate;
    }

    /**
     * Setter for FirstInstallmentDate.
     * @param firstInstallmentDate Value for LocalDateTime
     */
    @JsonSetter("FirstInstallmentDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setFirstInstallmentDate(LocalDateTime firstInstallmentDate) {
        this.firstInstallmentDate = firstInstallmentDate;
    }

    /**
     * Converts this PlanData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlanData [" + "totalAmount=" + totalAmount + ", numberOfInstallments="
                + numberOfInstallments + ", purchaseMethod=" + purchaseMethod + ", terminalId="
                + terminalId + ", firstInstallmentAmount=" + firstInstallmentAmount + ", currency="
                + currency + ", refOrderNumber=" + refOrderNumber + ", allowedInstallmentOptions="
                + allowedInstallmentOptions + ", tags=" + tags + ", processingData="
                + processingData + ", firstInstallmentDate=" + firstInstallmentDate + "]";
    }

    /**
     * Builds a new {@link PlanData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlanData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(totalAmount, numberOfInstallments, purchaseMethod)
                .terminalId(getTerminalId())
                .firstInstallmentAmount(getFirstInstallmentAmount())
                .currency(getCurrency())
                .refOrderNumber(getRefOrderNumber())
                .allowedInstallmentOptions(getAllowedInstallmentOptions())
                .tags(getTags())
                .processingData(getProcessingData())
                .firstInstallmentDate(getFirstInstallmentDate());
        return builder;
    }

    /**
     * Class to build instances of {@link PlanData}.
     */
    public static class Builder {
        private String totalAmount;
        private int numberOfInstallments;
        private PurchaseMethodEnum purchaseMethod;
        private String terminalId;
        private Double firstInstallmentAmount;
        private String currency;
        private String refOrderNumber;
        private List<Integer> allowedInstallmentOptions;
        private Map<String, String> tags;
        private ProcessingData processingData;
        private LocalDateTime firstInstallmentDate;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  totalAmount  String value for totalAmount.
         * @param  numberOfInstallments  int value for numberOfInstallments.
         * @param  purchaseMethod  PurchaseMethodEnum value for purchaseMethod.
         */
        public Builder(String totalAmount, int numberOfInstallments,
                PurchaseMethodEnum purchaseMethod) {
            this.totalAmount = totalAmount;
            this.numberOfInstallments = numberOfInstallments;
            this.purchaseMethod = purchaseMethod;
        }

        /**
         * Setter for totalAmount.
         * @param  totalAmount  String value for totalAmount.
         * @return Builder
         */
        public Builder totalAmount(String totalAmount) {
            this.totalAmount = totalAmount;
            return this;
        }

        /**
         * Setter for numberOfInstallments.
         * @param  numberOfInstallments  int value for numberOfInstallments.
         * @return Builder
         */
        public Builder numberOfInstallments(int numberOfInstallments) {
            this.numberOfInstallments = numberOfInstallments;
            return this;
        }

        /**
         * Setter for purchaseMethod.
         * @param  purchaseMethod  PurchaseMethodEnum value for purchaseMethod.
         * @return Builder
         */
        public Builder purchaseMethod(PurchaseMethodEnum purchaseMethod) {
            this.purchaseMethod = purchaseMethod;
            return this;
        }

        /**
         * Setter for terminalId.
         * @param  terminalId  String value for terminalId.
         * @return Builder
         */
        public Builder terminalId(String terminalId) {
            this.terminalId = terminalId;
            return this;
        }

        /**
         * Setter for firstInstallmentAmount.
         * @param  firstInstallmentAmount  Double value for firstInstallmentAmount.
         * @return Builder
         */
        public Builder firstInstallmentAmount(Double firstInstallmentAmount) {
            this.firstInstallmentAmount = firstInstallmentAmount;
            return this;
        }

        /**
         * Setter for currency.
         * @param  currency  String value for currency.
         * @return Builder
         */
        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * Setter for refOrderNumber.
         * @param  refOrderNumber  String value for refOrderNumber.
         * @return Builder
         */
        public Builder refOrderNumber(String refOrderNumber) {
            this.refOrderNumber = refOrderNumber;
            return this;
        }

        /**
         * Setter for allowedInstallmentOptions.
         * @param  allowedInstallmentOptions  List of Integer value for allowedInstallmentOptions.
         * @return Builder
         */
        public Builder allowedInstallmentOptions(List<Integer> allowedInstallmentOptions) {
            this.allowedInstallmentOptions = allowedInstallmentOptions;
            return this;
        }

        /**
         * Setter for tags.
         * @param  tags  Map of String, value for tags.
         * @return Builder
         */
        public Builder tags(Map<String, String> tags) {
            this.tags = tags;
            return this;
        }

        /**
         * Setter for processingData.
         * @param  processingData  ProcessingData value for processingData.
         * @return Builder
         */
        public Builder processingData(ProcessingData processingData) {
            this.processingData = processingData;
            return this;
        }

        /**
         * Setter for firstInstallmentDate.
         * @param  firstInstallmentDate  LocalDateTime value for firstInstallmentDate.
         * @return Builder
         */
        public Builder firstInstallmentDate(LocalDateTime firstInstallmentDate) {
            this.firstInstallmentDate = firstInstallmentDate;
            return this;
        }

        /**
         * Builds a new {@link PlanData} object using the set fields.
         * @return {@link PlanData}
         */
        public PlanData build() {
            return new PlanData(totalAmount, numberOfInstallments, purchaseMethod, terminalId,
                    firstInstallmentAmount, currency, refOrderNumber, allowedInstallmentOptions,
                    tags, processingData, firstInstallmentDate);
        }
    }
}
