/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.splitit.sandbox.webapiv3.DateTimeHelper;
import io.apimatic.core.types.OptionalNullable;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * This is a model class for PlanDataModel type.
 */
public class PlanDataModel {
    private String totalAmount;
    private String currency;
    private OptionalNullable<Integer> numberOfInstallments;
    private String terminalId;
    private PurchaseMethodEnum purchaseMethod;
    private String refOrderNumber;
    private Map<String, String> extendedParams;
    private String firstInstallmentAmount;
    private LocalDateTime firstInstallmentDate;

    /**
     * Default constructor.
     */
    public PlanDataModel() {
    }

    /**
     * Initialization constructor.
     * @param  totalAmount  String value for totalAmount.
     * @param  purchaseMethod  PurchaseMethodEnum value for purchaseMethod.
     * @param  currency  String value for currency.
     * @param  numberOfInstallments  Integer value for numberOfInstallments.
     * @param  terminalId  String value for terminalId.
     * @param  refOrderNumber  String value for refOrderNumber.
     * @param  extendedParams  Map of String, value for extendedParams.
     * @param  firstInstallmentAmount  String value for firstInstallmentAmount.
     * @param  firstInstallmentDate  LocalDateTime value for firstInstallmentDate.
     */
    public PlanDataModel(
            String totalAmount,
            PurchaseMethodEnum purchaseMethod,
            String currency,
            Integer numberOfInstallments,
            String terminalId,
            String refOrderNumber,
            Map<String, String> extendedParams,
            String firstInstallmentAmount,
            LocalDateTime firstInstallmentDate) {
        this.totalAmount = totalAmount;
        this.currency = currency;
        this.numberOfInstallments = OptionalNullable.of(numberOfInstallments);
        this.terminalId = terminalId;
        this.purchaseMethod = purchaseMethod;
        this.refOrderNumber = refOrderNumber;
        this.extendedParams = extendedParams;
        this.firstInstallmentAmount = firstInstallmentAmount;
        this.firstInstallmentDate = firstInstallmentDate;
    }

    /**
     * Initialization constructor.
     * @param  totalAmount  String value for totalAmount.
     * @param  purchaseMethod  PurchaseMethodEnum value for purchaseMethod.
     * @param  currency  String value for currency.
     * @param  numberOfInstallments  Integer value for numberOfInstallments.
     * @param  terminalId  String value for terminalId.
     * @param  refOrderNumber  String value for refOrderNumber.
     * @param  extendedParams  Map of String, value for extendedParams.
     * @param  firstInstallmentAmount  String value for firstInstallmentAmount.
     * @param  firstInstallmentDate  LocalDateTime value for firstInstallmentDate.
     */

    protected PlanDataModel(String totalAmount, PurchaseMethodEnum purchaseMethod, String currency,
            OptionalNullable<Integer> numberOfInstallments, String terminalId,
            String refOrderNumber, Map<String, String> extendedParams,
            String firstInstallmentAmount, LocalDateTime firstInstallmentDate) {
        this.totalAmount = totalAmount;
        this.currency = currency;
        this.numberOfInstallments = numberOfInstallments;
        this.terminalId = terminalId;
        this.purchaseMethod = purchaseMethod;
        this.refOrderNumber = refOrderNumber;
        this.extendedParams = extendedParams;
        this.firstInstallmentAmount = firstInstallmentAmount;
        this.firstInstallmentDate = firstInstallmentDate;
    }

    /**
     * Getter for TotalAmount.
     * @return Returns the String
     */
    @JsonGetter("TotalAmount")
    public String getTotalAmount() {
        return totalAmount;
    }

    /**
     * Setter for TotalAmount.
     * @param totalAmount Value for String
     */
    @JsonSetter("TotalAmount")
    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * Getter for Currency.
     * @return Returns the String
     */
    @JsonGetter("Currency")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCurrency() {
        return currency;
    }

    /**
     * Setter for Currency.
     * @param currency Value for String
     */
    @JsonSetter("Currency")
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * Internal Getter for NumberOfInstallments.
     * @return Returns the Internal Integer
     */
    @JsonGetter("NumberOfInstallments")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<Integer> internalGetNumberOfInstallments() {
        return this.numberOfInstallments;
    }

    /**
     * Getter for NumberOfInstallments.
     * @return Returns the Integer
     */
    public Integer getNumberOfInstallments() {
        return OptionalNullable.getFrom(numberOfInstallments);
    }

    /**
     * Setter for NumberOfInstallments.
     * @param numberOfInstallments Value for Integer
     */
    @JsonSetter("NumberOfInstallments")
    public void setNumberOfInstallments(Integer numberOfInstallments) {
        this.numberOfInstallments = OptionalNullable.of(numberOfInstallments);
    }

    /**
     * UnSetter for NumberOfInstallments.
     */
    public void unsetNumberOfInstallments() {
        numberOfInstallments = null;
    }

    /**
     * Getter for TerminalId.
     * @return Returns the String
     */
    @JsonGetter("TerminalId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTerminalId() {
        return terminalId;
    }

    /**
     * Setter for TerminalId.
     * @param terminalId Value for String
     */
    @JsonSetter("TerminalId")
    public void setTerminalId(String terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * Getter for PurchaseMethod.
     * @return Returns the PurchaseMethodEnum
     */
    @JsonGetter("PurchaseMethod")
    public PurchaseMethodEnum getPurchaseMethod() {
        return purchaseMethod;
    }

    /**
     * Setter for PurchaseMethod.
     * @param purchaseMethod Value for PurchaseMethodEnum
     */
    @JsonSetter("PurchaseMethod")
    public void setPurchaseMethod(PurchaseMethodEnum purchaseMethod) {
        this.purchaseMethod = purchaseMethod;
    }

    /**
     * Getter for RefOrderNumber.
     * @return Returns the String
     */
    @JsonGetter("RefOrderNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRefOrderNumber() {
        return refOrderNumber;
    }

    /**
     * Setter for RefOrderNumber.
     * @param refOrderNumber Value for String
     */
    @JsonSetter("RefOrderNumber")
    public void setRefOrderNumber(String refOrderNumber) {
        this.refOrderNumber = refOrderNumber;
    }

    /**
     * Getter for ExtendedParams.
     * @return Returns the Map of String, String
     */
    @JsonGetter("ExtendedParams")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, String> getExtendedParams() {
        return extendedParams;
    }

    /**
     * Setter for ExtendedParams.
     * @param extendedParams Value for Map of String, String
     */
    @JsonSetter("ExtendedParams")
    public void setExtendedParams(Map<String, String> extendedParams) {
        this.extendedParams = extendedParams;
    }

    /**
     * Getter for FirstInstallmentAmount.
     * @return Returns the String
     */
    @JsonGetter("FirstInstallmentAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFirstInstallmentAmount() {
        return firstInstallmentAmount;
    }

    /**
     * Setter for FirstInstallmentAmount.
     * @param firstInstallmentAmount Value for String
     */
    @JsonSetter("FirstInstallmentAmount")
    public void setFirstInstallmentAmount(String firstInstallmentAmount) {
        this.firstInstallmentAmount = firstInstallmentAmount;
    }

    /**
     * Getter for FirstInstallmentDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("FirstInstallmentDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getFirstInstallmentDate() {
        return firstInstallmentDate;
    }

    /**
     * Setter for FirstInstallmentDate.
     * @param firstInstallmentDate Value for LocalDateTime
     */
    @JsonSetter("FirstInstallmentDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setFirstInstallmentDate(LocalDateTime firstInstallmentDate) {
        this.firstInstallmentDate = firstInstallmentDate;
    }

    /**
     * Converts this PlanDataModel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlanDataModel [" + "totalAmount=" + totalAmount + ", purchaseMethod="
                + purchaseMethod + ", currency=" + currency + ", numberOfInstallments="
                + numberOfInstallments + ", terminalId=" + terminalId + ", refOrderNumber="
                + refOrderNumber + ", extendedParams=" + extendedParams
                + ", firstInstallmentAmount=" + firstInstallmentAmount + ", firstInstallmentDate="
                + firstInstallmentDate + "]";
    }

    /**
     * Builds a new {@link PlanDataModel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlanDataModel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(totalAmount, purchaseMethod)
                .currency(getCurrency())
                .terminalId(getTerminalId())
                .refOrderNumber(getRefOrderNumber())
                .extendedParams(getExtendedParams())
                .firstInstallmentAmount(getFirstInstallmentAmount())
                .firstInstallmentDate(getFirstInstallmentDate());
        builder.numberOfInstallments = internalGetNumberOfInstallments();
        return builder;
    }

    /**
     * Class to build instances of {@link PlanDataModel}.
     */
    public static class Builder {
        private String totalAmount;
        private PurchaseMethodEnum purchaseMethod;
        private String currency;
        private OptionalNullable<Integer> numberOfInstallments;
        private String terminalId;
        private String refOrderNumber;
        private Map<String, String> extendedParams;
        private String firstInstallmentAmount;
        private LocalDateTime firstInstallmentDate;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  totalAmount  String value for totalAmount.
         * @param  purchaseMethod  PurchaseMethodEnum value for purchaseMethod.
         */
        public Builder(String totalAmount, PurchaseMethodEnum purchaseMethod) {
            this.totalAmount = totalAmount;
            this.purchaseMethod = purchaseMethod;
        }

        /**
         * Setter for totalAmount.
         * @param  totalAmount  String value for totalAmount.
         * @return Builder
         */
        public Builder totalAmount(String totalAmount) {
            this.totalAmount = totalAmount;
            return this;
        }

        /**
         * Setter for purchaseMethod.
         * @param  purchaseMethod  PurchaseMethodEnum value for purchaseMethod.
         * @return Builder
         */
        public Builder purchaseMethod(PurchaseMethodEnum purchaseMethod) {
            this.purchaseMethod = purchaseMethod;
            return this;
        }

        /**
         * Setter for currency.
         * @param  currency  String value for currency.
         * @return Builder
         */
        public Builder currency(String currency) {
            this.currency = currency;
            return this;
        }

        /**
         * Setter for numberOfInstallments.
         * @param  numberOfInstallments  Integer value for numberOfInstallments.
         * @return Builder
         */
        public Builder numberOfInstallments(Integer numberOfInstallments) {
            this.numberOfInstallments = OptionalNullable.of(numberOfInstallments);
            return this;
        }

        /**
         * UnSetter for numberOfInstallments.
         * @return Builder
         */
        public Builder unsetNumberOfInstallments() {
            numberOfInstallments = null;
            return this;
        }

        /**
         * Setter for terminalId.
         * @param  terminalId  String value for terminalId.
         * @return Builder
         */
        public Builder terminalId(String terminalId) {
            this.terminalId = terminalId;
            return this;
        }

        /**
         * Setter for refOrderNumber.
         * @param  refOrderNumber  String value for refOrderNumber.
         * @return Builder
         */
        public Builder refOrderNumber(String refOrderNumber) {
            this.refOrderNumber = refOrderNumber;
            return this;
        }

        /**
         * Setter for extendedParams.
         * @param  extendedParams  Map of String, value for extendedParams.
         * @return Builder
         */
        public Builder extendedParams(Map<String, String> extendedParams) {
            this.extendedParams = extendedParams;
            return this;
        }

        /**
         * Setter for firstInstallmentAmount.
         * @param  firstInstallmentAmount  String value for firstInstallmentAmount.
         * @return Builder
         */
        public Builder firstInstallmentAmount(String firstInstallmentAmount) {
            this.firstInstallmentAmount = firstInstallmentAmount;
            return this;
        }

        /**
         * Setter for firstInstallmentDate.
         * @param  firstInstallmentDate  LocalDateTime value for firstInstallmentDate.
         * @return Builder
         */
        public Builder firstInstallmentDate(LocalDateTime firstInstallmentDate) {
            this.firstInstallmentDate = firstInstallmentDate;
            return this;
        }

        /**
         * Builds a new {@link PlanDataModel} object using the set fields.
         * @return {@link PlanDataModel}
         */
        public PlanDataModel build() {
            return new PlanDataModel(totalAmount, purchaseMethod, currency, numberOfInstallments,
                    terminalId, refOrderNumber, extendedParams, firstInstallmentAmount,
                    firstInstallmentDate);
        }
    }
}
