/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ProcessingData type.
 */
public class ProcessingData {
    private Boolean attemptThreeDSecured;
    private String softDescriptor;
    private ThreeDSData threeDSData;

    /**
     * Default constructor.
     */
    public ProcessingData() {
    }

    /**
     * Initialization constructor.
     * @param  attemptThreeDSecured  Boolean value for attemptThreeDSecured.
     * @param  softDescriptor  String value for softDescriptor.
     * @param  threeDSData  ThreeDSData value for threeDSData.
     */
    public ProcessingData(
            Boolean attemptThreeDSecured,
            String softDescriptor,
            ThreeDSData threeDSData) {
        this.attemptThreeDSecured = attemptThreeDSecured;
        this.softDescriptor = softDescriptor;
        this.threeDSData = threeDSData;
    }

    /**
     * Getter for AttemptThreeDSecured.
     * @return Returns the Boolean
     */
    @JsonGetter("AttemptThreeDSecured")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getAttemptThreeDSecured() {
        return attemptThreeDSecured;
    }

    /**
     * Setter for AttemptThreeDSecured.
     * @param attemptThreeDSecured Value for Boolean
     */
    @JsonSetter("AttemptThreeDSecured")
    public void setAttemptThreeDSecured(Boolean attemptThreeDSecured) {
        this.attemptThreeDSecured = attemptThreeDSecured;
    }

    /**
     * Getter for SoftDescriptor.
     * @return Returns the String
     */
    @JsonGetter("SoftDescriptor")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSoftDescriptor() {
        return softDescriptor;
    }

    /**
     * Setter for SoftDescriptor.
     * @param softDescriptor Value for String
     */
    @JsonSetter("SoftDescriptor")
    public void setSoftDescriptor(String softDescriptor) {
        this.softDescriptor = softDescriptor;
    }

    /**
     * Getter for ThreeDSData.
     * @return Returns the ThreeDSData
     */
    @JsonGetter("ThreeDSData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ThreeDSData getThreeDSData() {
        return threeDSData;
    }

    /**
     * Setter for ThreeDSData.
     * @param threeDSData Value for ThreeDSData
     */
    @JsonSetter("ThreeDSData")
    public void setThreeDSData(ThreeDSData threeDSData) {
        this.threeDSData = threeDSData;
    }

    /**
     * Converts this ProcessingData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ProcessingData [" + "attemptThreeDSecured=" + attemptThreeDSecured
                + ", softDescriptor=" + softDescriptor + ", threeDSData=" + threeDSData + "]";
    }

    /**
     * Builds a new {@link ProcessingData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ProcessingData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .attemptThreeDSecured(getAttemptThreeDSecured())
                .softDescriptor(getSoftDescriptor())
                .threeDSData(getThreeDSData());
        return builder;
    }

    /**
     * Class to build instances of {@link ProcessingData}.
     */
    public static class Builder {
        private Boolean attemptThreeDSecured;
        private String softDescriptor;
        private ThreeDSData threeDSData;



        /**
         * Setter for attemptThreeDSecured.
         * @param  attemptThreeDSecured  Boolean value for attemptThreeDSecured.
         * @return Builder
         */
        public Builder attemptThreeDSecured(Boolean attemptThreeDSecured) {
            this.attemptThreeDSecured = attemptThreeDSecured;
            return this;
        }

        /**
         * Setter for softDescriptor.
         * @param  softDescriptor  String value for softDescriptor.
         * @return Builder
         */
        public Builder softDescriptor(String softDescriptor) {
            this.softDescriptor = softDescriptor;
            return this;
        }

        /**
         * Setter for threeDSData.
         * @param  threeDSData  ThreeDSData value for threeDSData.
         * @return Builder
         */
        public Builder threeDSData(ThreeDSData threeDSData) {
            this.threeDSData = threeDSData;
            return this;
        }

        /**
         * Builds a new {@link ProcessingData} object using the set fields.
         * @return {@link ProcessingData}
         */
        public ProcessingData build() {
            return new ProcessingData(attemptThreeDSecured, softDescriptor, threeDSData);
        }
    }
}
