/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RedirectionEndpointsModel type.
 */
public class RedirectionEndpointsModel {
    private String authorizeSucceeded;
    private String succeeded;
    private String authorizeFailed;
    private String failed;

    /**
     * Default constructor.
     */
    public RedirectionEndpointsModel() {
    }

    /**
     * Initialization constructor.
     * @param  authorizeSucceeded  String value for authorizeSucceeded.
     * @param  succeeded  String value for succeeded.
     * @param  authorizeFailed  String value for authorizeFailed.
     * @param  failed  String value for failed.
     */
    public RedirectionEndpointsModel(
            String authorizeSucceeded,
            String succeeded,
            String authorizeFailed,
            String failed) {
        this.authorizeSucceeded = authorizeSucceeded;
        this.succeeded = succeeded;
        this.authorizeFailed = authorizeFailed;
        this.failed = failed;
    }

    /**
     * Getter for AuthorizeSucceeded.
     * @return Returns the String
     */
    @JsonGetter("AuthorizeSucceeded")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAuthorizeSucceeded() {
        return authorizeSucceeded;
    }

    /**
     * Setter for AuthorizeSucceeded.
     * @param authorizeSucceeded Value for String
     */
    @JsonSetter("AuthorizeSucceeded")
    public void setAuthorizeSucceeded(String authorizeSucceeded) {
        this.authorizeSucceeded = authorizeSucceeded;
    }

    /**
     * Getter for Succeeded.
     * @return Returns the String
     */
    @JsonGetter("Succeeded")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSucceeded() {
        return succeeded;
    }

    /**
     * Setter for Succeeded.
     * @param succeeded Value for String
     */
    @JsonSetter("Succeeded")
    public void setSucceeded(String succeeded) {
        this.succeeded = succeeded;
    }

    /**
     * Getter for AuthorizeFailed.
     * @return Returns the String
     */
    @JsonGetter("AuthorizeFailed")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAuthorizeFailed() {
        return authorizeFailed;
    }

    /**
     * Setter for AuthorizeFailed.
     * @param authorizeFailed Value for String
     */
    @JsonSetter("AuthorizeFailed")
    public void setAuthorizeFailed(String authorizeFailed) {
        this.authorizeFailed = authorizeFailed;
    }

    /**
     * Getter for Failed.
     * @return Returns the String
     */
    @JsonGetter("Failed")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFailed() {
        return failed;
    }

    /**
     * Setter for Failed.
     * @param failed Value for String
     */
    @JsonSetter("Failed")
    public void setFailed(String failed) {
        this.failed = failed;
    }

    /**
     * Converts this RedirectionEndpointsModel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RedirectionEndpointsModel [" + "authorizeSucceeded=" + authorizeSucceeded
                + ", succeeded=" + succeeded + ", authorizeFailed=" + authorizeFailed + ", failed="
                + failed + "]";
    }

    /**
     * Builds a new {@link RedirectionEndpointsModel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RedirectionEndpointsModel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .authorizeSucceeded(getAuthorizeSucceeded())
                .succeeded(getSucceeded())
                .authorizeFailed(getAuthorizeFailed())
                .failed(getFailed());
        return builder;
    }

    /**
     * Class to build instances of {@link RedirectionEndpointsModel}.
     */
    public static class Builder {
        private String authorizeSucceeded;
        private String succeeded;
        private String authorizeFailed;
        private String failed;



        /**
         * Setter for authorizeSucceeded.
         * @param  authorizeSucceeded  String value for authorizeSucceeded.
         * @return Builder
         */
        public Builder authorizeSucceeded(String authorizeSucceeded) {
            this.authorizeSucceeded = authorizeSucceeded;
            return this;
        }

        /**
         * Setter for succeeded.
         * @param  succeeded  String value for succeeded.
         * @return Builder
         */
        public Builder succeeded(String succeeded) {
            this.succeeded = succeeded;
            return this;
        }

        /**
         * Setter for authorizeFailed.
         * @param  authorizeFailed  String value for authorizeFailed.
         * @return Builder
         */
        public Builder authorizeFailed(String authorizeFailed) {
            this.authorizeFailed = authorizeFailed;
            return this;
        }

        /**
         * Setter for failed.
         * @param  failed  String value for failed.
         * @return Builder
         */
        public Builder failed(String failed) {
            this.failed = failed;
            return this;
        }

        /**
         * Builds a new {@link RedirectionEndpointsModel} object using the set fields.
         * @return {@link RedirectionEndpointsModel}
         */
        public RedirectionEndpointsModel build() {
            return new RedirectionEndpointsModel(authorizeSucceeded, succeeded, authorizeFailed,
                    failed);
        }
    }
}
