/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * RefundStatusEnum to be used.
 */
public enum RefundStatusEnum {
    PENDING,

    SUCCEEDED,

    FAILED;


    private static TreeMap<String, RefundStatusEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        PENDING.value = "Pending";
        SUCCEEDED.value = "Succeeded";
        FAILED.value = "Failed";

        valueMap.put("Pending", PENDING);
        valueMap.put("Succeeded", SUCCEEDED);
        valueMap.put("Failed", FAILED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static RefundStatusEnum constructFromString(String toConvert) throws IOException {
        RefundStatusEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static RefundStatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of RefundStatusEnum values to list of string values.
     * @param toConvert The list of RefundStatusEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<RefundStatusEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (RefundStatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 