/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RefundSummary type.
 */
public class RefundSummary {
    private Double totalAmount;
    private Double failedAmount;
    private Double succeededAmount;
    private Double pendingAmount;

    /**
     * Default constructor.
     */
    public RefundSummary() {
    }

    /**
     * Initialization constructor.
     * @param  totalAmount  Double value for totalAmount.
     * @param  failedAmount  Double value for failedAmount.
     * @param  succeededAmount  Double value for succeededAmount.
     * @param  pendingAmount  Double value for pendingAmount.
     */
    public RefundSummary(
            Double totalAmount,
            Double failedAmount,
            Double succeededAmount,
            Double pendingAmount) {
        this.totalAmount = totalAmount;
        this.failedAmount = failedAmount;
        this.succeededAmount = succeededAmount;
        this.pendingAmount = pendingAmount;
    }

    /**
     * Getter for TotalAmount.
     * @return Returns the Double
     */
    @JsonGetter("TotalAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getTotalAmount() {
        return totalAmount;
    }

    /**
     * Setter for TotalAmount.
     * @param totalAmount Value for Double
     */
    @JsonSetter("TotalAmount")
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * Getter for FailedAmount.
     * @return Returns the Double
     */
    @JsonGetter("FailedAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getFailedAmount() {
        return failedAmount;
    }

    /**
     * Setter for FailedAmount.
     * @param failedAmount Value for Double
     */
    @JsonSetter("FailedAmount")
    public void setFailedAmount(Double failedAmount) {
        this.failedAmount = failedAmount;
    }

    /**
     * Getter for SucceededAmount.
     * @return Returns the Double
     */
    @JsonGetter("SucceededAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getSucceededAmount() {
        return succeededAmount;
    }

    /**
     * Setter for SucceededAmount.
     * @param succeededAmount Value for Double
     */
    @JsonSetter("SucceededAmount")
    public void setSucceededAmount(Double succeededAmount) {
        this.succeededAmount = succeededAmount;
    }

    /**
     * Getter for PendingAmount.
     * @return Returns the Double
     */
    @JsonGetter("PendingAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getPendingAmount() {
        return pendingAmount;
    }

    /**
     * Setter for PendingAmount.
     * @param pendingAmount Value for Double
     */
    @JsonSetter("PendingAmount")
    public void setPendingAmount(Double pendingAmount) {
        this.pendingAmount = pendingAmount;
    }

    /**
     * Converts this RefundSummary into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RefundSummary [" + "totalAmount=" + totalAmount + ", failedAmount=" + failedAmount
                + ", succeededAmount=" + succeededAmount + ", pendingAmount=" + pendingAmount + "]";
    }

    /**
     * Builds a new {@link RefundSummary.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RefundSummary.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .totalAmount(getTotalAmount())
                .failedAmount(getFailedAmount())
                .succeededAmount(getSucceededAmount())
                .pendingAmount(getPendingAmount());
        return builder;
    }

    /**
     * Class to build instances of {@link RefundSummary}.
     */
    public static class Builder {
        private Double totalAmount;
        private Double failedAmount;
        private Double succeededAmount;
        private Double pendingAmount;



        /**
         * Setter for totalAmount.
         * @param  totalAmount  Double value for totalAmount.
         * @return Builder
         */
        public Builder totalAmount(Double totalAmount) {
            this.totalAmount = totalAmount;
            return this;
        }

        /**
         * Setter for failedAmount.
         * @param  failedAmount  Double value for failedAmount.
         * @return Builder
         */
        public Builder failedAmount(Double failedAmount) {
            this.failedAmount = failedAmount;
            return this;
        }

        /**
         * Setter for succeededAmount.
         * @param  succeededAmount  Double value for succeededAmount.
         * @return Builder
         */
        public Builder succeededAmount(Double succeededAmount) {
            this.succeededAmount = succeededAmount;
            return this;
        }

        /**
         * Setter for pendingAmount.
         * @param  pendingAmount  Double value for pendingAmount.
         * @return Builder
         */
        public Builder pendingAmount(Double pendingAmount) {
            this.pendingAmount = pendingAmount;
            return this;
        }

        /**
         * Builds a new {@link RefundSummary} object using the set fields.
         * @return {@link RefundSummary}
         */
        public RefundSummary build() {
            return new RefundSummary(totalAmount, failedAmount, succeededAmount, pendingAmount);
        }
    }
}
