/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.splitit.sandbox.webapiv3.DateTimeHelper;
import java.time.LocalDateTime;

/**
 * This is a model class for RefundModel type.
 */
public class RefundModel {
    private String refundId;
    private LocalDateTime submitDate;
    private double totalAmount;
    private RefundStatusEnum status;
    private double nonCreditRefundAmount;
    private double creditRefundAmount;
    private String referenceId;

    /**
     * Default constructor.
     */
    public RefundModel() {
    }

    /**
     * Initialization constructor.
     * @param  submitDate  LocalDateTime value for submitDate.
     * @param  totalAmount  double value for totalAmount.
     * @param  status  RefundStatusEnum value for status.
     * @param  nonCreditRefundAmount  double value for nonCreditRefundAmount.
     * @param  creditRefundAmount  double value for creditRefundAmount.
     * @param  refundId  String value for refundId.
     * @param  referenceId  String value for referenceId.
     */
    public RefundModel(
            LocalDateTime submitDate,
            double totalAmount,
            RefundStatusEnum status,
            double nonCreditRefundAmount,
            double creditRefundAmount,
            String refundId,
            String referenceId) {
        this.refundId = refundId;
        this.submitDate = submitDate;
        this.totalAmount = totalAmount;
        this.status = status;
        this.nonCreditRefundAmount = nonCreditRefundAmount;
        this.creditRefundAmount = creditRefundAmount;
        this.referenceId = referenceId;
    }

    /**
     * Getter for RefundId.
     * @return Returns the String
     */
    @JsonGetter("RefundId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getRefundId() {
        return refundId;
    }

    /**
     * Setter for RefundId.
     * @param refundId Value for String
     */
    @JsonSetter("RefundId")
    public void setRefundId(String refundId) {
        this.refundId = refundId;
    }

    /**
     * Getter for SubmitDate.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("SubmitDate")
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getSubmitDate() {
        return submitDate;
    }

    /**
     * Setter for SubmitDate.
     * @param submitDate Value for LocalDateTime
     */
    @JsonSetter("SubmitDate")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setSubmitDate(LocalDateTime submitDate) {
        this.submitDate = submitDate;
    }

    /**
     * Getter for TotalAmount.
     * @return Returns the double
     */
    @JsonGetter("TotalAmount")
    public double getTotalAmount() {
        return totalAmount;
    }

    /**
     * Setter for TotalAmount.
     * @param totalAmount Value for double
     */
    @JsonSetter("TotalAmount")
    public void setTotalAmount(double totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * Getter for Status.
     * @return Returns the RefundStatusEnum
     */
    @JsonGetter("Status")
    public RefundStatusEnum getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * @param status Value for RefundStatusEnum
     */
    @JsonSetter("Status")
    public void setStatus(RefundStatusEnum status) {
        this.status = status;
    }

    /**
     * Getter for NonCreditRefundAmount.
     * @return Returns the double
     */
    @JsonGetter("NonCreditRefundAmount")
    public double getNonCreditRefundAmount() {
        return nonCreditRefundAmount;
    }

    /**
     * Setter for NonCreditRefundAmount.
     * @param nonCreditRefundAmount Value for double
     */
    @JsonSetter("NonCreditRefundAmount")
    public void setNonCreditRefundAmount(double nonCreditRefundAmount) {
        this.nonCreditRefundAmount = nonCreditRefundAmount;
    }

    /**
     * Getter for CreditRefundAmount.
     * @return Returns the double
     */
    @JsonGetter("CreditRefundAmount")
    public double getCreditRefundAmount() {
        return creditRefundAmount;
    }

    /**
     * Setter for CreditRefundAmount.
     * @param creditRefundAmount Value for double
     */
    @JsonSetter("CreditRefundAmount")
    public void setCreditRefundAmount(double creditRefundAmount) {
        this.creditRefundAmount = creditRefundAmount;
    }

    /**
     * Getter for ReferenceId.
     * @return Returns the String
     */
    @JsonGetter("ReferenceId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReferenceId() {
        return referenceId;
    }

    /**
     * Setter for ReferenceId.
     * @param referenceId Value for String
     */
    @JsonSetter("ReferenceId")
    public void setReferenceId(String referenceId) {
        this.referenceId = referenceId;
    }

    /**
     * Converts this RefundModel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RefundModel [" + "submitDate=" + submitDate + ", totalAmount=" + totalAmount
                + ", status=" + status + ", nonCreditRefundAmount=" + nonCreditRefundAmount
                + ", creditRefundAmount=" + creditRefundAmount + ", refundId=" + refundId
                + ", referenceId=" + referenceId + "]";
    }

    /**
     * Builds a new {@link RefundModel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RefundModel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(submitDate, totalAmount, status, nonCreditRefundAmount,
                creditRefundAmount)
                .refundId(getRefundId())
                .referenceId(getReferenceId());
        return builder;
    }

    /**
     * Class to build instances of {@link RefundModel}.
     */
    public static class Builder {
        private LocalDateTime submitDate;
        private double totalAmount;
        private RefundStatusEnum status;
        private double nonCreditRefundAmount;
        private double creditRefundAmount;
        private String refundId;
        private String referenceId;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  submitDate  LocalDateTime value for submitDate.
         * @param  totalAmount  double value for totalAmount.
         * @param  status  RefundStatusEnum value for status.
         * @param  nonCreditRefundAmount  double value for nonCreditRefundAmount.
         * @param  creditRefundAmount  double value for creditRefundAmount.
         */
        public Builder(LocalDateTime submitDate, double totalAmount, RefundStatusEnum status,
                double nonCreditRefundAmount, double creditRefundAmount) {
            this.submitDate = submitDate;
            this.totalAmount = totalAmount;
            this.status = status;
            this.nonCreditRefundAmount = nonCreditRefundAmount;
            this.creditRefundAmount = creditRefundAmount;
        }

        /**
         * Setter for submitDate.
         * @param  submitDate  LocalDateTime value for submitDate.
         * @return Builder
         */
        public Builder submitDate(LocalDateTime submitDate) {
            this.submitDate = submitDate;
            return this;
        }

        /**
         * Setter for totalAmount.
         * @param  totalAmount  double value for totalAmount.
         * @return Builder
         */
        public Builder totalAmount(double totalAmount) {
            this.totalAmount = totalAmount;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  RefundStatusEnum value for status.
         * @return Builder
         */
        public Builder status(RefundStatusEnum status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for nonCreditRefundAmount.
         * @param  nonCreditRefundAmount  double value for nonCreditRefundAmount.
         * @return Builder
         */
        public Builder nonCreditRefundAmount(double nonCreditRefundAmount) {
            this.nonCreditRefundAmount = nonCreditRefundAmount;
            return this;
        }

        /**
         * Setter for creditRefundAmount.
         * @param  creditRefundAmount  double value for creditRefundAmount.
         * @return Builder
         */
        public Builder creditRefundAmount(double creditRefundAmount) {
            this.creditRefundAmount = creditRefundAmount;
            return this;
        }

        /**
         * Setter for refundId.
         * @param  refundId  String value for refundId.
         * @return Builder
         */
        public Builder refundId(String refundId) {
            this.refundId = refundId;
            return this;
        }

        /**
         * Setter for referenceId.
         * @param  referenceId  String value for referenceId.
         * @return Builder
         */
        public Builder referenceId(String referenceId) {
            this.referenceId = referenceId;
            return this;
        }

        /**
         * Builds a new {@link RefundModel} object using the set fields.
         * @return {@link RefundModel}
         */
        public RefundModel build() {
            return new RefundModel(submitDate, totalAmount, status, nonCreditRefundAmount,
                    creditRefundAmount, refundId, referenceId);
        }
    }
}
