/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * ShippingStatusEnum to be used.
 */
public enum ShippingStatusEnum {
    PENDING,

    SHIPPED,

    DELIVERED;


    private static TreeMap<String, ShippingStatusEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        PENDING.value = "Pending";
        SHIPPED.value = "Shipped";
        DELIVERED.value = "Delivered";

        valueMap.put("Pending", PENDING);
        valueMap.put("Shipped", SHIPPED);
        valueMap.put("Delivered", DELIVERED);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static ShippingStatusEnum constructFromString(String toConvert) throws IOException {
        ShippingStatusEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static ShippingStatusEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of ShippingStatusEnum values to list of string values.
     * @param toConvert The list of ShippingStatusEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<ShippingStatusEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (ShippingStatusEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 