/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ShopperData type.
 */
public class ShopperData {
    private String fullName;
    private String email;
    private String phoneNumber;
    private String culture;
    private String externalId;

    /**
     * Default constructor.
     */
    public ShopperData() {
    }

    /**
     * Initialization constructor.
     * @param  fullName  String value for fullName.
     * @param  email  String value for email.
     * @param  phoneNumber  String value for phoneNumber.
     * @param  culture  String value for culture.
     * @param  externalId  String value for externalId.
     */
    public ShopperData(
            String fullName,
            String email,
            String phoneNumber,
            String culture,
            String externalId) {
        this.fullName = fullName;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.culture = culture;
        this.externalId = externalId;
    }

    /**
     * Getter for FullName.
     * @return Returns the String
     */
    @JsonGetter("FullName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getFullName() {
        return fullName;
    }

    /**
     * Setter for FullName.
     * @param fullName Value for String
     */
    @JsonSetter("FullName")
    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    /**
     * Getter for Email.
     * @return Returns the String
     */
    @JsonGetter("Email")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getEmail() {
        return email;
    }

    /**
     * Setter for Email.
     * @param email Value for String
     */
    @JsonSetter("Email")
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for PhoneNumber.
     * @return Returns the String
     */
    @JsonGetter("PhoneNumber")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Setter for PhoneNumber.
     * @param phoneNumber Value for String
     */
    @JsonSetter("PhoneNumber")
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Getter for Culture.
     * @return Returns the String
     */
    @JsonGetter("Culture")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCulture() {
        return culture;
    }

    /**
     * Setter for Culture.
     * @param culture Value for String
     */
    @JsonSetter("Culture")
    public void setCulture(String culture) {
        this.culture = culture;
    }

    /**
     * Getter for ExternalId.
     * @return Returns the String
     */
    @JsonGetter("ExternalId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getExternalId() {
        return externalId;
    }

    /**
     * Setter for ExternalId.
     * @param externalId Value for String
     */
    @JsonSetter("ExternalId")
    public void setExternalId(String externalId) {
        this.externalId = externalId;
    }

    /**
     * Converts this ShopperData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ShopperData [" + "fullName=" + fullName + ", email=" + email + ", phoneNumber="
                + phoneNumber + ", culture=" + culture + ", externalId=" + externalId + "]";
    }

    /**
     * Builds a new {@link ShopperData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ShopperData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .fullName(getFullName())
                .email(getEmail())
                .phoneNumber(getPhoneNumber())
                .culture(getCulture())
                .externalId(getExternalId());
        return builder;
    }

    /**
     * Class to build instances of {@link ShopperData}.
     */
    public static class Builder {
        private String fullName;
        private String email;
        private String phoneNumber;
        private String culture;
        private String externalId;



        /**
         * Setter for fullName.
         * @param  fullName  String value for fullName.
         * @return Builder
         */
        public Builder fullName(String fullName) {
            this.fullName = fullName;
            return this;
        }

        /**
         * Setter for email.
         * @param  email  String value for email.
         * @return Builder
         */
        public Builder email(String email) {
            this.email = email;
            return this;
        }

        /**
         * Setter for phoneNumber.
         * @param  phoneNumber  String value for phoneNumber.
         * @return Builder
         */
        public Builder phoneNumber(String phoneNumber) {
            this.phoneNumber = phoneNumber;
            return this;
        }

        /**
         * Setter for culture.
         * @param  culture  String value for culture.
         * @return Builder
         */
        public Builder culture(String culture) {
            this.culture = culture;
            return this;
        }

        /**
         * Setter for externalId.
         * @param  externalId  String value for externalId.
         * @return Builder
         */
        public Builder externalId(String externalId) {
            this.externalId = externalId;
            return this;
        }

        /**
         * Builds a new {@link ShopperData} object using the set fields.
         * @return {@link ShopperData}
         */
        public ShopperData build() {
            return new ShopperData(fullName, email, phoneNumber, culture, externalId);
        }
    }
}
