/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;


/**
 * TestModesEnum to be used.
 */
public enum TestModesEnum {
    NONE,

    REGULAR,

    FAST,

    AUTOMATION;


    private static TreeMap<String, TestModesEnum> valueMap = new TreeMap<>();
    private String value;

    static {
        NONE.value = "None";
        REGULAR.value = "Regular";
        FAST.value = "Fast";
        AUTOMATION.value = "Automation";

        valueMap.put("None", NONE);
        valueMap.put("Regular", REGULAR);
        valueMap.put("Fast", FAST);
        valueMap.put("Automation", AUTOMATION);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static TestModesEnum constructFromString(String toConvert) throws IOException {
        TestModesEnum enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static TestModesEnum fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of TestModesEnum values to list of string values.
     * @param toConvert The list of TestModesEnum values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<TestModesEnum> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (TestModesEnum enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 