/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.Map;

/**
 * This is a model class for ThreeDsRedirectDataV3 type.
 */
public class ThreeDsRedirectDataV3 {
    private String url;
    private String verb;
    private Map<String, String> params;
    private String clientRedirectUrl;

    /**
     * Default constructor.
     */
    public ThreeDsRedirectDataV3() {
    }

    /**
     * Initialization constructor.
     * @param  url  String value for url.
     * @param  verb  String value for verb.
     * @param  params  Map of String, value for params.
     * @param  clientRedirectUrl  String value for clientRedirectUrl.
     */
    public ThreeDsRedirectDataV3(
            String url,
            String verb,
            Map<String, String> params,
            String clientRedirectUrl) {
        this.url = url;
        this.verb = verb;
        this.params = params;
        this.clientRedirectUrl = clientRedirectUrl;
    }

    /**
     * Getter for Url.
     * @return Returns the String
     */
    @JsonGetter("Url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * @param url Value for String
     */
    @JsonSetter("Url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for Verb.
     * @return Returns the String
     */
    @JsonGetter("Verb")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getVerb() {
        return verb;
    }

    /**
     * Setter for Verb.
     * @param verb Value for String
     */
    @JsonSetter("Verb")
    public void setVerb(String verb) {
        this.verb = verb;
    }

    /**
     * Getter for Params.
     * @return Returns the Map of String, String
     */
    @JsonGetter("Params")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Map<String, String> getParams() {
        return params;
    }

    /**
     * Setter for Params.
     * @param params Value for Map of String, String
     */
    @JsonSetter("Params")
    public void setParams(Map<String, String> params) {
        this.params = params;
    }

    /**
     * Getter for ClientRedirectUrl.
     * @return Returns the String
     */
    @JsonGetter("ClientRedirectUrl")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getClientRedirectUrl() {
        return clientRedirectUrl;
    }

    /**
     * Setter for ClientRedirectUrl.
     * @param clientRedirectUrl Value for String
     */
    @JsonSetter("ClientRedirectUrl")
    public void setClientRedirectUrl(String clientRedirectUrl) {
        this.clientRedirectUrl = clientRedirectUrl;
    }

    /**
     * Converts this ThreeDsRedirectDataV3 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ThreeDsRedirectDataV3 [" + "url=" + url + ", verb=" + verb + ", params=" + params
                + ", clientRedirectUrl=" + clientRedirectUrl + "]";
    }

    /**
     * Builds a new {@link ThreeDsRedirectDataV3.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ThreeDsRedirectDataV3.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .url(getUrl())
                .verb(getVerb())
                .params(getParams())
                .clientRedirectUrl(getClientRedirectUrl());
        return builder;
    }

    /**
     * Class to build instances of {@link ThreeDsRedirectDataV3}.
     */
    public static class Builder {
        private String url;
        private String verb;
        private Map<String, String> params;
        private String clientRedirectUrl;



        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for verb.
         * @param  verb  String value for verb.
         * @return Builder
         */
        public Builder verb(String verb) {
            this.verb = verb;
            return this;
        }

        /**
         * Setter for params.
         * @param  params  Map of String, value for params.
         * @return Builder
         */
        public Builder params(Map<String, String> params) {
            this.params = params;
            return this;
        }

        /**
         * Setter for clientRedirectUrl.
         * @param  clientRedirectUrl  String value for clientRedirectUrl.
         * @return Builder
         */
        public Builder clientRedirectUrl(String clientRedirectUrl) {
            this.clientRedirectUrl = clientRedirectUrl;
            return this;
        }

        /**
         * Builds a new {@link ThreeDsRedirectDataV3} object using the set fields.
         * @return {@link ThreeDsRedirectDataV3}
         */
        public ThreeDsRedirectDataV3 build() {
            return new ThreeDsRedirectDataV3(url, verb, params, clientRedirectUrl);
        }
    }
}
