/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ThreeDSData type.
 */
public class ThreeDSData {
    private String eCI;
    private String cAVV;
    private String xID;
    private String directoryServerTxnId;
    private String threeDSVersion;
    private String transactionId;

    /**
     * Default constructor.
     */
    public ThreeDSData() {
    }

    /**
     * Initialization constructor.
     * @param  eCI  String value for eCI.
     * @param  cAVV  String value for cAVV.
     * @param  xID  String value for xID.
     * @param  directoryServerTxnId  String value for directoryServerTxnId.
     * @param  threeDSVersion  String value for threeDSVersion.
     * @param  transactionId  String value for transactionId.
     */
    public ThreeDSData(
            String eCI,
            String cAVV,
            String xID,
            String directoryServerTxnId,
            String threeDSVersion,
            String transactionId) {
        this.eCI = eCI;
        this.cAVV = cAVV;
        this.xID = xID;
        this.directoryServerTxnId = directoryServerTxnId;
        this.threeDSVersion = threeDSVersion;
        this.transactionId = transactionId;
    }

    /**
     * Getter for ECI.
     * @return Returns the String
     */
    @JsonGetter("ECI")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getECI() {
        return eCI;
    }

    /**
     * Setter for ECI.
     * @param eCI Value for String
     */
    @JsonSetter("ECI")
    public void setECI(String eCI) {
        this.eCI = eCI;
    }

    /**
     * Getter for CAVV.
     * @return Returns the String
     */
    @JsonGetter("CAVV")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCAVV() {
        return cAVV;
    }

    /**
     * Setter for CAVV.
     * @param cAVV Value for String
     */
    @JsonSetter("CAVV")
    public void setCAVV(String cAVV) {
        this.cAVV = cAVV;
    }

    /**
     * Getter for XID.
     * @return Returns the String
     */
    @JsonGetter("XID")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getXID() {
        return xID;
    }

    /**
     * Setter for XID.
     * @param xID Value for String
     */
    @JsonSetter("XID")
    public void setXID(String xID) {
        this.xID = xID;
    }

    /**
     * Getter for DirectoryServerTxnId.
     * @return Returns the String
     */
    @JsonGetter("DirectoryServerTxnId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDirectoryServerTxnId() {
        return directoryServerTxnId;
    }

    /**
     * Setter for DirectoryServerTxnId.
     * @param directoryServerTxnId Value for String
     */
    @JsonSetter("DirectoryServerTxnId")
    public void setDirectoryServerTxnId(String directoryServerTxnId) {
        this.directoryServerTxnId = directoryServerTxnId;
    }

    /**
     * Getter for ThreeDSVersion.
     * @return Returns the String
     */
    @JsonGetter("ThreeDSVersion")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getThreeDSVersion() {
        return threeDSVersion;
    }

    /**
     * Setter for ThreeDSVersion.
     * @param threeDSVersion Value for String
     */
    @JsonSetter("ThreeDSVersion")
    public void setThreeDSVersion(String threeDSVersion) {
        this.threeDSVersion = threeDSVersion;
    }

    /**
     * Getter for TransactionId.
     * @return Returns the String
     */
    @JsonGetter("TransactionId")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTransactionId() {
        return transactionId;
    }

    /**
     * Setter for TransactionId.
     * @param transactionId Value for String
     */
    @JsonSetter("TransactionId")
    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

    /**
     * Converts this ThreeDSData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ThreeDSData [" + "eCI=" + eCI + ", cAVV=" + cAVV + ", xID=" + xID
                + ", directoryServerTxnId=" + directoryServerTxnId + ", threeDSVersion="
                + threeDSVersion + ", transactionId=" + transactionId + "]";
    }

    /**
     * Builds a new {@link ThreeDSData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ThreeDSData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .eCI(getECI())
                .cAVV(getCAVV())
                .xID(getXID())
                .directoryServerTxnId(getDirectoryServerTxnId())
                .threeDSVersion(getThreeDSVersion())
                .transactionId(getTransactionId());
        return builder;
    }

    /**
     * Class to build instances of {@link ThreeDSData}.
     */
    public static class Builder {
        private String eCI;
        private String cAVV;
        private String xID;
        private String directoryServerTxnId;
        private String threeDSVersion;
        private String transactionId;



        /**
         * Setter for eCI.
         * @param  eCI  String value for eCI.
         * @return Builder
         */
        public Builder eCI(String eCI) {
            this.eCI = eCI;
            return this;
        }

        /**
         * Setter for cAVV.
         * @param  cAVV  String value for cAVV.
         * @return Builder
         */
        public Builder cAVV(String cAVV) {
            this.cAVV = cAVV;
            return this;
        }

        /**
         * Setter for xID.
         * @param  xID  String value for xID.
         * @return Builder
         */
        public Builder xID(String xID) {
            this.xID = xID;
            return this;
        }

        /**
         * Setter for directoryServerTxnId.
         * @param  directoryServerTxnId  String value for directoryServerTxnId.
         * @return Builder
         */
        public Builder directoryServerTxnId(String directoryServerTxnId) {
            this.directoryServerTxnId = directoryServerTxnId;
            return this;
        }

        /**
         * Setter for threeDSVersion.
         * @param  threeDSVersion  String value for threeDSVersion.
         * @return Builder
         */
        public Builder threeDSVersion(String threeDSVersion) {
            this.threeDSVersion = threeDSVersion;
            return this;
        }

        /**
         * Setter for transactionId.
         * @param  transactionId  String value for transactionId.
         * @return Builder
         */
        public Builder transactionId(String transactionId) {
            this.transactionId = transactionId;
            return this;
        }

        /**
         * Builds a new {@link ThreeDSData} object using the set fields.
         * @return {@link ThreeDSData}
         */
        public ThreeDSData build() {
            return new ThreeDSData(eCI, cAVV, xID, directoryServerTxnId, threeDSVersion,
                    transactionId);
        }
    }
}
