/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for UxSettingsModel type.
 */
public class UxSettingsModel {
    private List<Integer> displayedInstallmentOptions;

    /**
     * Default constructor.
     */
    public UxSettingsModel() {
    }

    /**
     * Initialization constructor.
     * @param  displayedInstallmentOptions  List of Integer value for displayedInstallmentOptions.
     */
    public UxSettingsModel(
            List<Integer> displayedInstallmentOptions) {
        this.displayedInstallmentOptions = displayedInstallmentOptions;
    }

    /**
     * Getter for DisplayedInstallmentOptions.
     * @return Returns the List of Integer
     */
    @JsonGetter("DisplayedInstallmentOptions")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<Integer> getDisplayedInstallmentOptions() {
        return displayedInstallmentOptions;
    }

    /**
     * Setter for DisplayedInstallmentOptions.
     * @param displayedInstallmentOptions Value for List of Integer
     */
    @JsonSetter("DisplayedInstallmentOptions")
    public void setDisplayedInstallmentOptions(List<Integer> displayedInstallmentOptions) {
        this.displayedInstallmentOptions = displayedInstallmentOptions;
    }

    /**
     * Converts this UxSettingsModel into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "UxSettingsModel [" + "displayedInstallmentOptions=" + displayedInstallmentOptions
                + "]";
    }

    /**
     * Builds a new {@link UxSettingsModel.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link UxSettingsModel.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .displayedInstallmentOptions(getDisplayedInstallmentOptions());
        return builder;
    }

    /**
     * Class to build instances of {@link UxSettingsModel}.
     */
    public static class Builder {
        private List<Integer> displayedInstallmentOptions;



        /**
         * Setter for displayedInstallmentOptions.
         * @param  displayedInstallmentOptions  List of Integer value for
         *         displayedInstallmentOptions.
         * @return Builder
         */
        public Builder displayedInstallmentOptions(List<Integer> displayedInstallmentOptions) {
            this.displayedInstallmentOptions = displayedInstallmentOptions;
            return this;
        }

        /**
         * Builds a new {@link UxSettingsModel} object using the set fields.
         * @return {@link UxSettingsModel}
         */
        public UxSettingsModel build() {
            return new UxSettingsModel(displayedInstallmentOptions);
        }
    }
}
