/*
 * SplititWebApiV3Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.splitit.sandbox.webapiv3.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for VerifyAuthorizationResponse type.
 */
public class VerifyAuthorizationResponse {
    private boolean isAuthorized;
    private Double authorizationAmount;
    private AuthorizationModel authorization;

    /**
     * Default constructor.
     */
    public VerifyAuthorizationResponse() {
    }

    /**
     * Initialization constructor.
     * @param  isAuthorized  boolean value for isAuthorized.
     * @param  authorizationAmount  Double value for authorizationAmount.
     * @param  authorization  AuthorizationModel value for authorization.
     */
    public VerifyAuthorizationResponse(
            boolean isAuthorized,
            Double authorizationAmount,
            AuthorizationModel authorization) {
        this.isAuthorized = isAuthorized;
        this.authorizationAmount = authorizationAmount;
        this.authorization = authorization;
    }

    /**
     * Getter for IsAuthorized.
     * @return Returns the boolean
     */
    @JsonGetter("IsAuthorized")
    public boolean getIsAuthorized() {
        return isAuthorized;
    }

    /**
     * Setter for IsAuthorized.
     * @param isAuthorized Value for boolean
     */
    @JsonSetter("IsAuthorized")
    public void setIsAuthorized(boolean isAuthorized) {
        this.isAuthorized = isAuthorized;
    }

    /**
     * Getter for AuthorizationAmount.
     * @return Returns the Double
     */
    @JsonGetter("AuthorizationAmount")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getAuthorizationAmount() {
        return authorizationAmount;
    }

    /**
     * Setter for AuthorizationAmount.
     * @param authorizationAmount Value for Double
     */
    @JsonSetter("AuthorizationAmount")
    public void setAuthorizationAmount(Double authorizationAmount) {
        this.authorizationAmount = authorizationAmount;
    }

    /**
     * Getter for Authorization.
     * @return Returns the AuthorizationModel
     */
    @JsonGetter("Authorization")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AuthorizationModel getAuthorization() {
        return authorization;
    }

    /**
     * Setter for Authorization.
     * @param authorization Value for AuthorizationModel
     */
    @JsonSetter("Authorization")
    public void setAuthorization(AuthorizationModel authorization) {
        this.authorization = authorization;
    }

    /**
     * Converts this VerifyAuthorizationResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "VerifyAuthorizationResponse [" + "isAuthorized=" + isAuthorized
                + ", authorizationAmount=" + authorizationAmount + ", authorization="
                + authorization + "]";
    }

    /**
     * Builds a new {@link VerifyAuthorizationResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link VerifyAuthorizationResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(isAuthorized)
                .authorizationAmount(getAuthorizationAmount())
                .authorization(getAuthorization());
        return builder;
    }

    /**
     * Class to build instances of {@link VerifyAuthorizationResponse}.
     */
    public static class Builder {
        private boolean isAuthorized;
        private Double authorizationAmount;
        private AuthorizationModel authorization;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  isAuthorized  boolean value for isAuthorized.
         */
        public Builder(boolean isAuthorized) {
            this.isAuthorized = isAuthorized;
        }

        /**
         * Setter for isAuthorized.
         * @param  isAuthorized  boolean value for isAuthorized.
         * @return Builder
         */
        public Builder isAuthorized(boolean isAuthorized) {
            this.isAuthorized = isAuthorized;
            return this;
        }

        /**
         * Setter for authorizationAmount.
         * @param  authorizationAmount  Double value for authorizationAmount.
         * @return Builder
         */
        public Builder authorizationAmount(Double authorizationAmount) {
            this.authorizationAmount = authorizationAmount;
            return this;
        }

        /**
         * Setter for authorization.
         * @param  authorization  AuthorizationModel value for authorization.
         * @return Builder
         */
        public Builder authorization(AuthorizationModel authorization) {
            this.authorization = authorization;
            return this;
        }

        /**
         * Builds a new {@link VerifyAuthorizationResponse} object using the set fields.
         * @return {@link VerifyAuthorizationResponse}
         */
        public VerifyAuthorizationResponse build() {
            return new VerifyAuthorizationResponse(isAuthorized, authorizationAmount,
                    authorization);
        }
    }
}
